### ISSUE TITLE
Unobfuscate the code

### ISSUE THREAD

**Issue by Infiniti20** [glixzzy/blooket-hack#1]
What's the point of putting this on GitHub if the code is obfuscated? I'd like to take a look at how you reverse engineered it, as I tried, but the data was very cryptic. It works really well, so I was just wondering how you accomplished that.

**Comment by glixzzy** [comment]
the only reason I put it on GitHub is because it can show up on the search engine

**Comment by Infiniti20** [comment]
hmmm

**Comment by RandyPlayzMC** [comment]
first issue nice
