### ISSUE TITLE
The new gamemode.

### ISSUE THREAD

**Issue by BlooketHackerx** [glixzzy/blooket-hack#1004]
Is there a way to unlock the new Blook rush gamemode with a spoofer of some sort? Like a plus membership spoof? I really hope there is a way because february 3rd is when it becomes free but that is soooo long to wait and since you have the best blooket hacks right now I thought there might be a way.

**Comment by hotboi69** [comment]
If you can find a spoof plus then yes but otherwise as of now no there is no possible way

**Comment by GooseterV** [comment]
Currently, there is no way to unlock it as a playable mode without plus. Hacks will not be made for the game mode until it is publicly released without plus.

**Comment by Zwalker559** [comment]
whyyyyy
