### ISSUE TITLE
More coins

### ISSUE THREAD

**Issue by Jonnnnnnnez** [glixzzy/blooket-hack#1011]
Any way to get more than 500 coins?

**Comment by FallGuysFan1234** [comment]
Sorry there is no way to get more, its server side which means that there is no way to bypass it at all D:

**Comment by GooseterV** [comment]
I believe this is a duplicate of [this](https://github.com/glixzzy/blooket-hack/issues/993)
To answer your question, there is no way to get more than 500 tokens a day.

**Comment by dogs221** [comment]
pepe

**Comment by jackisgoated** [comment]
pepe popo
