### ISSUE TITLE
The Spam open box hack is not working

### ISSUE THREAD

**Issue by JtaoOMG** [glixzzy/blooket-hack#1017]
I used the bookmarklet method with javascript: then the code. But it never gives me a response

**Comment by ilikecatss** [comment]
it doesnt work cuz glizzy made it not work

**Comment by ilikecatss** [comment]
cuz there is currently a ban wave on blooket

**Comment by ilikecatss** [comment]
sooo dont use spam open box
u get banned

**Comment by RedMythic1** [comment]
ohh, but how to make it work

**Comment by seven10018** [comment]
dont use it right now, blooket is banning people who use it

**Comment by CocoTech1861** [comment]
Ok. Thx for the warning

**Comment by glixzzy** [comment]
just fixed it
