### ISSUE TITLE
I was banned

### ISSUE THREAD

**Issue by Titanmaster203** [glixzzy/blooket-hack#1021]
I used the token hack and got banned how to fix this.

**Comment by amkoolok** [comment]
you will need to contact jack in blooket

**Comment by Staraner** [comment]
I have like 2 accounts and 1 of my accounts got banned by using add token hack

**Comment by GooseterV** [comment]
Contact blooket admins at contact-us@blooket.com to get unbanned ; names are Ben, Spencer, tommy
