### ISSUE TITLE
Get all blooks don't work anymore

### ISSUE THREAD

**Issue by Staraner** [glixzzy/blooket-hack#1027]

**Comment by glixzzy** [comment]
it works fine? Please provide more information instead of just saying something "doesn't work".

**Comment by clgtart** [comment]
wtf

**Comment by GooseterV** [comment]
Works fine

**Comment by hi1692** [comment]
If you reload the page, it's gone

**Comment by Staraner** [comment]
> If you reload the page, it's gone

I know that
