### ISSUE TITLE
Spam open boxes instantly bans you

### ISSUE THREAD

**Issue by Feedbackgeek** [glixzzy/blooket-hack#1030]
I got banned right after I did it.

**Comment by WaYaAtDawg** [comment]
good.

**Comment by FallGuysFan1234** [comment]
Wdym good?? Thats not good

**Comment by FallGuysFan1234** [comment]
It is really hard to open boxes so its unfair that you get banned for using spam open boxes

**Comment by FallGuysFan1234** [comment]
Blooket should just add an easier option instead of banning people that are having to hack the easier option

**Comment by FallGuysFan1234** [comment]
So thats not good WaYaAtDawg >:(

**Comment by FallGuysFan1234** [comment]
> I got banned right after I did it.

Try contacting blooket support! You might get unbanned :D

**Comment by FallGuysFan1234** [comment]
> good.



> good.

Please read my comments :D

**Comment by WaYaAtDawg** [comment]
nahh ur account is deader than micheal jackson

**Comment by GooseterV** [comment]
If your account gets banned, contact contact-us@blooket.com

Do not use spam sell and spam open if you don't want to get banned

**Comment by glixzzy** [comment]
try again?

**Comment by coolman3289** [comment]
Fixed

**Comment by amkoolok** [comment]
I have made a unban hack
I am still working on it but it is avaliable
