### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by bigguystevieb** [glixzzy/blooket-hack#1033]
Hey bro whats up, I really appreciate you taking your time doing these hacks. Although you do a great job, I wanted to let you know that the SPAM OPEN BOXES hack doesn't work just FYI. 

Thanks man really appreciate ya.

**Comment by glixzzy** [comment]
ummm I just tested it and it works perfectly fine?

If you mean it doesn't work with the bookmarklet method, I just fixed it so go and recheck

**Comment by bigguystevieb** [comment]
Thanks man I appreciate it.

**Comment by GooseterV** [comment]
It works fine now.
