### ISSUE TITLE
New hack game mode

### ISSUE THREAD

**Issue by hongquanhacker** [glixzzy/blooket-hack#1035]
Um...you can create a hack for blook rush please?

**Comment by WaYaAtDawg** [comment]
how bout u do it bozo

**Comment by FallGuysFan1234** [comment]
> how bout u do it bozo

Hey be quiet he is probably not sure how to make hacks >:(

**Comment by FallGuysFan1234** [comment]
> Um...you can create a hack for blook rush please?

I think glixzzy will only make a hack for it when it releases to everyone on February 3rd! :D

**Comment by FallGuysFan1234** [comment]
> Um...you can create a hack for blook rush please?

So im sorry but your gonna have to wait :(

**Comment by BOBKing123** [comment]
GLIXZY PLEASE MAKE BLOOK RUSH HACK SOON

**Comment by glixzzy** [comment]
mmm I tried but their isn't much to add tbh.
