### ISSUE TITLE
Need battle royal mode

### ISSUE THREAD

**Issue by nguyenphoang** [glixzzy/blooket-hack#1036]
Please support battle royal mode

**Comment by WaYaAtDawg** [comment]
Exactly my teacher only does that gamemode bc she knows i hack in all the other ones. WE NEED BATTLE ROYALE!!!

**Comment by FallGuysFan1234** [comment]
Tbh idk how they are able to do battle royale lol

**Comment by FallGuysFan1234** [comment]
> Exactly my teacher only does that gamemode bc she knows i hack in all the other ones. WE NEED BATTLE ROYALE!!!

Wow look at this you say "good" to someone getting banned for using spam open boxes which is the EASIER option for opening boxes yet you hack in all of the gamemodes bruh

**Comment by FallGuysFan1234** [comment]
> Please support battle royale mode

Sorry but im not sure there is really any way to hack battle royale :/

**Comment by bigguystevieb** [comment]
If this has nothing to do with BLOOKET HACKS please stop.

**Comment by WaYaAtDawg** [comment]
FallGuysFans yes the hell i do and theres not a DANG thing you can do bout it. Yo account dead as hell and im happy abt that.

**Comment by GooseterV** [comment]
1. What would you add in battle royale ?
2. This is the issues section of a hacks repository, please keep things on topic.

**Comment by glixzzy** [comment]
no, because their isn't anything to add.
