### ISSUE TITLE
i was banned from blooket

### ISSUE THREAD

**Issue by leonutana** [glixzzy/blooket-hack#1040]
im very sad now

**Comment by bigguystevieb** [comment]
That is pretty much your problem for using the hacks. @glixzzy said to use hacks at your own pace, so you chose to use hacks not anyone else.

**Comment by FallGuysFan1234** [comment]
> im very sad now

Aw man that sucks :(

**Comment by FallGuysFan1234** [comment]
> That is pretty much your problem for using the hacks. @glixzzy said to use hacks at your own pace, so you chose to use hacks not anyone else.

Well I mean he didn't blame it on glixzzy so I think he probably already knows lol

**Comment by bigguystevieb** [comment]
You could mind your own business!! Thank you very much!

**Comment by SubToNotSuper** [comment]
blooket updated their tos, they now ban people that use hacks

it's not gliz's fault, he even said to use hacks at your own pace and be cautious

**Comment by gimmy74** [comment]
> You could mind your own business!! Thank you very much!

You don't have to get nasty they are right

**Comment by Cayden625** [comment]
is it ip ban or just ban?

**Comment by GooseterV** [comment]
It's an account ban. If you don't want to get banned you shouldn't use the spam hacks. If you do get banned he isn't responsible for anything that happened.

**Comment by FallGuysFan1234** [comment]
> You could mind your own business!! Thank you very much!

How about no

**Comment by FallGuysFan1234** [comment]
> > You could mind your own business!! Thank you very much!
> 
> You don't have to get nasty they are right

Thanks :D

**Comment by glixzzy** [comment]
stop complaining in my issues https://github.com/glixzzy/blooket-hack#important
