### ISSUE TITLE
Get All Blooks not working

### ISSUE THREAD

**Issue by lng810** [glixzzy/blooket-hack#1043]
Every time I try to use it, it says that you must be on the Blook selecting page even if you already are.

**Comment by BlooketHackerx** [comment]
In a game idiot. It is not permanent you have to be in a game that someone is HOSTING and it unlocks all the blooks for you to pick and use THERE not on the blook sell page.

**Comment by bigguystevieb** [comment]
Don't call him an idiot, He just didn't know give the man a break. Jesus.

**Comment by hi1692** [comment]
chill bro

**Comment by FallGuysFan1234** [comment]
> In a game idiot. It is not permanent you have to be in a game that someone is HOSTING and it unlocks all the blooks for you to pick and use THERE not on the blook sell page.

Jesus dont call the man an idiot
