### ISSUE TITLE
I cant sell the blooks I get from get all blooks

### ISSUE THREAD

**Issue by SUIIIINALDO** [glixzzy/blooket-hack#1045]
Glixzzy can you make it so that i could sell the blookets i get from get all blookets

**Comment by bigguystevieb** [comment]
He did [CLICK HERE](https://github.com/glixzzy/blooket-hack/tree/main/global#selldupeblooksjs) AT THE VERY BOTTOM THERE IS A SELL DUPE BLOOKS. USE THAT.

**Comment by BOBKing123** [comment]
no he didnt, not when you use all blooks hack you cannot sell those

**Comment by SUIIIINALDO** [comment]
but can i sell the blooks i get from unlock every blook?

**Comment by glixzzy** [comment]
because get all blooks is a spoof it doesn't actually unlock the blooks.
