### ISSUE TITLE
Wait do we paste all the script and tell in the cmd/home screen of python app or just 24hr-toke-adder.py?

### ISSUE THREAD

**Issue by LeaderOfTheEvilFrenchGhostBlook** [glixzzy/blooket-hack#105]

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
Do you remove the word python and then type it and where is the cmd and how do you use python because I am stupid🤓🤓🤓

**Comment by Akul2010** [comment]
open cmd, and type python (filename).py

**Comment by kgsensei** [comment]
Win+R then type cmd and press enter.
