### ISSUE TITLE
YouTube Question

### ISSUE THREAD

**Issue by bigguystevieb** [glixzzy/blooket-hack#1050]
Hey @glixzzy I was curious if you wouldn't mind if I post a YT video on this HACK. If you allow me to, let me know your YT channel and I''ll give you credits in the description. If yeah and you wanna check out my channel here is the link: https://www.youtube.com/channel/UCTcXMPnaWxWcQzsEHPlMhxw

**Comment by glixzzy** [comment]
You are most welcome to make videos on this tool. If you want to give credit you can just link my twitter: https://twitter.com/glizuwu
