### ISSUE TITLE
Just wanted to make a little note for glixzzy :D

### ISSUE THREAD

**Issue by FallGuysFan1234** [glixzzy/blooket-hack#1055]
Hey glixzzy! I know it doesnt really matter, but if you see this then I just wanted to say that you accidentally made a typo on the add tokens hack! Let me show you the code real quick: async function getName() {
    const response = await fetch('https://api.blooket.com/api/users/verify-token', {
        method: "GET",
        headers: {
            "accept": "application/json, text/plain, */*",
            "accept-language": "en-US,en;q=0.9,ru;q=0.8",
        },
        credentials: "include"
    });
    const data = await response.json();

    return data.name;
};

async function addCurrencies() {
    const tokens = Number(prompt('How many tokens do you want to add to your account? (500 daily)'));

    if (tokens > 500) {
        alert('You can only add up to 500 tokens daily.');
    };

    const response = await fetch('https://api.blooket.com/api/users/add-rewards', {
        method: "PUT",
        headers: {
            "referer": "https://www.blooket.com/",
            "content-type": "application/json",
        },
        credentials: "include",
        body: JSON.stringify({
            addedTokens: tokens,
            addedXp: 300,
            name: await getName()
        })
    });

    if (response.status == 200) {
        alert(`${tokens} tokens and 300 XP added to your account!`);
    } else {
        alert('An error occured.');
    };

};

addCurrencies(); 
At the part where it says an error occurred, all you did was just forget to add an extra r so if you wanted to you could probably fix it! I know its not really a serious issue, but I just wanted to let you know :D

**Comment by glixzzy** [comment]
you can make a pull request here: https://github.com/glixzzy/blooket-hack/pulls you don't gotta make a issue
