### ISSUE TITLE
🥇  NEW TOKEN LIMT 🥇 

### ISSUE THREAD

**Issue by amkoolok** [glixzzy/blooket-hack#1063]
525 IS THE NEW MAX TOKENS PER DAY 
"ONLY IF YOU HAVE A STUDENT ACOUNT"

**Comment by BOBKing123** [comment]
HOW DO YOU CHECK IF YOU HAVE STUDENT ACCOUNT

**Comment by FallGuysFan1234** [comment]
Omg really??

**Comment by FallGuysFan1234** [comment]
Actually I think you might be lying...

**Comment by GooseterV** [comment]
The token limit has never changed.

**Comment by glixzzy** [comment]
not true.

**Comment by amkoolok** [comment]
im not sure but maybe


________________________________
