### ISSUE TITLE
Idea for a new hack

### ISSUE THREAD

**Issue by MrGamer-FS** [glixzzy/blooket-hack#1066]
Is it possible to make a crypto hack hack so that you can't be hacked by anyone in-game? And I don't mean like other people using glizzy hacks just so people can't take your crypto? Thank you

**Comment by FallGuysFan1234** [comment]
> Is it possible to make a crypto hack hack so that you can't be hacked by anyone in-game? And I don't mean like other people using glizzy hacks just so people can't take your crypto? Thank you

That would be cool! :D

**Comment by hi1692** [comment]
cool

**Comment by Telantix** [comment]
i agree
