### ISSUE TITLE
Please Add Battle Royal Hacks

### ISSUE THREAD

**Issue by Zaffarese** [glixzzy/blooket-hack#1067]
The getEveryAnswerCorrect.js hack does not work for Battle Royal, but it does work for every other game mode. I would like to know if you can add Battle Royal Hacks or let the getEveryAnswerCorrect.js hack to work for Battle Royal. 

There is a picture of what happens below.

![Screenshot 2022-02-01 12 30 26 PM](https://user-images.githubusercontent.com/98838537/152019706-a2c3c7ea-7f2f-4af5-b6fe-16f7d44bebd6.png)

**Comment by glixzzy** [comment]
can you not read? it tells you thats its not supported for that game mode because no.
