### ISSUE TITLE
Would this be posssible - make it so the game thinks you are a Plus Member

### ISSUE THREAD

**Issue by coolman3289** [glixzzy/blooket-hack#1069]
I am not sure if it is server sided or not, but if this can be done, what you would do, is use it on a page (eg. Host game page) and click on something the requires plus. It is Probobly not possible for you to have all plus features, but some… well @glixzzy you know better than anyone. If it is possible, it would be great.

**Comment by coolman3289** [comment]
Gbasil.dev has a plus spoof, so I know that’s possible

**Comment by glixzzy** [comment]
yeah probably

**Comment by coolman3289** [comment]
Will you consider making it? It would Probobly be one of the (if not the most) used cheats

**Comment by coolman3289** [comment]
Would be very cool
