### ISSUE TITLE
Hack idea

### ISSUE THREAD

**Issue by SirMadMa** [glixzzy/blooket-hack#1077]
this isn't an issue, and actually here to thank you, and ask for a hack. (you don't need to) but i want to be able to change the chance of specific blooks. I didn't see if someone else proposed this or if it isn't possible, but i think it would be cool to add!

**Comment by E10DezNuts** [comment]
I have tried this and it didn't work at all. But maybe gliz has a solution?

**Comment by SirMadMa** [comment]
Hopefully

**Comment by glixzzy** [comment]
Not possible, thats server sided.
