### ISSUE TITLE
Doesn't work at all.

### ISSUE THREAD

**Issue by flux101** [glixzzy/blooket-hack#1090]
When I enter the code in the console it says this: VM169:1 Refused to connect to 'https://raw.githubusercontent.com/glixzzy/blooket-hack/main/main.js' because it violates the following Content Security Policy directive: "connect-src 'self' https://api.blooket.com https://fb.blooket.com https://mediasvc.blooket.com https://blooket.s3.us-east-2.amazonaws.com https://kit.fontawesome.com https://ka-f.fontawesome.com https://www.google-analytics.com https://www.googleapis.com https://firebase.googleapis.com https://firebaseinstallations.googleapis.com https://*.firebaseio.com wss://*.firebaseio.com https://securetoken.googleapis.com https://media.blooket.com https://api.cloudinary.com https://images.unsplash.com".

(anonymous) @ VM169:1
VM169:1 Refused to connect to 'https://raw.githubusercontent.com/glixzzy/blooket-hack/main/main.js' because it violates the document's Content Security Policy.
(anonymous) @ VM169:1
VM169:1 Uncaught (in promise) TypeError: Failed to fetch
    at <anonymous>:1:1

**Comment by netsaosa** [comment]
fixed
