### ISSUE TITLE
hacks are not working 

### ISSUE THREAD

**Issue by noneedforusername** [glixzzy/blooket-hack#1103]
all the hacks are broken except add tokens please fix this before monday

**Comment by Jonnnnnnnez** [comment]
yes they should

**Comment by Eviehu708** [comment]
that is also happening to me except all my brothers hax are working

**Comment by noneedforusername** [comment]
well its not working

**Comment by Jonnnnnnnez** [comment]
death

**Comment by Jonnnnnnnez** [comment]
Theyy on vacay ?

**Comment by Eviehu708** [comment]
maybe
