### ISSUE TITLE
None of the hacks are working!!!

### ISSUE THREAD

**Issue by KimaKween** [glixzzy/blooket-hack#1108]
The hacks simply arent working. i think it's because of the new update, but can you plz fix this? thx

**Comment by Eviehu708** [comment]
Yea but i think add tokens is working

**Comment by jquadri** [comment]
it works for me

**Comment by KiwiDaBestKitty** [comment]
Ya only the add cash is working for me

**Comment by Eviehu708** [comment]
yeah but the rest are not

**Comment by glixzzy** [comment]
v4 has just been released! https://github.com/glixzzy/blooket-hack
