### ISSUE TITLE
Sugjeston

### ISSUE THREAD

**Issue by jquadri** [glixzzy/blooket-hack#1109]
Helooooooooo, can you make a cheat that lowers the cost of boxes plz

**Comment by jquadri** [comment]
o and btw glizzy if u see this my friend claims that they are you and making all of these hacks, is ur name alexander

**Comment by FallGuysFan1234** [comment]
Im sorry @jquadri but I dont think glixzzy can make hacks that are as op as that as mostly everything like adding more than 500 tokens is server sided, which means that its impossible to make a hack for it D:

**Comment by jquadri** [comment]
ok :(

**Comment by jquadri** [comment]
or would making it so blooks sell for more

**Comment by glixzzy** [comment]
impossible
