### ISSUE TITLE
The Infinite food level works, but all my customers give me $0 so like....

### ISSUE THREAD

**Issue by ghost** [glixzzy/blooket-hack#1115]
so whenever i try to run the code, all my plates turn black like they're supposed to, but people give me no money. Any way you can fix that? cause if you can, that would be epic. I'm not really a big fan of cafe though and this is for live streams.

**Comment by fatherbaja** [comment]
yeah it doesnt work for me either.

**Comment by glixzzy** [comment]
sometimes they pay you. i think its a problem within blooket. But this new update should have fixed it
