### ISSUE TITLE
the hacks usually only work once unless you reload the page

### ISSUE THREAD

**Issue by zathestic** [glixzzy/blooket-hack#1116]

**Comment by cph101** [comment]
The hacks only change the content of the webpage, not modify the actual code stored on the Blooket server.

**Comment by Zelkicks** [comment]
For clarification, you can run more than one hack on one page because of v4. You still cannot, however, run the same hack twice.

**Comment by Gowixx** [comment]
The problem occurs here: 
![image](https://user-images.githubusercontent.com/57415348/153109828-6e44dea7-7480-4baa-a115-0455c2a34f97.png
If you try to run the script again, it won't work as the variable is a constant, and is already declared

**Comment by glixzzy** [comment]
fixed
