### ISSUE TITLE
blookrush file setblooks.js not work wwhen attackinhg other it back the blooks

### ISSUE THREAD

**Issue by Cretawwin3** [glixzzy/blooket-hack#1119]

**Comment by Cretawwin3** [comment]
pls fix tht

**Comment by Zelkicks** [comment]
> pls fix tht

yeah I tried it too, but you worded it weird.
Basically, all your blooks disappear when you try to attack/defend.

**Comment by coolman3289** [comment]
Why, 50 or so is plenty

**Comment by 548573** [comment]
> > pls fix tht
> 
> yeah I tried it too, but you worded it weird. Basically, all your blooks disappear when you try to attack/defend.

**Comment by 548573** [comment]
> oh yes and I set 9999999999999999999999999999999999999 blooks and chrome crashed

**Comment by glixzzy** [comment]
fixed
