### ISSUE TITLE
ter

### ISSUE THREAD

**Issue by Andrew9254** [glixzzy/blooket-hack#1120]
drtggdbgbg

**Comment by MrGamer-FS** [comment]
Can someone close this issue

**Comment by FallGuysFan1234** [comment]
What the heck is this lol

**Comment by ilikecatss** [comment]
Don't open unnecessary issues like this. srsly, it gives the hack a bad rep.

**Comment by BL00KETN00B** [comment]
bruh why would you make this its annoying ok?
