### ISSUE TITLE
You said for v4 you would make it mobile compatible

### ISSUE THREAD

**Issue by coolman3289** [glixzzy/blooket-hack#1123]
:( you did not

**Comment by coolman3289** [comment]
I know some hacks are mobile compatible, does anyone know which ones (eg. Spam open boxes, sell dupes)

**Comment by coolman3289** [comment]
I am trying to do this for school, I can’t bring my pc to school…

**Comment by qwertxcs** [comment]
calm dowm lmao

**Comment by FallGuysFan1234** [comment]
> THATS YOUR PROBLEM.

Rude

**Comment by glixzzy** [comment]
umm it didn't really work out, really sorry.

**Comment by coolman3289** [comment]
Still going to try to do it eventually?
