### ISSUE TITLE
A lot of the hacks don’t work on Safari IPad

### ISSUE THREAD

**Issue by NotAwk** [glixzzy/blooket-hack#1129]
I use these in school, and most of the add (item for game mode) hacks don’t work. A lot of the general cheats don’t work as well, but I do have a few main ones working, such as Add Tokens, SpamOpenBox, Chest XRay (gold quest), and a few others. 
![64CF982B-D2AF-46CC-9E47-3FCAD9B0AA4C](https://user-images.githubusercontent.com/99204720/152849042-cf402716-9424-4a39-ad44-f841d7d2c829.jpeg)

**Comment by justinkopf** [comment]
Yes exactly I made my own hack with Siri Shortcuts, load it in with a JavaScript loader, and used the book market. Some of the hack work tho but not any of the game hacks

**Comment by glixzzy** [comment]
cause they are not supposed to Lol.
