### ISSUE TITLE
The token hack isnt working

### ISSUE THREAD

**Issue by ilikecatss** [glixzzy/blooket-hack#1139]
After using it, it just gives me an error message 
![image](https://user-images.githubusercontent.com/93303927/152890182-740e1322-284f-4e3f-9911-979ff52ad978.png)

**Comment by BL00KETN00B** [comment]
do the javascript: in the url bar and copy and paste the code again. hacks dont work on the same page twice still for some reasoon. just reload and try again

**Comment by glixzzy** [comment]
yeah i just fixed it!
