### ISSUE TITLE
blooket td set round does not work at all. and also can you make it so that blook drop rate gets lowered? (using hacks, of course.)

### ISSUE THREAD

**Issue by ghost** [glixzzy/blooket-hack#1141]
one more thing, when i tried setting a billions blooks in rush, that tab froze and my chromebook restarted.

**Comment by whutermeloon** [comment]
> one more thing, when i tried setting a billions blooks in rush, that tab froze and my chromebook restarted.

It is impossible to lower the blook drop rate, if it was possible, you could just send requests stating that you got a chroma when you only sent an API, the tower defense hack will be fixed shortly.

**Comment by Greenlio** [comment]
I don't even get how set round broke, there hasn't even been any noticeable changes to anything

**Comment by Zelkicks** [comment]
> one more thing, when i tried setting a billions blooks in rush, that tab froze and my chromebook restarted.

It has to render every single one of those blooks. Obviously a s***ty Chromebook can't handle that.

**Comment by FallGuysFan1234** [comment]
> > one more thing, when i tried setting a billions blooks in rush, that tab froze and my chromebook restarted.
> 
> It has to render every single one of those blooks. Obviously a s***ty Chromebook can't handle that.

Hey please don't swear D:

**Comment by glixzzy** [comment]
fixed.
