### ISSUE TITLE
Addtokens

### ISSUE THREAD

**Issue by balayke** [glixzzy/blooket-hack#1142]
When I insert the addtokens script, it lets me put in the quantity, but after it says an error occured.

**Comment by RoronoaDLuffy** [comment]
yea same
![image](https://user-images.githubusercontent.com/87439474/152900305-14fac9c6-9b81-490c-b2e7-bde5b4a90eba.png)

**Comment by dariusylin** [comment]
Me too!!

**Comment by 130701477** [comment]
Same so youse this lik https://www.gbasil.dev/blooket

**Comment by bachhacker** [comment]
me too

**Comment by glixzzy** [comment]
just fixed.
