### ISSUE TITLE
The daily coin hack doesn't work

### ISSUE THREAD

**Issue by JtaoOMG** [glixzzy/blooket-hack#1144]
I used the coin hack just now and it gave me an error message. I used the bookmarklet method.

**Comment by dariusylin** [comment]
Same for me...

**Comment by 130701477** [comment]
Yeah here use this link https://www.gbasil.dev/blooket

**Comment by whutermeloon** [comment]
> Yeah here use this link https://www.gbasil.dev/blooket

This link uses gliz's hack as a reference and uses the same method, so this site's hack will not work. Please actually work for tokens and this is just a game.

**Comment by glixzzy** [comment]
just fixed.
