### ISSUE TITLE
Blooket Hack Bug

### ISSUE THREAD

**Issue by justinkopf** [glixzzy/blooket-hack#1149]
All of the Blooket hacks are not working on iPad and iPhone and I tried the bookmarklet method and inserted the JavaScript but it says
JavaScript Exception
ReferenceError: Can't find variable: webpackJsonp
![D6E14B32-6B01-456D-842A-877DE0772612](https://user-images.githubusercontent.com/77589837/153081263-684168d7-6cfa-4080-b002-f08c95932641.jpeg)

**Comment by glixzzy** [comment]
because it doesnt work on mobile/ipad
