### ISSUE TITLE
Auto answer doesn't work for me

### ISSUE THREAD

**Issue by LeVuong2013** [glixzzy/blooket-hack#1154]
when i let auto answer work then it doesn't do anything

**Comment by noimno** [comment]
yes it does it makes every answer right for you not for anyone else .Only people with that hack can get every answer right but you can't do it in battle  royal

**Comment by glixzzy** [comment]
fixed.

**Comment by 3yellow7ve** [comment]
does it work on mobile???? because it doesn’t work when i do it
