### ISSUE TITLE
all hacks are broken

### ISSUE THREAD

**Issue by Ender-Gamer0262** [glixzzy/blooket-hack#1155]
every hack is currently broken, how long until a potential fix? also can you try adding something for the new gamemode

**Comment by glixzzy** [comment]
which hacks are broken? all of them work fine.

**Comment by malachibh** [comment]
ya they work fine i love them the only problem is that you have to reload pg to use it multiple times

**Comment by Briggan311** [comment]
> ya they work fine I love them the only problem is that you have to reload pg to use it multiple times

ya same thing is happening to me

**Comment by glizzy2189** [comment]
the add tokens not working can you also make a get 300 tim the alien

**Comment by malachibh** [comment]
> the add tokens not working can you also make a get 300 tim the alien

you have to exete out the tab when you do it and go back in a new tab

**Comment by glixzzy** [comment]
fixed
