### ISSUE TITLE
auto answer in classic

### ISSUE THREAD

**Issue by HappyArshu** [glixzzy/blooket-hack#1160]
auto-answer is not working nicely

**Comment by Zelkicks** [comment]
It might have issues because its new but if you just do get all answers correct, that should work in all modes now? Don't quote me on that, though, because I'm unsure.

**Comment by derinpilge** [comment]
Use gbasil.dev/blooket multitool bookmarklet. q is auto answer

**Comment by glixzzy** [comment]
should work now..?

**Comment by 29crain** [comment]
hay y is the chets not working
