### ISSUE TITLE
mad

### ISSUE THREAD

**Issue by elijahb12345** [glixzzy/blooket-hack#1170]
it wont let me

**Comment by Zelkicks** [comment]
Won't let you what?
Can you be specific? Like, at all?

**Comment by glixzzy** [comment]
for what game mode?

**Comment by suckmytitties** [comment]
i think global but there's alot of blooket coin hacks here

**Comment by hecker1234567890** [comment]
elijahb12345, you got to be specific

**Comment by glixzzy** [comment]
fixed
