### ISSUE TITLE
there is a bug

### ISSUE THREAD

**Issue by Briggan311** [glixzzy/blooket-hack#1174]
um you have to reload the tab to be able to use the hacks more than one time but for some, you only need to use them one time because it stays there if you click a link but still for hacks like set crypto and all of those hacks you need to reload the page and it sucks can you please try to fix this if you can we would love this thanks

**Comment by Briggan311** [comment]
ya maybe lets hope it gets fixed soon

**Comment by derinpilge** [comment]
qbasil.dev/blooket

**Comment by glixzzy** [comment]
yeah i'm aware :( I thought i fixed this in the v4 update

**Comment by glixzzy** [comment]
fixed
