### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by Criptc** [glixzzy/blooket-hack#1178]
the battle royal answerer is too slow, it takes sometimes 2 seconds when other people are doing it in 1.5

**Comment by BlooketHackerx** [comment]
Can you not spell? It is spelled ANSWERER NOT ANCERER!!!! UGH!!!!

**Comment by derinpilge** [comment]
Use the gbasil.dev/blooket or qbasil.dev/blooket auto answer it is way faster

**Comment by Briggan311** [comment]
> Use the gbasil.dev/blooket or qbasil.dev/blooket auto answer it is way faster

stop trying to steal his people away from him dude

**Comment by Briggan311** [comment]
> Use the gbasil.dev/blooket or qbasil.dev/blooket auto answer it is way faster

people like you suck get your people by earning them like glixzzy did and don't steal them from him

**Comment by FallGuysFan1234** [comment]
> > Use the gbasil.dev/blooket or qbasil.dev/blooket auto answer it is way faster
> 
> people like you suck get your people by earning them like glixzzy did and don't steal them from him

Hey they are just suggesting another site theres nothing wrong with that :D

**Comment by FallGuysFan1234** [comment]
> the battle royal ancerer is too slow, it takes sometimes 2 seconds when other people are doing it in 1.5

Yea it was kinda slow when I first did it lol

**Comment by derinpilge** [comment]
fucking shut up these notifications are so annoying

**Comment by MrGamer-FS** [comment]
then just unsubscribe 


> fucking shut up these notifications are so annoying

**Comment by glixzzy** [comment]
ok not my problem

**Comment by Criptc** [comment]
what war did I miss?
