### ISSUE TITLE
99999999999999 IQ SUGGESTION PLEASE LOOK!!!

### ISSUE THREAD

**Issue by derinpilge** [glixzzy/blooket-hack#1181]
I know if you hover your cursor above the "?" on boxes you can see the rates of pulling something. I've been wondering if @glixzzy could find a way to change the % of pulling something. Maybe like rainbow panda becoming 95%

**Comment by ilikecatss** [comment]
hmmmmm  it may not be possible (in my opinion)

**Comment by longsinger** [comment]
I DOnt like 500 DAILY
I WANT 500 WHEN EVER WE WANT

**Comment by Al4708** [comment]
> I DOnt like 500 DAILY I WANT 500 WHEN EVER WE WANT

They can't do that sadly because blooket itself only allows to collect 500 coins every 24 hours
