### ISSUE TITLE
The global add tokens is not working pleas fix

### ISSUE THREAD

**Issue by Hacked-Thunder** [glixzzy/blooket-hack#1182]
The global add tokes is not working, I did it and I waited a day(it daily) and then put in 500 and then it says ok, but when I refresh the page its still the same thing pls fix and see it

**Comment by dariusylin** [comment]
well it worked for me

**Comment by ilikecatss** [comment]
ye that happened to me yesterday, but it should work now

**Comment by minh2576** [comment]
it only works once

**Comment by Hacked-Thunder** [comment]
> it only works only 1/1day

ik but I waited 24 hours but I refresh nothing

**Comment by Hacked-Thunder** [comment]
ok thanks guys

**Comment by glixzzy** [comment]
i updated it get the script again.
