### ISSUE TITLE
Hacks are all broke

### ISSUE THREAD

**Issue by BlooketThings** [glixzzy/blooket-hack#1186]
You broke the codes with your annoying watermark. Also you made it like 8 pages long for no reason

**Comment by FallGuysFan1234** [comment]
Theres a watermark??

**Comment by FallGuysFan1234** [comment]
Dang I never knew that lol

**Comment by glixzzy** [comment]
Don't care, people are steal my work.

**Comment by coolman3289** [comment]
Oh… can you make it movable though (or dismissible)

**Comment by coolman3289** [comment]
Or maybe instead add a text box (like you do for prompts) saying it’s your hacks.

**Comment by coolman3289** [comment]
Or at least make the boxes not make it so you can only use one script at a time.
