### ISSUE TITLE
Get Cash in factory doesnt work, only tells you an error occurred, and get mega bot has an empty line

### ISSUE THREAD

**Issue by Riftyy** [glixzzy/blooket-hack#1188]
Yeah so whenever I try and use getCash it tells me “an error occurred, report it to the discord server?” And get mega bots line is just empty.

![128C9E17-229F-4272-A03F-60E399362DB0](https://user-images.githubusercontent.com/95542431/153442397-1ebbabae-4d0a-4611-b19c-4bc14e2d511e.jpeg)

![4BAFC024-D283-4ACF-B047-F1DD782D7923](https://user-images.githubusercontent.com/95542431/153442409-d2866020-92c5-4051-98a5-bdacfe6c00aa.jpeg)

**Comment by Sanford0316** [comment]
I never heard of it

**Comment by glixzzy** [comment]
no empty line??

**Comment by glixzzy** [comment]
should be fixed
