### ISSUE TITLE
Did the scripts get broken when they got moved?

### ISSUE THREAD

**Issue by Piplup7575** [glixzzy/blooket-hack#119]
Hey @glixzzy!
I can see everyone else is screaming that the hacks have moved, but @LuisGamingYT has found your website with the on it now ( https://schoolcheats.net/blooket/iexef5lt4f )
But the issue is that they are all broken and don't work. 
Will there be any way for you to fix this? 
Thank you!
(Also don't fix it until after Monday I want to see my classmates get mad as they all depend on it to win in class lmao)

**Comment by glixzzy** [comment]
Yes we’re working on a fix and I don’t own the website @varedz does.

**Comment by glixzzy** [comment]
fixed:  https://github.com/glixzzy/blooket-hack#video-tutorial

**Comment by Piplup7575** [comment]
Thank you!
