### ISSUE TITLE
Its Saying i cant get tokens

### ISSUE THREAD

**Issue by Voltfyhg** [glixzzy/blooket-hack#1202]
<img width="717" alt="m" src="https://user-images.githubusercontent.com/88753580/153532300-63459510-5d6e-48ef-bceb-fc68657bdf3a.PNG">
<img width="239" alt="Capture" src="https://user-images.githubusercontent.com/88753580/153532305-a5238b5e-dac1-4383-b27d-00ad9dbef8b9.PNG">

**Comment by Voltfyhg** [comment]
i dont know what to do

**Comment by BuggyAl** [comment]
update?

**Comment by glixzzy** [comment]
cause thats the wrong script, get the new updated script
