### ISSUE TITLE
When used as a bookmark, you are unable to click on the code.

### ISSUE THREAD

**Issue by LZ-iBozo** [glixzzy/blooket-hack#1207]
When I make turn the hack into a bookmark, I am unable to click on it. The mouse will stop at the border of the bookmark, and teleport over it.

**Comment by suckmytitties** [comment]
that happens to me too. just use fingers

**Comment by maxgamertyper** [comment]
I think that's just you too because I just tried it and it seemed to work so IDK maybe its a bug

**Comment by Rentuh** [comment]
> that happens to me too. just use fingers

not everyone has those touch screen computers or mobile

**Comment by glixzzy** [comment]
try again
