### ISSUE TITLE
Blooket rush hacks does this

### ISSUE THREAD

**Issue by coolman3289** [glixzzy/blooket-hack#1211]
It says that I am blocked from the game… oh the up side it works on mobile.

**Comment by coolman3289** [comment]
[https://ibb.co/Rg3T7fs](url)

**Comment by coolman3289** [comment]
That’s a picture

**Comment by coolman3289** [comment]
They probs have a new anti-cheat @glixzzy

**Comment by suckmytitties** [comment]
were you on a live game? they have anti cheat on in those streams

**Comment by suckmytitties** [comment]
like youtube live stream 24/7 blooket games

**Comment by glixzzy** [comment]
fixed
