### ISSUE TITLE
Why hacks are under maintenance?!!!

### ISSUE THREAD

**Issue by Staraner** [glixzzy/blooket-hack#1219]

**Comment by 2SturdyZayy** [comment]
Exactly!

**Comment by crosscha** [comment]
probably because their was a bug and their getting it fixing right now

**Comment by R3nH4s1ssu3s** [comment]
Perhaps it's fixed now? I will go check.

**Comment by Staraner** [comment]
It has been 2 days

**Comment by dogeking69** [comment]
i know it anowing some one fix this

**Comment by R3nH4s1ssu3s** [comment]
Someone said they're under maintenance because they are making a new update, so we have to play the waiting game.

**Comment by glixzzy** [comment]
they were being fixed, try again
