### ISSUE TITLE
this is not really a issue but i need help

### ISSUE THREAD

**Issue by waffles8609** [glixzzy/blooket-hack#1220]
im kinda dump so even with the tutorials i don't know how to get it can someone join a discord call with me and walk me threw it or you can email me at wafflemanbilly@gmail.com

**Comment by F3ArMrJames** [comment]
GitHub is under maintenance right now and it will be under maintenance for a few more hours please be patent. thank you

**Comment by F3ArMrJames** [comment]
It wont work because its under maintenance

**Comment by waffles8609** [comment]
oh thank you

**Comment by F3ArMrJames** [comment]
your welcome
