### ISSUE TITLE
Im so need help with token

### ISSUE THREAD

**Issue by hongquanhacker** [glixzzy/blooket-hack#1221]
The token hack is broken and im can't hack 500 token

**Comment by 301Bri** [comment]
Same

**Comment by F3ArMrJames** [comment]
GitHub is under maintenance right now and it will be under maintenance for a few more hours please be patent. thank you

**Comment by Staraner** [comment]
Same

**Comment by moiboigod** [comment]
me too

**Comment by glixzzy** [comment]
back up!
