### ISSUE TITLE
5th Issue: Spam open boxes make you log out

### ISSUE THREAD

**Issue by Staraner** [glixzzy/blooket-hack#1227]

**Comment by Bacon-boi** [comment]
yea i got same issue

**Comment by Telantix** [comment]
again, using the spam boxes has a very very high chance of getting your account banned and usually after about 3 times of using it and the third time you get logged out you cannot log back in and your account will be suspended.

**Comment by Greenlio** [comment]
api spam causes suspensions.
read the bottom of the readme before you use it
