### ISSUE TITLE
Guys you can get a easy chroma today only!!!!

### ISSUE THREAD

**Issue by FallGuysFan1234** [glixzzy/blooket-hack#1228]
Guys make sure to head on over to the market section of blooket RIGHT NOW and there you will see that the lovely frog is there for one day only, costs 500 tokens, and is a chroma rarity!! So this could be your very first chroma!!! (Side note: this is for valentines day only :D) Here is some images if you don't believe me: 
![image](https://user-images.githubusercontent.com/92480033/153874131-b26682b9-fb46-48ad-b230-1525952959e5.png)
![image](https://user-images.githubusercontent.com/92480033/153965896-a2f8cbfc-60f4-4fb0-81bf-140a945dd782.png)
And lastly, 
![image](https://user-images.githubusercontent.com/92480033/153965838-433d9fb4-e290-4157-953f-f5ae6393c938.png)
:D

**Comment by Telantix** [comment]
yo thanks

**Comment by Rentuh** [comment]
I just sacrificed a astronaut and mega bot.. WORTH IT

**Comment by LordofPenguins** [comment]
I have 3

**Comment by coolman3289** [comment]
… gxlizzy has a 500 coin everyday hack… why not use that. Austronuat and mega is not worth this for me

**Comment by coolman3289** [comment]
@LordofPenguins why? There’s not trading in blooket.

**Comment by FallGuysFan1234** [comment]
> yo thanks

Your welcome :D

**Comment by FallGuysFan1234** [comment]
> @LordofPenguins why? There’s not trading in blooket.

It has been rumored that it might be coming to blooket soon :D

**Comment by FallGuysFan1234** [comment]
> … gxlizzy has a 500 coin everyday hack… why not use that. Austronuat and mega is not worth this for me

Yea your right

**Comment by FallGuysFan1234** [comment]
> I have 3

Nice!

**Comment by FallGuysFan1234** [comment]
> I just sacrificed a astronaut and mega bot.. WORTH IT

Well to be honest you could've used the Add Tokens hack but you dont have to lol

**Comment by JulianaLeHacker** [comment]
I wish i could get more tokens than just 500 lol

**Comment by FallGuysFan1234** [comment]
> I wish i could get more tokens than just 500 lol

Same lol

**Comment by FallGuysFan1234** [comment]
Also my stats are https://www.blooket.com/stats?name=GracefulGhost incase anyone was curious :D

**Comment by Hacked-Thunder** [comment]
BRO thanks you soo much

**Comment by termy0000wormy** [comment]
i used the hack so i dit do have to sacrafice a thing

**Comment by Greenlio** [comment]
this issue has gone on for so long wtf

**Comment by suckmytitties** [comment]
what the
