### ISSUE TITLE
Make it so you can use multiple hacks at a time

### ISSUE THREAD

**Issue by coolman3289** [glixzzy/blooket-hack#1229]
Would be great!

**Comment by CharEmily** [comment]
Hello coolman3289,

You can use multiple hacks at once.

Are you Talking about in-game or [`Addtokens`](https://github.com/glixzzy/blooket-hack/blob/main/global/addTokens.js)
or ?

**Comment by coolman3289** [comment]
In game

**Comment by FallGuysFan1234** [comment]
> Hello coolman3289,
> 
> You can use multiple hacks at once.
> 
> Are you Talking about in-game or [`Addtokens`](https://github.com/glixzzy/blooket-hack/blob/main/global/addTokens.js) or ?

Hey Emily! :D

**Comment by Greenlio** [comment]
you can use many at once lol?

**Comment by glixzzy** [comment]
This has been finally fixed in the 4.2 update
