### ISSUE TITLE
Tower defence

### ISSUE THREAD

**Issue by StoneStrick** [glixzzy/blooket-hack#1234]
Um why do none of the tower defence hacks work.

**Comment by Greenlio** [comment]
they do

**Comment by StoneStrick** [comment]
Which ones

**Comment by StoneStrick** [comment]
![CFA33540-73D3-43EA-8C8E-A47FEA760AE0](https://user-images.githubusercontent.com/99690218/154092162-02cdf37d-a28e-4314-b7ed-f197ec0077a5.png)

**Comment by Piplup7575** [comment]
dont think they work on mobile
