### ISSUE TITLE
Hi your thing didnt give me the tokens

### ISSUE THREAD

**Issue by WoofRulesAll** [glixzzy/blooket-hack#1236]
so i havent played blooket in a few days but when i opened the thing and did the hack for 500 tokens to get the lovely frog it didnt give me anything and it wont let me grind either saying i reached the max daily limit even though i didnt receive the tokens.

**Comment by FallGuysFan1234** [comment]
Well the thing is you have to refresh for the tokens to show up :D

**Comment by ilikecatss** [comment]
depends on what time zone ur in

**Comment by Greenlio** [comment]
@ilikecatss no it doesn't at all

@FallGuysFan1234 is correct. refresh for tokens to show up
