### ISSUE TITLE
King of Hearts is better than Mega Bot in factory, pls change it.

### ISSUE THREAD

**Issue by ViriDescent77** [glixzzy/blooket-hack#1239]
Mega bots make 1b/5s at max lvl (no synergy bonus) while the King of Hearts makes 1.5b/5s (no synergy bonus). Pls change the hack to give us Kings of Hearts.

**Comment by R3nH4s1ssu3s** [comment]
This is not really an issue, so put it in the discussions.*
I like your idea, unfortunately I think glizzy is already dealing with some issues or just doesn't have the motivation to read any issues and discussions today.

**Comment by Greenlio** [comment]
@R3nH4s1ssu3s you smoking that pack bruh

issues are for enhancements, hence why there's an enhancement tag.. don't be weird lol

**Comment by Riftyy** [comment]
Just going to put this out here, megabot is better than king, i did the math:
King of Hearts= 4.5b/5s = 13.5b:15s
Bot= 3b/3s = 15b:15s

**Comment by Minesraft2** [comment]
the all mega bots has a synergy bonus, which is higher than the king of hearts synergy

**Comment by Minesraft2** [comment]
bozo

**Comment by Cretawwin3** [comment]
king of hearts all synergy = 8,3 Billion cash : 5 =1,66 Billion cash 
Mega bot all synergy= 5,5 billion cash : 3 = 1,833333333333333... billion cash  
mega bot no synergy = 1 billion cash : 3= 333333333,333333.... million cash
King of hearts no synergy = 1,5 billion : 5 =300000000 million cash
so mega bot is better
Belive me, I knew this
