### ISSUE TITLE
I need to say made by gliz gone  

### ISSUE THREAD

**Issue by CuriousCoder1232** [glixzzy/blooket-hack#1243]
It's that when it says made by gliz the thing is im trying to hack but everyones learning how to do it and some got bannned i think but i need to hack without my freinds noticing it

**Comment by TheRandomCat** [comment]
It is so you can't steal it.

**Comment by AFLUFYPROTOGEN** [comment]
it is drag abbele

**Comment by AFLUFYPROTOGEN** [comment]
just do not say u own it

**Comment by CuriousCoder1232** [comment]
@AFLUFYPROTOGEN

**Comment by glixzzy** [comment]
no

**Comment by AFLUFYPROTOGEN** [comment]
use this https://www.gbasil.dev/blooket
