### ISSUE TITLE
sell dupes is broken

### ISSUE THREAD

**Issue by Dentamon** [glixzzy/blooket-hack#1247]
whenever I do the sell dupe, it says "hack activated" then when you press ok it says "an error occurred"

**Comment by AFLUFYPROTOGEN** [comment]
did u do it like this : what box: Space

**Comment by AFLUFYPROTOGEN** [comment]
exactly like the titel

**Comment by coolman3289** [comment]
Get newest version

**Comment by R3nH4s1ssu3s** [comment]
It's patched, I think.
![image](https://user-images.githubusercontent.com/99570560/154190103-3d2a1fad-0dce-4cd4-936b-d975b6c1a08a.png)

**Comment by coolman3289** [comment]
It work for me…
