### ISSUE TITLE
error in code ? 

### ISSUE THREAD

**Issue by joeyneedsmoney** [glixzzy/blooket-hack#1252]
adding 500 tokens and says an error has occurred

**Comment by coolman3289** [comment]
Yeah, you need the newest version

**Comment by joeyneedsmoney** [comment]
how do i get the newest v

**Comment by BrickKing09** [comment]
ya how get newest version?

**Comment by coolman3289** [comment]
Copy it from the file

**Comment by coolman3289** [comment]
Do what you did to get the old version

**Comment by coolman3289** [comment]
But now the code is updated

**Comment by BrickKing09** [comment]
k
