### ISSUE TITLE
When will hacks be back up

### ISSUE THREAD

**Issue by rickriord** [glixzzy/blooket-hack#1273]
will hacks ever be back up

**Comment by longsinger** [comment]
yea

**Comment by crunchey** [comment]
i need

**Comment by BlooketHackerx** [comment]
They wont be back up he want you to pay for them now.

**Comment by BlooketHackerx** [comment]
2 bitcoin. He want money for hack so now he is not giving anymore.

**Comment by MAXXINCODING** [comment]
bruh this sucks

**Comment by MAXXINCODING** [comment]
i used this so much

**Comment by crunchey** [comment]
it does suck

**Comment by Zelkicks** [comment]
Hackers usually get money from trusted people by making them pay Bitcoin to them. Do not worry, he most likely got hacked.

**Comment by Zelkicks** [comment]
For now, don't run it in your browser as the hackers may have included a cookie logger.

**Comment by glixzzy** [comment]
in a couple hours, see https://github.com/glixzzy/blooket-hack/issues/1288
