### ISSUE TITLE
urmmmm the spam open box wont work

### ISSUE THREAD

**Issue by SoSecretThat** [glixzzy/blooket-hack#128]

**Comment by glixzzy** [comment]
uh it seems to be working? you can see how i had 525 tokens and then i had about 200 tokens after i refreshed
https://user-images.githubusercontent.com/73669084/137659088-7d08743c-fdb3-423d-a2f8-e028764d1b85.mp4

**Comment by SoSecretThat** [comment]
xd

**Comment by SoSecretThat** [comment]
i try it like 10 time
it wont work
