### ISSUE TITLE
Hacks are down, why?

### ISSUE THREAD

**Issue by glixzzy** [glixzzy/blooket-hack#1288]
Hello, I am now aware of the cheats asking for btc or eth. This message was totally random and the hacks **are still free** and always will be! 

Blooket changed something which made this hack break. Just be patient I'll fix it soon.

Also I have not been hacked, dont worry.

If you want to know when the hacks will be back up the best thing to do is join the discord server: https://discord.gg/blooketcom

**Comment by Zelkicks** [comment]
Good. Also, sorry for telling everyone you got hacked. I guess I didn't make it clear enough that it was just speculation.

**Comment by nathanweel** [comment]
That's good to know thx

**Comment by inyourface34456** [comment]
I herd that they were pay now (for 2 bitcoin, or $82k).  Good to know that is not true!

**Comment by glixzzy** [comment]
> I herd that they were pay now (for 2 bitcoin, or $82k). Good to know that is not true!

The code displayed random messages, but i'm pretty sure it was 2$ in bitcoin. Anyway, it was an accident and the hacks will always be free!

**Comment by FallGuysFan1234** [comment]
> > I herd that they were pay now (for 2 bitcoin, or $82k). Good to know that is not true!
> 
> The code displayed random messages, but i'm pretty sure it was 2$ in bitcoin. Anyway, it was an accident and the hacks will always be free!

Im glad you weren't hacked glixzzy! Also thanks for making the Add Tokens hack and other hacks, because it made blooket way easier since im too lazy to grind tokens lol

**Comment by FallGuysFan1234** [comment]
> huh hoi huh hoi 😪

?

**Comment by FallGuysFan1234** [comment]
10th comment lul

**Comment by JENeEeE** [comment]
are the hacks up yet?

**Comment by noneedforusername** [comment]
youtube.com/watch?v=q0hL5CQ1X7k&t=11s why i sed huh hoi huh hoi 😭

**Comment by noneedforusername** [comment]
youtube.com/watch?v=q0hL5CQ1X7k&t=11s

**Comment by noneedforusername** [comment]
![maxresdefault](https://user-images.githubusercontent.com/98358829/154346024-28544488-04e2-4602-ba96-51bf78de66ce.jpg)

**Comment by Imanerd2010** [comment]
I just finally got out of class but I hope that the hacks are going to get fixed soon. I can wait a couple of days

**Comment by J0SU3sWXRLD** [comment]
I hope it can be fixed thank god i got the lion but i still want the megalodon idk how im still getting the tokens even tho the hack is down im still getting the 500 daliy

**Comment by LOLboi6** [comment]
I hope the hacks still work we all hope it works please click the thumbs up button if you hope they work.

**Comment by ilikecatss** [comment]
#glizzy4thewin

**Comment by glixzzy** [comment]
Fixed.
