### ISSUE TITLE
pls put back the old one  , the new one dont work for me

### ISSUE THREAD

**Issue by TZY1351** [glixzzy/blooket-hack#129]

**Comment by glixzzy** [comment]
are there any errors? 

if you don't even know how it works i suggest watching the tutorial: https://github.com/glixzzy/blooket-hack#video-tutorial

**Comment by N00b34** [comment]
pleas put back the old one

**Comment by N00b34** [comment]
PLEASSSSSSSEEEEEE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by TZY1351** [comment]
Yea
