### ISSUE TITLE
Glad to see glixzzy wasn't hacked! :D

### ISSUE THREAD

**Issue by FallGuysFan1234** [glixzzy/blooket-hack#1291]
Poggers!

**Comment by noneedforusername** [comment]
but hacks dont work
:/

**Comment by Imanerd2010** [comment]
same! Im glad to hear that the hacks arent down forever

**Comment by FallGuysFan1234** [comment]
> but hacks dont work :/

Yea your right D:

**Comment by FallGuysFan1234** [comment]
> same! Im glad to hear that the hacks arent down forever

Yea :D
