### ISSUE TITLE
How Do I Add The Javascripts on iPad?

### ISSUE THREAD

**Issue by eletrickball** [glixzzy/blooket-hack#1300]
Only some Javascripts work when I add “JavaScript:”. On others, it doesn’t work. It says stuff like, “Code not available”. But for others, it works. What do I do about it? (Also when are the hacks coming back I really need my 500 Blooket Coins for today.)

**Comment by Imanerd2010** [comment]
probably the same way as you do on computer, click the tab??

**Comment by eletrickball** [comment]
I don’t think so. I add it to favorites, and paste the codes in the address. Only some codes work.
![A7568165-2A17-459B-B24D-296B12110146](https://user-images.githubusercontent.com/99839457/154354849-4614936a-b029-4482-82fa-078e91c9dd9e.jpeg)

**Comment by eletrickball** [comment]
@glixzzy, do you know?

**Comment by eletrickball** [comment]
How to change the codes so that it words on the iPad? If not, could you maybe try to recode the Javascript so that it works on iPad? If not it’s ok. I think you need to add something like “JavaScript:” at the very beginning. Thanks!

**Comment by glixzzy** [comment]
not supported

**Comment by coolman3289** [comment]
Same hacks do work on iPad, but most don’t. The 500 coins, spam boxes, and sell dupes work for me, and for some reason blooketrush hacks worked for me, although usually game hacks don’t work for me.
