### ISSUE TITLE
Blooket hacks 

### ISSUE THREAD

**Issue by Br-blip-ma** [glixzzy/blooket-hack#1303]
I'm sorry if I'm annoying you I just want to know when the hacks will be fixed I appreciate your work!!!! I know you said to join the discord but at the moment I cannot join.

**Comment by banana-nana** [comment]
where are u at school if so do you have discord if so use this proxy https://bossbaby21.herokuapp.com/

**Comment by FallGuysFan1234** [comment]
> I'm sorry if I'm annoying you I just want to know when the hacks will be fixed I appreciate your work!!!! I know you said to join the discord but at the moment I cannot join.

Yea same im on a school chromebook so I cant join discord D:

**Comment by Br-blip-ma** [comment]
Glixzzy are you almost done fixing the hacks?
