### ISSUE TITLE
Hey guys, the hacks are now back and running so you can use them finally!

### ISSUE THREAD

**Issue by FallGuysFan1234** [glixzzy/blooket-hack#1307]
The add tokens hack worked for me so that most likely means that all the hacks are back up, and glixzzy also added new crypto hacks and you should go check them out! Poggers! :D

**Comment by glixzzy** [comment]
yeah!!!

**Comment by Melloe-code** [comment]
Ik I just used them in my blooket HW

**Comment by Melloe-code** [comment]
thanks for fixing tho

**Comment by R3nH4s1ssu3s** [comment]
hip hip hooray for glizzy

**Comment by SoulsCombat** [comment]
LES GOOOOOOOOOOOOOOOOOOOOOOOOOOOOO!!!!!!!!!!!!!!!

**Comment by LOLboi6** [comment]
OMG ty soo much glixzzy for taking your time for fixing the hacks. Click the thumbs up.

**Comment by Imanerd2010** [comment]
YOUR THE BEST GLIXZZY! Tysm!

**Comment by noneedforusername** [comment]
![download](https://user-images.githubusercontent.com/98358829/154510994-07dbd134-b161-4604-bc7c-88d997e8fd72.jpg)
