### ISSUE TITLE
Hacks Not Working

### ISSUE THREAD

**Issue by SoulsCombat** [glixzzy/blooket-hack#1308]
Some hacks might work but sometimes it says "an error has occur" i hope you can fix it.

**Comment by Melloe-code** [comment]
i can help

**Comment by Melloe-code** [comment]
all you have to do is get the code from school cheats and paste it in the console. remember, the hacks just now opened up

**Comment by SoulsCombat** [comment]
Yes i did do that but sometimes it didn't work
