### ISSUE TITLE
What does remove hack and setcustom password do? Does it give the opportunity for the other person to guess that password?

### ISSUE THREAD

**Issue by coolman3289** [glixzzy/blooket-hack#1310]
?

**Comment by glixzzy** [comment]
why can't you join the discord server and ask these kind of questions?

I was really about to block you today for telling others I'm making these hacks cost 44k dollars. The message said "2$ in btc" which was a total accident. This hack will always be free.

**Comment by coolman3289** [comment]
… how was I supposed to know that at the time… someone told about the bitcoin message, and what was “$2 in bitcoin” became “2 bitcoin”. I apologize, I love your work, I had no idea. I am confused how that would randomly pop up, but I’m not gonna question it.

**Comment by coolman3289** [comment]
Also also don’t have discord available to me all the time.

**Comment by coolman3289** [comment]
I was in school.

**Comment by coolman3289** [comment]
And stop attacking me, the message shown May not have been your fualt, but it was definitely not mine. What was is supposed to need from a message that clearly said that the hacks would cost money.
