### ISSUE TITLE
Tokens and XP not coming through blooket.

### ISSUE THREAD

**Issue by DepressedBoi345** [glixzzy/blooket-hack#1311]
This is my second day trying this hack, and the hack says it's available I type in how much I want and then I refresh the tab but it it doesn't give me the tokens and xp.

**Comment by LOLboi6** [comment]
The hacks work. Thank you glixzzy for taking your time to make them work.

**Comment by twixe123** [comment]
> 

You cannot reload

**Comment by R3nH4s1ssu3s** [comment]
Don't reload. If it still doesn't work then idk.

**Comment by Imanerd2010** [comment]
2 things. 1) Don't reload; that just makes the problem harder. 2) Make sure you didn't put anything above 500 because the hack only works with that number. No more.

**Comment by coolman3289** [comment]
Also, get the newest version

**Comment by Teddiursa123** [comment]
It doesnt work

**Comment by Piplup7575** [comment]
It works
You have to wait about 70-80 sec after running before reloading the page, and they **should** update
