### ISSUE TITLE
WHY STOP THE HACKS????

### ISSUE THREAD

**Issue by SoulsCombat** [glixzzy/blooket-hack#1336]
Bruh, why did @glixzzy stop this hack dude? Just tell me why....... I wonder how, I wonder why

**Comment by glixzzy** [comment]
please read here: https://twitter.com/glizuwu/status/1494434918285381633

![image](https://user-images.githubusercontent.com/73669084/154604820-3291705a-d838-42e8-9b13-c7b4905695d5.png)

**Comment by Riftyy** [comment]
Thats harsh

**Comment by SoulsCombat** [comment]
> please read here: https://twitter.com/glizuwu/status/1494434918285381633
> 
> **WILL BE BACK 2/18/22 8 AM EST WHEN SCHOOL STARTS, PLEASE DON'T LEAVE AND HELP ME OUT!!**
> 
> ![image](https://user-images.githubusercontent.com/73669084/154604820-3291705a-d838-42e8-9b13-c7b4905695d5.png)

Is it UK EST?

**Comment by SoulsCombat** [comment]
just say "SHUT MAN, I NEED TO GO TO WORK" maybe it works

**Comment by geograjuice** [comment]
why no more hacks?

**Comment by SoulsCombat** [comment]
BRUHHH

**Comment by SoulsCombat** [comment]
Is the hack working now @glixzzy?

**Comment by FallGuysFan1234** [comment]
> who the heck even is ben

He's the creator of blooket D:

**Comment by Piplup7575** [comment]
> > please read here: https://twitter.com/glizuwu/status/1494434918285381633
> > **WILL BE BACK 2/18/22 8 AM EST WHEN SCHOOL STARTS, PLEASE DON'T LEAVE AND HELP ME OUT!!**
> > ![image](https://user-images.githubusercontent.com/73669084/154604820-3291705a-d838-42e8-9b13-c7b4905695d5.png)
> 
> Is it UK EST?

8 AM EST (Eastern Standard Time, or east coast of USA)

**Comment by Parzival750** [comment]
> who the heck even is ben

Creator of Blooket

**Comment by Parzival750** [comment]
Are Hacks back up yet?

**Comment by Parzival750** [comment]
Yay! It's back!!!

**Comment by Parzival750** [comment]
I think you can close this.

**Comment by glixzzy** [comment]
backs up
