### ISSUE TITLE
Permission to redistribute?

### ISSUE THREAD

**Issue by inyourface34456** [glixzzy/blooket-hack#1354]
I have a [repository](https://github.com/inyourface34456/bookmarklets-website)  that includes you bookmarklets as of version 4.2.  This is just asking if it is OK for me to put them up like that.

P.S: If you want to look at them, you can find them under Bookmarklets>site specific bookmarklets>Booklet.

**Comment by partyManz** [comment]
Yeah it is good

**Comment by glixzzy** [comment]
yeah as long as i get the credit.
