### ISSUE TITLE
Its been 5 hours or 6 when hacks are down.

### ISSUE THREAD

**Issue by blooket500k** [glixzzy/blooket-hack#1368]
it dont take that long to fix hacks gliz.

**Comment by Greenlio** [comment]
it does but ok

**Comment by Smiggles333** [comment]
Once you've done that, all you'll have to do is click "multitool" while in blooket, and it'll open a panel with all sorts of hacks, including almost all of the hacks that can be found here.

**Comment by Smiggles333** [comment]
who
