### ISSUE TITLE
it isnt working

### ISSUE THREAD

**Issue by littledangerman** [glixzzy/blooket-hack#1391]
when will it work agin glixzzy

**Comment by blooket500k** [comment]
tmr at 4 PM EST

**Comment by Candleknight** [comment]
this works so in the meantime try this! https://www.gbasil.dev/blooket

**Comment by Smiggles333** [comment]
![Screenshot 2022-02-19 3 49 39 PM](https://user-images.githubusercontent.com/100011821/154821768-97158c67-daa1-4dea-b150-f2c17ff786fa.png) 
                           
                                                              Thanks Gliz!!

**Comment by Smiggles333** [comment]
> this works so in the meantime try this! https://www.gbasil.dev/blooket

**Comment by littledangerman** [comment]
I do use gbasil

**Comment by littledangerman** [comment]
why delete
