### ISSUE TITLE
10th Issue: This is the 6th day hacks are down when will the hack get fixed???!!!

### ISSUE THREAD

**Issue by Staraner** [glixzzy/blooket-hack#1396]

**Comment by Rookiehecker** [comment]
Gbasil.dev
![Screenshot (13)](https://user-images.githubusercontent.com/94798292/154827240-0555e5a4-684f-423f-85ed-56e20a2c6525.png)

**Comment by Rookiehecker** [comment]
gbasil.dev

**Comment by Candleknight** [comment]
gbasil is less reliable but sure good enough
