### ISSUE TITLE
token console code

### ISSUE THREAD

**Issue by chillman-crypto** [glixzzy/blooket-hack#14]
It keeps telling me they coins are added yet they arent what do i do

**Comment by glixzzy** [comment]
for what game?

**Comment by chillman-crypto** [comment]
its not for a  game i think its for the market
https://github.com/glixzzy/blooket-hack/blob/78fe8380d6e127e36eb0a66d63630721f33ec17b/global/addTokens.js

**Comment by glixzzy** [comment]
you can add 500 once a day, if you try to add again it won't work
