### ISSUE TITLE
when I go to schoolcheats.net/pages.dev/blooket 

### ISSUE THREAD

**Issue by Blooket-dude** [glixzzy/blooket-hack#1412]
when I go to schoolcheats.net/pages.dev/blooket I cant click any of the script tabs like when I click it nothing opens up. is this on the websites end or is it on my end? because the normal schoolcheats.net is block for me since im on a school computer.

**Comment by AFLUFYPROTOGEN** [comment]
use this https://www.gbasil.dev/blooket read the instructions works on all game modes

**Comment by BlooketHacks123** [comment]
What I did was copy the hacks and put them in my bookmarks bar so they still work

**Comment by yodaluca23** [comment]
> when I go to schoolcheats.net/pages.dev/blooket I cant click any of the script tabs like when I click it nothing opens up. is this on the websites end or is it on my end? because the normal schoolcheats.net is block for me since im on a school computer.

Most likely because the schoolcheats.net/pages.dev/blooket site still connects to the original site, and your school has likely blocked any traffic from your device to the original site's IP...

**Comment by glixzzy** [comment]
its https://schoolcheats,net/blooket

**Comment by coolman3289** [comment]
That’s blocked

**Comment by coolman3289** [comment]
It would be cool if they could make a GitHub, or a various copy of the site.

**Comment by coolman3289** [comment]
@glixzzy
