### ISSUE TITLE
HELP PLEASE SOMEONE

### ISSUE THREAD

**Issue by Blooket-dude** [glixzzy/blooket-hack#1434]
when I go to schoolcheats.net/pages.dev/blooket I cant click any of the script tabs like when I click it nothing opens up. is this on the websites end or is it on my end? because the normal schoolcheats.net is block for me since im on a school computer. is there anyway I can fix that. or is ther anyway you can make a website for everyone?

**Comment by ZasticBradyn** [comment]
https://github.com/glixzzy/blooket-hack/tree/f3da3a769e03f8ca650dea2fe5ccc6a2dae57b07

**Comment by Damonsudo** [comment]
pretty sure he cant really "make a website for everyone" because all school firewalls/ blocking software is different.

**Comment by Dentamon** [comment]
I have made a new github with the old code of add tokens.  (Still works!)  Here is the link.  Oh, I forgot to add credit, but thank you glixzzy for all the things you have done for us :)  https://github.com/Dentamon/The-Blooket-Hack

**Comment by ZasticBradyn** [comment]
> I have made a new github with the old code of add tokens. (Still works!) Here is the link. Oh, I forgot to add credit, but thank you glixzzy for all the things you have done for us :) https://github.com/Dentamon/The-Blooket-Hack

check ur pull requests on the repo

**Comment by ThirdEyeBoi** [comment]
> when I go to schoolcheats.net/pages.dev/blooket I cant click any of the script tabs like when I click it nothing opens up. is this on the websites end or is it on my end? because the normal schoolcheats.net is block for me since im on a school computer. is there anyway I can fix that. or is ther anyway you can make a website for everyone?

Since the code is so big it did the same for me but all you have to do is wait a little and it will load.

**Comment by BSH45868** [comment]
Bruh ZastucBradyn literally copied Dentamon

**Comment by Blooket-dude** [comment]
@ThirdEyeBoi what do you mean I have to wait a little bit.

**Comment by ThirdEyeBoi** [comment]
What I mean is leave the page open for about 3 min and do something else, at least it was about 3 min for me.

**Comment by ThirdEyeBoi** [comment]
Did It Work?

**Comment by glixzzy** [comment]
its https://schoolcheats.pages.dev/blooket
