### ISSUE TITLE
old hacks back

### ISSUE THREAD

**Issue by blooketismylife** [glixzzy/blooket-hack#147]
bro im on a school chromebook so i cant use this new website hack and i can only do hacks in bookmarklet so add it back i cant get 500 coins daily anymore

**Comment by username122323** [comment]
they still exist.
make a new bookmarklet with exact code:
 javascript:fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/main.js").then((res) => res.text().then((t) => eval(t)))
then click bookmark while on blooket
it will take you to website
click global, then choose add tokens or spam boxes, whichever you use (these are the most popular)
then follow instructions, and it will do the command on the blooket page by itself (you NEED to keep blooket open I think)
