### ISSUE TITLE
plz bring back the hacks

### ISSUE THREAD

**Issue by hacker112394843** [glixzzy/blooket-hack#156]

**Comment by username122323** [comment]
they still exist.
make a new bookmarklet with exact code:
 javascript:fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/main.js").then((res) => res.text().then((t) => eval(t)))
then click bookmark while on blooket
it will take you to website
click global, then choose add tokens or spam boxes, whichever you use (these are the most popular)
then follow instructions, and it will do the command on the blooket page by itself (you NEED to keep blooket open I think)
