### ISSUE TITLE
how to use the spam open box can make a vid i dont know how xd

### ISSUE THREAD

**Issue by SoSecretThat** [glixzzy/blooket-hack#17]

**Comment by glixzzy** [comment]
solution here: https://github.com/glixzzy/blooket-hack/issues/18

**Comment by forliwe** [comment]
![Screenshot 2021-10-01 1 44 05 PM](https://user-images.githubusercontent.com/91738157/135671320-8b3683bf-b4d6-4fb1-841b-4bac8f9fcdfd.png)
