### ISSUE TITLE
all answers correct

### ISSUE THREAD

**Issue by Masterx50** [glixzzy/blooket-hack#20]
this hack does not work for battle royale. also can you add hacks for battle royale and classic?

**Comment by glixzzy** [comment]
ah thanks for letting me know...

there is no cheats i can add for battle royale or classic yet. They are just normal games but if i find one i will definitely add it

**Comment by Masterx50** [comment]
i also noticed in fishing it says correct but gives you another question as if you got it wrong.

**Comment by glixzzy** [comment]
ill look into the new fishing frenzy game mode later. thanks for letting me know
