### ISSUE TITLE
Can u make a glitch to get all blooks??

### ISSUE THREAD

**Issue by TheGamerMaX** [glixzzy/blooket-hack#21]
Especially chromas!

**Comment by glixzzy** [comment]
thats server sided, i tried so much but i couldn't get it to work, sorry

**Comment by TheGamerMaX** [comment]
when you do the join game bot thing you always have colored astronaut

**Comment by TheGamerMaX** [comment]
plz find a way i need it and I rely on u

**Comment by glixzzy** [comment]
yeah cause thats automated, i can't control the bots

**Comment by TheGamerMaX** [comment]
oh

**Comment by TheGamerMaX** [comment]
sorry to waste your time but I have one more question. Is there a way to get past 500 daily coin limit???

**Comment by glixzzy** [comment]
that is server sided too, can't bypass it sorry.

**Comment by TheGamerMaX** [comment]
ok
