### ISSUE TITLE
all answer correct modification request

### ISSUE THREAD

**Issue by ToastOnInk** [glixzzy/blooket-hack#22]
I would like a feature in the getallanswerscorrect script, or you can make a new one. Basically before the script starts it asks of a scale from 1 to 100, then when you answer the question theres that chance of getting it correct. I would've just forked but your code is damn messy.

**Comment by glixzzy** [comment]
most of my code is obfuscated, its not "messy". Anyway the feature you suggested, uhhh i find it lame but ill see if i have time to add it

**Comment by ToastOnInk** [comment]
yea im not offended its lame ngl but if i get them all correct stuff just goes wrong

**Comment by ToastOnInk** [comment]
plus why are you even obfuscating (i never really seen much about obfuscated stuff so idk much about it), its not like you're not letting others modify or whatsoever

**Comment by ToastOnInk** [comment]
nevermind dont need it anymore add if you want i guess
