### ISSUE TITLE
Blooket is not picking up the amount on crypto i got…?????

### ISSUE THREAD

**Issue by Scpwolf123** [glixzzy/blooket-hack#275]
![image](https://user-images.githubusercontent.com/70712351/139532978-8189a3a6-7589-4c9c-989d-cdb956809b9e.png)

The user "k" doesn't have the hacks on... the other users have the hacks on but the currency is not showing on the host screen or the end of game  ![image](https://user-images.githubusercontent.com/70712351/139533030-60b28d03-b48f-4081-878a-bd709f4f37d2.png)

Idk if this also happens to other games e.g tower  defense.....etc

**Comment by resolvebeta** [comment]
are you scp wolf from yt?

**Comment by Scpwolf123** [comment]
> are you scp wolf from yt?

No sry, my usernames are responsible, SW049=ScpWolf040. I do know his channel tho

**Comment by Scpwolf123** [comment]
I just checked the game option "Common" the skin and answer hacks work perfect fine so I think it's only the "crypto" game that's not working...The skin hack in "crypto" still works btw....

**Comment by glixzzy** [comment]
this is not meant to be used on mobile/ipad
