### ISSUE TITLE
I'm a bit upset

### ISSUE THREAD

**Issue by milocreator** [glixzzy/blooket-hack#281]
Hello. I am a frequent user of your blooket hacks. Actually I'm new but used it a lot this weekend. Once I did the 500 a day token thing, I'm not getting my tokens, and I can't earn any real tokens any more. If you didn't understand, let me explain once more. I'm not getting my 500 tokens, and I'm not earning any more tokens.

**Comment by glixzzy** [comment]
it works perfectly fine I just tried.

**Comment by WonderPig9** [comment]
Yea everything works
