### ISSUE TITLE
After adding coins in tower of doom, you cannot pick a card

### ISSUE THREAD

**Issue by yee-negative** [glixzzy/blooket-hack#283]

**Comment by wolfgoo** [comment]
???

**Comment by yee-negative** [comment]
i meant when you finish beating the levels you can add coins, but after that .you cannot continuue because cant pick a acard

**Comment by ilikecatss** [comment]
yes this is true
I am also experiencing issues like this

**Comment by MRLightnes** [comment]
same

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
Ya

**Comment by burninbarney** [comment]
Same and they took down my one because "it works for them".

**Comment by glixzzy** [comment]
That’s blookets problem not mine
