### ISSUE TITLE
blooket

### ISSUE THREAD

**Issue by aa2d** [glixzzy/blooket-hack#284]
spam box doesn't work at all tower of doom doesn't either

**Comment by ilikecatss** [comment]
maybe you dont have enough tokens for opening boxes

**Comment by aa2d** [comment]
> maybe you dont have enough tokens for opening boxes
i have like 480 token and it dosent open a single one

**Comment by aa2d** [comment]
> maybe you dont have enough tokens for opening boxes

nvm i have to buy atleast one

**Comment by ilikecatss** [comment]
what box were you trying to buy?

**Comment by ilikecatss** [comment]
for example: if you wanted to open space box, you must not type Space Box just type "Space"

**Comment by ilikecatss** [comment]
and also remember to make the first letter for the name of the box an uppercase letter

**Comment by ilikecatss** [comment]
Aquatic, Space, Spooky, Medival etc

**Comment by wolfgoo** [comment]
......

**Comment by wolfgoo** [comment]
No, I try it but it don't work.

**Comment by wolfgoo** [comment]
I got 12,060 money but it also don't work.

**Comment by MRLightnes** [comment]
bruh

**Comment by wolfgoo** [comment]
???

**Comment by wolfgoo** [comment]
> bruh
???

**Comment by glixzzy** [comment]
It works fine
