### ISSUE TITLE
please

### ISSUE THREAD

**Issue by RoshenNaidu** [glixzzy/blooket-hack#285]
can you @glixzzy  do a add exp hack please

**Comment by Nobody-720** [comment]
For class pass ?

**Comment by Nobody-720** [comment]
note: This cheat also includes adding max xp for the day

Open console (ctrl + shift + j) and paste the following:

fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/global/addTokens.js").then((res) => res.text().then((t) => eval(t)))

[ If Your Level Didn't Change After 3 days ... Try This { Try This Hack Next Day In Your Stats }
