### ISSUE TITLE
Where did the FAQ go?

### ISSUE THREAD

**Issue by wesley61** [glixzzy/blooket-hack#286]
UWU

**Comment by Nobody-720** [comment]
what do FAQ means ? ;=;

**Comment by wolfgoo** [comment]
don't know?

**Comment by Piplup7575** [comment]
FAQ means Frequently Asked Questions
Glixzzy removed it.

**Comment by BackVoid8** [comment]
Don't ask

**Comment by FreezeLucif3r** [comment]
Also, when your questions are answered, can you close the issues yourself? It's a lot less work For @glixzzy  and the others.

**Comment by wesley61** [comment]
why did Glixzzy remove it?

**Comment by wesley61** [comment]
Frequently Asked Questions
Note: Before you make an issue or ask someone on the support server, please go through the FAQ to check if it is in here. Thank you.

Q: The all permanent blooks isn't working!

A: Yes, it was a joke and does not permanently work.

Q: Is there any way to bypass the 500 token per day limit or change the time before reset timer?

A: Nope! This is simply not possible, because it is server-side.

Q: Can I make custom blook skins and use them in game?

A: Yes and no. This is possible even without these hacks, if you gain enough xp through grinding or using the addTokens hack, you will be able to make your own custom blooks under the Stats tab on Blooket. But if you are trying to upload your own fully custom blooks, this is not currently possible, as all blooks are server-side.

Q: Ahhh! My account was banned! Was I just banned for hacking blooket? Screen Shot 2021-10-07 at 6 39 06 PM

A: Probably not, this is a bug that is going around that doesn't let you in your account for a short period of time. The best thing to do is just wait it out.
