### ISSUE TITLE
pls

### ISSUE THREAD

**Issue by TurboSlayer10** [glixzzy/blooket-hack#29]
can you guys pls make a way to get all books PERMANENTLY if this is possible pls do so thank you

**Comment by PhillieWillie** [comment]
That would be a good thing to add if you could @glixzzy !

**Comment by DarklordX89X** [comment]
This is currently not possible or it is very deep inside the main source of Blooket. No one has found a way to do this. They use an API to unlock blooks and we don't have the source of the API because it's not public. Yes, people have done deep searches into the code, I have aswell.
