### ISSUE TITLE
the spam open box wont work

### ISSUE THREAD

**Issue by jyfrnj** [glixzzy/blooket-hack#293]

**Comment by wolfgoo** [comment]
Yes, it don't work.

**Comment by jyfrnj** [comment]
why doesn't it work already?

**Comment by wolfgoo** [comment]
The glixzzy say it work.But I try many times also don't work.  :<

**Comment by wolfgoo** [comment]
i don't know it work or don't work.

**Comment by wolfgoo** [comment]
maybe is we don't how to use.

**Comment by jyfrnj** [comment]
it worked already :)

**Comment by wolfgoo** [comment]
ok

**Comment by wolfgoo** [comment]
how to use???
I don't know???

**Comment by jyfrnj** [comment]
go to the glixzzy / blooket hack main page, scroll down, copy link and it would send you to another website

**Comment by jyfrnj** [comment]
fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/main.js")
.then((res) => res.text()
.then((t) => eval(t)))
