### ISSUE TITLE
learn some hack

### ISSUE THREAD

**Issue by itzmederpy** [glixzzy/blooket-hack#295]
i gonna teach hack

**Comment by wolfgoo** [comment]
what hack???

**Comment by wolfgoo** [comment]
You now about deeep.io 2021 hacks???

**Comment by wolfgoo** [comment]
hallo

**Comment by wolfgoo** [comment]
hello————————————————————————————————-

**Comment by wolfgoo** [comment]
..............

**Comment by wolfgoo** [comment]
> i gonna teach hack
 You know about deeep.io 2021 hacks???

**Comment by wolfgoo** [comment]
piz respond me.

**Comment by CatusKing** [comment]
Two huge problems with this issue.
1. Learn English, please
2. Calm down @wolfgoo because it can take some people up to 24 hours to respond because you know time zones

**Comment by FreezeLucif3r** [comment]
You can't just "learn some hack". What does that even mean anyway?

**Comment by CatusKing** [comment]
Lmfaooo

**Comment by wolfgoo** [comment]
......
