### ISSUE TITLE
 Tower of Doom addCoins.js

### ISSUE THREAD

**Issue by FreezeLucif3r** [glixzzy/blooket-hack#297]
The script is working, but when I am at the rewards page (which is the only page that works) I try to click the card that I want and it ends up not letting me. I'm forced to refresh and the gold is not saved. I have tried 3 times to no avail.

**Comment by VirtualFiber415** [comment]
do 999 coins i think thats the max you can do without breaking it

**Comment by FreezeLucif3r** [comment]
Thanks.
