### ISSUE TITLE
not an issue but a question 

### ISSUE THREAD

**Issue by Anxietycontolsme** [glixzzy/blooket-hack#300]
is it possible to make a hack/client just for the Xp or No?  Thanks

**Comment by HHHHHHUUYTF** [comment]
No the xp is gained through the ammount of games you play once you get to level 45 you have to play the game modes to level up.

**Comment by FreezeLucif3r** [comment]
Yeah, there is no point in making one just for XP because you get max both coins and XP when you run the addtokens.js in global.
