### ISSUE TITLE
can't get all the blooks 

### ISSUE THREAD

**Issue by OVPElements** [glixzzy/blooket-hack#301]
ive tried but i just can't get them why

**Comment by i-do-not-wish-to-be-alive** [comment]
if you read the bottom, it says it was a joke, and only works in host games, if you're the participant/player

**Comment by i-do-not-wish-to-be-alive** [comment]
wait its in global

**Comment by burninbarney** [comment]
> if you read the bottom, it says it was a joke, and only works in host games, if you're the participant/player

Yup he is right
At least you can use it.

**Comment by glixzzy** [comment]
you have to be on /play/lobby page while being in a live game
