### ISSUE TITLE
wont let me get anything

### ISSUE THREAD

**Issue by Doninic** [glixzzy/blooket-hack#302]
The get all blooks doesnt work and the get gold and tokens dont work

**Comment by burninbarney** [comment]
Tbh I think you dont know how to use it.
It works fine for me and I think everyone else.
Msh me 4 help.

**Comment by burninbarney** [comment]
msg*

**Comment by glixzzy** [comment]
https://github.com/glixzzy/blooket-hack/issues/301#issuecomment-958587129

**Comment by Doninic** [comment]
No i know how to use it ive seen many people use it but it only works for
tower defence and 500 tokens and when i tried it with tower of doom nothing
happened
