### ISSUE TITLE
Spam open boxes doesn't work!

### ISSUE THREAD

**Issue by hihihhihihihihihihihihihih** [glixzzy/blooket-hack#303]

**Comment by Nobody-720** [comment]
If Yu use **Bookmark** then write the full name of the box .
[ **EXP : Space Box** ]

If Yu use **Console** then write the name of the box only . 
[ **EXP : Space** ]

**Comment by hihihhihihihihihihihihihih** [comment]
Thanks!

**Comment by wolfgoo** [comment]
It also don't work.........................
