### ISSUE TITLE
Request: Combined hacks

### ISSUE THREAD

**Issue by wesley61** [glixzzy/blooket-hack#308]
What I mean by this is that maybe we can have a hack that can be activated with a button. So an `if` code for all of the functions in the gamemode. then we don't have to paste the code again and again.

**Comment by Ihatr1** [comment]
You can make a "bookmarklet" which accomplishes this function.

For example,
`javascript:fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/global/addTokens.js").then((res) => res.text().then((t) => eval(t)))`
will add 500 tokens to your account when the bookmark is clicked.

**Comment by glixzzy** [comment]
theres something already for that.

use this:

```js
fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/main.js")
.then((res) => res.text()
.then((t) => eval(t)))
```
