### ISSUE TITLE
Request: Add Crypto Box Esp pls

### ISSUE THREAD

**Issue by yee-negative** [glixzzy/blooket-hack#309]
add crypto box esp  , the gold one can.so can add the crypto one pls

**Comment by Piplup7575** [comment]
*crypto hack
Good idea!

**Comment by wolfgoo** [comment]
crypto box is bot box

**Comment by wolfgoo** [comment]
bot box is crypto box

**Comment by burninbarney** [comment]
I am so confused.

**Comment by Nobody-720** [comment]
same ;=;

**Comment by Nobody-720** [comment]
![image](https://user-images.githubusercontent.com/92516697/140597812-8d6f68a5-f77e-4977-a72c-f07f5f000025.png)


[ U mean this ESP ]

**Comment by glixzzy** [comment]
no
