### ISSUE TITLE
Flood don't work

### ISSUE THREAD

**Issue by helloieat** [glixzzy/blooket-hack#31]
rip

**Comment by IvanYam12123** [comment]
why flood did not work

**Comment by helloieat** [comment]
I made it into  bookmarklet and it ended up not working

**Comment by glixzzy** [comment]
i know you get paused in debugger, you just have to be patient with it

**Comment by glixzzy** [comment]
i added a tutorial https://github.com/glixzzy/blooket-hack/blob/main/global/README.md

**Comment by helloieat** [comment]
Alr
