### ISSUE TITLE
227162

### ISSUE THREAD

**Issue by Quangdai2** [glixzzy/blooket-hack#310]
Aananba

**Comment by Quangdai2** [comment]
Sksjaj

**Comment by Quangdai2** [comment]
Shshsh

**Comment by Ihatr1** [comment]
Dude, stop.

Issues are meant to report issues, not to spam around.
Stop acting like you're eight, get off of GitHub, and do something else with your life.

**Comment by FreezeLucif3r** [comment]
I wonder what language he's speaking.

**Comment by burninbarney** [comment]
he is speaking sugonesse I understand it. If you want I can explain the language its really easy just ask whats sugonese.
