### ISSUE TITLE
Can you make that you can add more than 500 tokens AddTokens.js

### ISSUE THREAD

**Issue by Arjun-Bhatnagar** [glixzzy/blooket-hack#312]
please

**Comment by Piplup7575** [comment]
Nope, 500 tokens a day is server side no mater what you do that is the limit.

**Comment by FreezeLucif3r** [comment]
Bruh how many issues have been opened about this. We need a new FAQ lol.

**Comment by FreezeLucif3r** [comment]
![Uploading download (2).jpeg…]()

**Comment by CABCITY** [comment]
The creator can't control what blooket sets for the max tokens for the day unless you somehow convince blooket to change the daily limit than yeah you can get more than 500 tokens

**Comment by FreezeLucif3r** [comment]
![download (2)](https://user-images.githubusercontent.com/92932466/140337291-efeebec7-3164-4d8b-bff2-6e9847c25b02.jpeg)

**Comment by Piplup7575** [comment]
no

**Comment by ilikecatss** [comment]
i can only say 2 words....
SERVER SIDE

**Comment by FreezeLucif3r** [comment]
@echo off
title Expros Virus Scanner
:start
echo Welcome to Expros Virus Scanner!
echo[
echo First, Choose Your Scan Type.
echo 1. Full Scan
echo 2. Quick Scan

set /p c=C:\
if "%c%" == "1" goto full
if "%c%" == "2" goto quick

cls
goto start

:full
cls
echo Scanning...
echo[
echo Pre-Scan Preperations
echo [-----]
ping 192.0.2.2 -n 1 -w 1000 > nul

cls
echo Scanning...
echo[
echo Pre-Scan Preperations
echo [=----]
ping 192.0.2.2 -n 1 -w 1000 > nul

cls
echo Scanning...
echo[
echo Pre-Scan Preperations
echo [==---]
ping 192.0.2.2 -n 1 -w 1000 > nul

cls
echo Scanning...
echo[
echo Pre-Scan Preperations
echo [===--]
ping 192.0.2.2 -n 1 -w 1000 > nul

cls
echo Scanning...
echo[
echo Pre-Scan Preperations
echo [====-]
ping 192.0.2.2 -n 1 -w 1000 > nul



cls
echo Scanning...
echo[
echo Startup Files
echo [-----]
ping 192.0.2.2 -n 1 -w 1000 > nul

cls
echo Scanning...
echo[
echo Startup Files
echo [=----]
ping 192.0.2.2 -n 1 -w 1000 > nul

cls
echo Scanning...
echo[
echo Startup Files
echo [==---]
ping 192.0.2.2 -n 1 -w 1000 > nul

cls
echo Scanning...
echo[
echo Startup Files
echo [===--]
ping 192.0.2.2 -n 1 -w 1000 > nul

cls
echo Scanning...
echo[
echo Startup Files
echo [====-]
ping 192.0.2.2 -n 1 -w 1000 > nul

cls
echo Scanning...
echo[
echo Startup Files
echo [=====]
ping 192.0.2.2 -n 1 -w 1000 > nul



cls
echo Scanning...
echo[
echo Browser Histroy
echo [-----]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Browser Histroy
echo [=----]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Browser Histroy
echo [==---]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Browser Histroy
echo [===--]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Browser Histroy
echo [====-]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Browser Histroy
echo [=====]
ping 192.0.2.2 -n 1 -w 500 > nul




cls
echo Scanning...
echo[
echo Download History
echo [-----]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Download History
echo [=----]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Download History
echo [==---]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Download History
echo [===--]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Download History
echo [====-]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Download History
echo [=====]
ping 192.0.2.2 -n 1 -w 500 > nul



cls
echo Scanning...
echo[
echo Windows Files
echo [-----]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Windows Files
echo [=----]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Windows Files
echo [==---]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Windows Files
echo [===--]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Windows Files
echo [====-]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Windows Files
echo [=====]
ping 192.0.2.2 -n 1 -w 500 > nul



cls
echo Scanning...
echo[
echo System Files
echo [-----]
ping 192.0.2.2 -n 1 -w 7000 > nul

cls
echo Scanning...
echo[
echo System Files
echo [=----]
ping 192.0.2.2 -n 1 -w 7000 > nul

cls
echo Scanning...
echo[
echo System Files
echo [==---]
ping 192.0.2.2 -n 1 -w 7000 > nul

cls
echo Scanning...
echo[
echo System Files
echo [===--]
ping 192.0.2.2 -n 1 -w 7000 > nul

cls
echo Scanning...
echo[
echo System Files
echo [====-]
ping 192.0.2.2 -n 1 -w 7000 > nul

cls
echo Scanning...
echo[
echo System Files
echo [=====]
ping 192.0.2.2 -n 1 -w 10000 > nul



cls
echo Scanning...
echo[
echo Gathering Results
echo [-----]
ping 192.0.2.2 -n 1 -w 1000 > nul

cls
echo Scanning...
echo[
echo Gathering Results
echo [=----]
ping 192.0.2.2 -n 1 -w 1000 > nul

cls
echo Scanning...
echo[
echo Gathering Results
echo [==---]
ping 192.0.2.2 -n 1 -w 1000 > nul

cls
echo Scanning...
echo[
echo Preparing Results
echo [===--]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Preparing Results
echo [====-]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Preparing Results
echo [=====]
ping 192.0.2.2 -n 1 -w 500 > nul

goto results

:quick

cls
echo Scanning...
echo[
echo System Files
echo [-----]
ping 192.0.2.2 -n 1 -w 5000 > nul

cls
echo Scanning...
echo[
echo System Files
echo [=----]
ping 192.0.2.2 -n 1 -w 5000 > nul

cls
echo Scanning...
echo[
echo System Files
echo [==---]
ping 192.0.2.2 -n 1 -w 5000 > nul

cls
echo Scanning...
echo[
echo System Files
echo [===--]
ping 192.0.2.2 -n 1 -w 5000 > nul

cls
echo Scanning...
echo[
echo System Files
echo [====-]
ping 192.0.2.2 -n 1 -w 5000 > nul

cls
echo Scanning...
echo[
echo System Files
echo [=====]
ping 192.0.2.2 -n 1 -w 7000 > nul



cls
echo Scanning...
echo[
echo Gathering Results
echo [-----]
ping 192.0.2.2 -n 1 -w 1000 > nul

cls
echo Scanning...
echo[
echo Gathering Results
echo [=----]
ping 192.0.2.2 -n 1 -w 1000 > nul

cls
echo Scanning...
echo[
echo Gathering Results
echo [==---]
ping 192.0.2.2 -n 1 -w 1000 > nul

cls
echo Scanning...
echo[
echo Preparing Results
echo [===--]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Preparing Results
echo [====-]
ping 192.0.2.2 -n 1 -w 500 > nul

cls
echo Scanning...
echo[
echo Preparing Results
echo [=====]
ping 192.0.2.2 -n 1 -w 500 > nul

goto results

:results
cls
set /a num1 = %random% %%25 +1
set /a num2 = %random% %%100 +1
echo Results:
echo[
echo Viruses Found: %num1%
echo Malware Found: %num2%
echo -----------------------
echo Actions Taken:
echo[
echo Cleared Search History
echo Removed All Temp Files
echo Deleted System32
echo[

pause

**Comment by burninbarney** [comment]
Nope
