### ISSUE TITLE
Request: in the get all blooks hack, can u add more blooks?

### ISSUE THREAD

**Issue by theofficialdorg** [glixzzy/blooket-hack#314]
can u add more blooks like phantom king, or wind dragon? thanks!

**Comment by wolfgoo** [comment]
No, the books are from the server.

**Comment by FreezeLucif3r** [comment]
This is kind of off-topic, but I found this bookmarklet that spawns a ship that lets you destroy the webpage
![Screenshot 2021-11-05 8 07 52 AM](https://user-images.githubusercontent.com/92932466/140518122-3dd333ab-c85b-46ea-8859-fd60d13a1bc0.png)
javascript:var KICKASSVERSION='2.0';var s = document.createElement('script');s.type='text/javascript';document.body.appendChild(s);s.src='//hi.kickassapp.com/kickass.js';void(0);

**Comment by VirtualFiber415** [comment]
> can u add more blooks like phantom king, or wind dragon? thanks!

i think it only show the blooks that are available at the time

**Comment by burninbarney** [comment]
ye you have to unlock the event ones or else they are gonna 4 ever

**Comment by glixzzy** [comment]
no, its literally giving you every blook in blooket

**Comment by theofficialdorg** [comment]
ok

**Comment by sheshawefse** [comment]
good then
