### ISSUE TITLE
Keeps on saying I have issue when I do anything

### ISSUE THREAD

**Issue by coolman3289** [glixzzy/blooket-hack#315]
I can do anything.

**Comment by Piplup7575** [comment]
?
Please elaborate, this makes no sence.

**Comment by coolman3289** [comment]
Okay, I got it to work, and I send the script but nothing happens

**Comment by coolman3289** [comment]
It says that I sent it.

**Comment by coolman3289** [comment]
And that’s using the gui, when I make a bookmark let, it does nothing

**Comment by burninbarney** [comment]
wat

**Comment by coolman3289** [comment]
What did you close it. The bookmark let does not work.

**Comment by wolfgoo** [comment]
what bookmark????

**Comment by coolman3289** [comment]
I said bookmarklet. That’s how run code.
