### ISSUE TITLE
Writing's not that easy, but Grammarly can help. This sentence is grammatically correct, but it's wordy and hard to read. It undermines the writer's message and the word choice is bland. Grammarly's cutting-edge technology helps you craft compelling, understandable writing that is clear and understandable

### ISSUE THREAD

**Issue by burninbarney** [glixzzy/blooket-hack#316]
Writing's not that easy, but Grammarly can help. This sentence is
grammatically correct, but it's wordy and hard to read. It undermines the
writer's message and the word choice is bland. Grammarly's cutting-edge
technology helps you craft compelling, understandable writing that is clear
and understandable

**Comment by theofficialdorg** [comment]
boi

**Comment by ilikecatss** [comment]
Just stop opening unnecessary issues

**Comment by Minty4614** [comment]
bro. tf.
