### ISSUE TITLE
The issues part of this page is a big issue

### ISSUE THREAD

**Issue by burninbarney** [glixzzy/blooket-hack#317]
There are random people sh1tposting on this page (me and other people) making this page look bad. Some people dont know how to use stuff some people make g@y requests. Some people cant spell exp right. So I reccomend grammarly 

Writing's not that easy, but Grammarly can help. This sentence is
grammatically correct, but it's wordy and hard to read. It undermines the
writer's message and the word choice is bland. Grammarly's cutting-edge
technology helps you craft compelling, understandable writing that is clear
and understandable

But srsly there needs to be some sort of change to the isssues part of this github page bc its making it look bad.

**Comment by Nobody-720** [comment]
agree

**Comment by glixzzy** [comment]
this proves how immature you are too. This makes you no different than the others.
