### ISSUE TITLE
SPam does not work

### ISSUE THREAD

**Issue by GREGoryOMG** [glixzzy/blooket-hack#318]
when i always do it does not work

**Comment by glixzzy** [comment]
can you be more specific? what cheat doesn't work?

**Comment by burninbarney** [comment]
I think he means spam open box. 
To use the cheat you have to enter the boxs name eg. Enter aquatic to open aquatic box. On the next notification type in how many aquatic boxs you want to open. Btw it works on every box, it took me a while to figure it out. Does the answer your question?

**Comment by KEN6110** [comment]
UHm..GET ALL BLOOKS IN GAME NOT WORK I TRY MANY TIME,  I DONT KNOW WHAT I WRONG CAN U MAKE A VEDIO OR ANSWER FOR ME PLSS. IM A NEWBIE :((((((

**Comment by KEN6110** [comment]
i wil wait =(

**Comment by glixzzy** [comment]
> I think he means spam open box. To use the cheat you have to enter the boxs name eg. Enter aquatic to open aquatic box. On the next notification type in how many aquatic boxs you want to open. Btw it works on every box, it took me a while to figure it out. Does the answer your question?

correct, but its case sensitive so you have to put `Aquatic`

**Comment by glixzzy** [comment]
> UHm..GET ALL BLOOKS IN GAME NOT WORK I TRY MANY TIME, I DONT KNOW WHAT I WRONG CAN U MAKE A VEDIO OR ANSWER FOR ME PLSS. IM A NEWBIE :((((((

someone made a video tutorial: https://www.youtube.com/watch?v=-Q68Ol39LHM

**Comment by wolfgoo** [comment]
it not spam open box......
