### ISSUE TITLE
This is more of a suggestion but...

### ISSUE THREAD

**Issue by VerifiedPerson** [glixzzy/blooket-hack#326]
Maybe add a way to change the drop rates of blooks this way you would get infinite coins by selling the blooks, AND permanent blooks. Sorry for bothering you!

**Comment by glixzzy** [comment]
to get more tokens after you added 500 tokens in a day just sell all your duped blooks 

script:
```js
fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/global/sellDupeBlooks.js").then((res) => res.text().then((t) => eval(t)))
```
