### ISSUE TITLE
Game Flooding does not work

### ISSUE THREAD

**Issue by Minty4614** [glixzzy/blooket-hack#328]
i have tried multiple times.

**Comment by wolfgoo** [comment]
?

**Comment by wolfgoo** [comment]
you can use school cheats

**Comment by wolfgoo** [comment]
https://github.com/glixzzy/blooket-hack

**Comment by Greenlio** [comment]
Will investigate in a few minutes. It (should) work.

**Comment by Greenlio** [comment]
Odd, doesn't work for me. However, I'm using the repository version instead of SchoolCheats. Will try further when I get home.

Bookmarklet used:
`fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/global/floodGames.js").then((res) => res.text().then((t) => eval(t)))
`

**Comment by willutgilugpiulg** [comment]
ya

**Comment by willutgilugpiulg** [comment]
ALso the get all blooks for me wont work it says "you have to be on blook selecting page" but i AM ON THAT PAGE
i just does not work

**Comment by Greenlio** [comment]
Hey.. you have to be in the game. Where it says 'Waiting for host' or something related. Not in the 'Blooks' screen of the dashboard.
Sorry for the confusion.

**Comment by Greenlio** [comment]
> ALso the get all blooks for me wont work it says "you have to be on blook selecting page" but i AM ON THAT PAGE i just does not work

Please refer to #333.

**Comment by glixzzy** [comment]
> Will investigate in a few minutes. It (should) work.

why are you acting like you developed every cheat in this repository?

**Comment by glixzzy** [comment]
> i have tried multiple times.
it works perfectly fine??

https://user-images.githubusercontent.com/73669084/140996832-9636af02-cb02-4d62-8166-6327c12fe7ca.mp4

**Comment by Greenlio** [comment]
> > Will investigate in a few minutes. It (should) work.
> 
> why are you acting like you developed every cheat in this repository?

great question.
idk, I'll stop

**Comment by glixzzy** [comment]
> > > Will investigate in a few minutes. It (should) work.
> > 
> > 
> > why are you acting like you developed every cheat in this repository?
> 
> great question. idk, I'll stop

I don't mind you helping out others but the other comment you made seemed like you were acting like you made these cheats.

**Comment by Greenlio** [comment]
yeah, apologies on how I came off. not my intent.

**Comment by Minty4614** [comment]
https://user-images.githubusercontent.com/79288321/141006239-66fb482a-232b-4fca-8bb9-65c8d7840f85.mp4

Odd. Mine won't work. Am I doing something wrong?

**Comment by glixzzy** [comment]
nope you aren't doing anything wrong, sometimes blooket is just blocking all the requests that are coming in. There is nothing I can do about that atm, sorry.
