### ISSUE TITLE
Spam open boex not working.

### ISSUE THREAD

**Issue by Random0120** [glixzzy/blooket-hack#329]
Yeah, I tried spam opening bot box and it still wouldn't take my tokens. I spelled it these way but none worked, "Bot Box", "Bot box", "bot Box" and "bot box".

**Comment by Greenlio** [comment]
Hey!

You have to put the name of the box, as the example says.
For your situation, use "Bot" as the name.

**Comment by hotboi69** [comment]
I just checked the flooding works like a charm

**Comment by Greenlio** [comment]
> I just checked the flooding works like a charm

wrong issue I think, try [#328](https://github.com/glixzzy/blooket-hack/issues/328).

**Comment by Random0120** [comment]
I am using the school cheats websites and not the console.

**Comment by Greenlio** [comment]
Interesting, I haven't used the SchoolCheats version lately. I'll check in an hour or so. It should be the same though.

**Comment by Greenlio** [comment]
Well, as SchoolCheats simply isn't working for me, I used this repositories version.
Works for me. Remember: Use 'Bot' instead of 'Bot Box' or similar.

Here's the exact code.
`fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/global/spamOpenBoxes.js").then((res) => res.text().then((t) => eval(t)))
`

**Comment by Random0120** [comment]
Do I put that in the console?

**Comment by Greenlio** [comment]
Yes.

**Comment by Greenlio** [comment]
If you don't have access to console, put in your searchbar "javascript:" then paste that. Press enter.

**Comment by Random0120** [comment]
Do I just paste the code or should I do javascript: before it?

**Comment by Greenlio** [comment]
If you're putting it in your URL bar, put the javascript: . If you are putting it in console, do **not** put the javascript: .

**Comment by glixzzy** [comment]
school cheats is a very old and outdated version. I'll update everything on schoolcheats soon,
