### ISSUE TITLE
Lots of bugs But is a great hack

### ISSUE THREAD

**Issue by hotboi69** [glixzzy/blooket-hack#330]
On tower defence, all free doesn't work set price doesn't work all answers correctly doesn't work flood game doesn't work and change round is buggy on tower defence. But I know it is hard and takes a lot of time to do stuff like this. I admire your effort and hope you can fix these bugs. Thx

**Comment by hotboi69** [comment]
@Greenlio I got bugs Hope you can get to fixing them soon. Thx

**Comment by Greenlio** [comment]
Hey - I can't modify those due to obfuscation, so you'd have to ask @glixzzy.

**Comment by hotboi69** [comment]
@glixzzy

**Comment by glixzzy** [comment]
fixed.
