### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by Jimbo889** [glixzzy/blooket-hack#332]
So when I try to add money to my tower defense game it says error and I don’t know what to do

**Comment by Greenlio** [comment]
It works for me.
However, it seems like it's adding a 0 every time you answer.

Here's the exact code I used, as said in the 'tower-defense' folder of this repository.

`fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/tower-defense/getCash.js").then((res) => res.text().then((t) => eval(t)))
`

**Comment by Jimbo889** [comment]
So I’m on a school iPad and I’m not sure if that makes any difference but if it does can you please let me know

**Comment by Jimbo889** [comment]
> It works for me. However, it seems like it's adding a 0 every time you answer.
> 
> Here's the exact code I used, as said in the 'tower-defense' folder of this repository.
> 
> `fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/tower-defense/getCash.js").then((res) => res.text().then((t) => eval(t)))`

So I’m on a school iPad and I’m not sure if that makes any difference but if it does can you please let me know

**Comment by Greenlio** [comment]
I have not tried iPad.
However, it should follow the same format.

Type in your URL bar
`javascript:`
then paste 
`fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/tower-defense/getCash.js").then((res) => res.text().then((t) => eval(t)))`

Hope this helps!

**Comment by Jimbo889** [comment]
> I have not tried iPad. However, it should follow the same format.
> 
> Type in your URL bar `javascript:` then paste `fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/tower-defense/getCash.js").then((res) => res.text().then((t) => eval(t)))`
> 
> Hope this helps!

![F74ABCE3-DEDF-48C0-95D8-44455B4BB9A8](https://user-images.githubusercontent.com/94004530/140981388-42d56238-f1d0-4e38-9415-3617e1d2c80b.jpeg)


That’s what it says

**Comment by Greenlio** [comment]
@glixzzy

**Comment by glixzzy** [comment]
I don't provide mobile/ipad support sorry. Computer/Laptop is recommended
