### ISSUE TITLE
nevermind i think my computer sucks

### ISSUE THREAD

**Issue by willutgilugpiulg** [glixzzy/blooket-hack#334]

**Comment by Greenlio** [comment]
Very descriptive, thanks.
Furthermore, have you made sure you are already in a game and on the 'Waiting for Host' screen?

**Comment by Greenlio** [comment]
Please refer to #333.

**Comment by willutgilugpiulg** [comment]
lol

**Comment by willutgilugpiulg** [comment]
yes

**Comment by willutgilugpiulg** [comment]
maybe it just is broken for me

**Comment by willutgilugpiulg** [comment]
Its fine.

**Comment by Greenlio** [comment]
Hey, if I may suggest, if you have no other questions or issues, closing the issue.

**Comment by glixzzy** [comment]
you have to be on /play/lobby page while being in a live game

**Comment by willutgilugpiulg** [comment]
???

**Comment by willutgilugpiulg** [comment]
ohhhhhhhhhhhhh

**Comment by willutgilugpiulg** [comment]
well it still does not work because my computer is trash

**Comment by willutgilugpiulg** [comment]
well anyways is it possible to give ideas ike for new cheats
