### ISSUE TITLE
hacks for blooket 

### ISSUE THREAD

**Issue by hacksforblooket** [glixzzy/blooket-hack#335]
these hacks for blooket are not working so pretty plz get that fixed pretty plz and thx

**Comment by Greenlio** [comment]
What? Please be more descriptive.

**Comment by hotboi69** [comment]
I want to know if you could check if all answers correct are working because it is not working for me.

**Comment by Greenlio** [comment]
Works for me.
Type `fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/global/getEveryAnswerCorrect.js").then((res) => res.text().then((t) => eval(t)))` in console or:

Type `javascript:` and then paste the above code block in your URL bar.

I'd also like to let you know that the Every Answer Correct only works on some modes. Example: I know that Tower Defense doesn't work, but Factory does.
Hope this helped!

**Comment by glixzzy** [comment]
most of the cheats in this repository work. Some of them are a bit buggy and some of them are broken. I'll get them fixed soon once I have time, sorry.

**Comment by sheshawefse** [comment]
can you add more hacks? to any game mode please??
