### ISSUE TITLE
Tower of Doom

### ISSUE THREAD

**Issue by ActualKazooKid** [glixzzy/blooket-hack#340]
Tower of Doom add coins hack doesn't work, it says "you can't use this cheat on this page" even though I've tried it in the shop and also on the map.

**Comment by burninbarney** [comment]
I agree.

**Comment by sheshawefse** [comment]
no it just when you are fighting the bot you have to do it there and it work

**Comment by i-do-not-wish-to-be-alive** [comment]
this cheat only works during the cardselect page, and will work up to 500 of them.
