### ISSUE TITLE
tokens

### ISSUE THREAD

**Issue by issue-reproter** [glixzzy/blooket-hack#341]
i know you cant get more than 500 hundred a day, but do you think you could speed up the timer not and not get more than 500 tokens, to the computer at least

**Comment by Nobody-720** [comment]
No Yu cant ;=; I Think

**Comment by Mugz114** [comment]
Nah the timer is "Server Side" Meaning you would need to hack into the server to change the timer witch would be very hard if not imposible

**Comment by spider0412** [comment]
it would be easy if u had an acttular admin

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
It is server-side please stop making issues about this they will all eventually be closed

**Comment by Greenlio** [comment]
> It is server-side please stop making issues about this they will all eventually be closed

minimod

**Comment by glixzzy** [comment]
> > It is server-side please stop making issues about this they will all eventually be closed
> 
> minimod

Thats not mini-modding. I don't mind people telling others that some stuff isn't possible
