### ISSUE TITLE
all of the hacks

### ISSUE THREAD

**Issue by ZZMANMAN2** [glixzzy/blooket-hack#343]
so if I use a hack it only lets me do it once and if I want to do it again I would have to refresh

**Comment by TJ999YT** [comment]
Yes, idk but for some reason that happens.

**Comment by i-do-not-wish-to-be-alive** [comment]
some hacks are automated, such as stockinfFood.js

**Comment by TJ999YT** [comment]
Maybe if you try to put a ; at the beginning or end of the script it might work... I'm not sure

**Comment by TJ999YT** [comment]
But make sure it's separate script

**Comment by glixzzy** [comment]
you dont have to refresh. What cheat are you using?

**Comment by Ongyj888** [comment]
I also have this issue:
it just throws this error in console
![image](https://user-images.githubusercontent.com/67620716/141305990-70e452af-b1ce-4b45-a44d-71fcd932d44a.png)

**Comment by Ongyj888** [comment]
but in other day it just worked

**Comment by Ongyj888** [comment]
update: spamopenbox.js also doesn't work
![image](https://user-images.githubusercontent.com/67620716/141306764-ee509a70-dfb0-42bc-ad48-cfed2a6cf678.png)

**Comment by ZZMANMAN2** [comment]
every one of them but using the bookmarklet

**Comment by ZZMANMAN2** [comment]
also it shows glixzzys twitter
