### ISSUE TITLE
Flooding does not work.

### ISSUE THREAD

**Issue by Random0120** [glixzzy/blooket-hack#344]
I have tried multiple times on different games. Nothing worked.

**Comment by TJ999YT** [comment]
Same bro

**Comment by i-do-not-wish-to-be-alive** [comment]
this problem has been here for a week or so, just wait for them to fix it

**Comment by TJ999YT** [comment]
To me, it's been an issue since I first started to try flooding

**Comment by glixzzy** [comment]
how does it work when I try it?? 
![image](https://user-images.githubusercontent.com/73669084/141228699-24336639-b2bc-4abc-93d2-cc6d6c86ee54.png)

**Comment by wesley61** [comment]
Umm, I tried it in crypto and didn't work. Maybe just blooket slow :\

**Comment by wesley61** [comment]
maybe patched, cause the request got blocked.

**Comment by wesley61** [comment]
<img width="396" alt="Screenshot 2021-11-11 at 8 54 48 PM" src="https://user-images.githubusercontent.com/71319668/141301535-6ae7a2a0-7bcf-4bda-badf-52b668fdebac.png">

**Comment by glixzzy** [comment]
> maybe patched, cause the request got blocked.

ahhhhhh thanks for this error, I didn't notice this error cause I had a CORS proxy running locally on my PC. I have fixed this issue.
