### ISSUE TITLE
Add existing feature request

### ISSUE THREAD

**Issue by TJ999YT** [glixzzy/blooket-hack#345]
You should add the auto-answer script from gbasil.dev and it works for EVERY GAME MODE!!!

**Comment by TJ999YT** [comment]
But make sure to obfuscate just so it's not so easy to leak the source code as it is now lol

**Comment by TJ999YT** [comment]
Oh, and I think it is possible to make an anti-kick feature because they added a feature where the host can kick people from the game in the newest update and it's annoying but that's only possible if it isn't fully server side.

**Comment by TJ999YT** [comment]
Anti-kick means to not be able to get kicked from the game so the host can't kick you.

**Comment by i-do-not-wish-to-be-alive** [comment]
anti-kick is a good idea, but it requires it on the host's side, if possible. if they can find a loophole, yes.

**Comment by i-do-not-wish-to-be-alive** [comment]
auto-answer is good, but it's easily detectable and the game can crash. it happens mainly on chromebooks (school ones)

**Comment by TJ999YT** [comment]
The auto answer that's from gbasil.dev isnt laggy at all, you just press q and it auto-answers and even around the end of the game it's still not laggy and it's not detectible because they would have to patch it.

**Comment by TJ999YT** [comment]
![16365949772643418960492481467815](https://user-images.githubusercontent.com/94023636/141221984-80f0a814-6ba5-48f5-b4f6-4dcc3683b17f.jpg)
