### ISSUE TITLE
Here's some proof that flood still doesn't work (yes, i used the new script and the bots are still not joining)...

### ISSUE THREAD

**Issue by TJ999YT** [glixzzy/blooket-hack#350]
![image](https://user-images.githubusercontent.com/94023636/141379328-96312346-1df1-4fb0-b1dd-fa5fb5213036.png)

**Comment by wesley61** [comment]
It works for me

**Comment by glixzzy** [comment]
show me the error

**Comment by Nobody-720** [comment]
holy

show the script in console :)

**Comment by BlooketHeck** [comment]
it works for me

**Comment by issue-reproter** [comment]
i get the same thing, it does not show an error

**Comment by wolfgoo** [comment]
It works for me but the bots are all the same blooks.

**Comment by TJ999YT** [comment]
There is no error...

**Comment by TJ999YT** [comment]
> show me the error

There is no error that pops up it just says undefined in console but nothing if I use it as a bookmark...

**Comment by wolfgoo** [comment]
use school cheats.

**Comment by TJ999YT** [comment]
I tried to use the launcher/schoolcheats and it still doesn't work...
