### ISSUE TITLE
Tower of Doom lowerAllEnemyStats.js only works for one round

### ISSUE THREAD

**Issue by BlooketHeck** [glixzzy/blooket-hack#355]
![Screenshot 2021-11-12 6 28 19 AM](https://user-images.githubusercontent.com/94115787/141460068-9856ddb6-9bf7-4fed-8613-ebeabfb61828.png)
![Screenshot 2021-11-12 6 27 47 AM](https://user-images.githubusercontent.com/94115787/141460094-96a38010-f0ad-496a-9a34-0e87266b5b8b.png)
is this intentional?

**Comment by wesley61** [comment]
It should work for 1 game...

**Comment by Piplup7575** [comment]
Yes
You have to rerun the code every round
