### ISSUE TITLE
Tower Defense

### ISSUE THREAD

**Issue by Coolkid1624** [glixzzy/blooket-hack#356]
I cannot get the cash I used the script for

**Comment by BlooketHeck** [comment]
it works 50/50 for me

**Comment by ilikecatss** [comment]
try refreshing the page, then paste the script

**Comment by ilikecatss** [comment]
this happens sometimes

**Comment by wolfgoo** [comment]
Use school cheats.

**Comment by Greenlio** [comment]
> Use school cheats.

glixzzy has said many times schoolcheats is outdated.. why suggest?

**Comment by Greenlio** [comment]
here's the funny proof [on issue #329](https://github.com/glixzzy/blooket-hack/issues/329#issuecomment-964496061)

**Comment by glixzzy** [comment]
schoolcheats is updated now.
