### ISSUE TITLE
Chromebook

### ISSUE THREAD

**Issue by CheetoKirby** [glixzzy/blooket-hack#357]
It will not work on chrome book if you use the common hack javascript:
If there is any other way except instead of inspecting it, let me know!
Thx

**Comment by glixzzy** [comment]
`javascript:` should work

**Comment by CheetoKirby** [comment]
when should I do it. When im in the game or before they start the game or during questions?

**Comment by CheetoKirby** [comment]
and its for the get cash

**Comment by FreezeLucif3r** [comment]
I went on my Chromebook to test it out and it it works so idk.

**Comment by CheetoKirby** [comment]
when did you do it during the game?

**Comment by CheetoKirby** [comment]
or like before the game

**Comment by CheetoKirby** [comment]
nevermind I got it fixed I was on tower of doom. Sorry!
