### ISSUE TITLE
Suggestion | idea for sellDupeBlooks.js

### ISSUE THREAD

**Issue by Greenlio** [glixzzy/blooket-hack#359]
Wouldn't it be theoretically possible to use the same system used in spamOpenBoxes.js that prints the amount of a blook you obtained? Couldn't we just do that but for spamOpenBoxes and use an alert? The only reason we don't do alerts now is because it would blow up your browser and computer into pieces if we did, but this could be a possibility?

all a hypothetical and it's like 11:00 pm and I don't know.

**Comment by glixzzy** [comment]
added !
