### ISSUE TITLE
Not getting tokens.

### ISSUE THREAD

**Issue by ADictionary** [glixzzy/blooket-hack#362]
I used the get tokens hack, and it didn't work. My daily limit had just refreshed, so I should have gotten the coins, but I didn't. Any tips for this to work?

**Comment by BlooketHeck** [comment]
No tips from me it works always

**Comment by glixzzy** [comment]
it works perfectly fine

**Comment by ADictionary** [comment]
> it works perfectly fine

now it says "VM83:2 GET https://api.blooket.com/api/users/verify-token?token=JWT+eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTgxN2UxY2UzNzQyNDE4NGNhN2VjODYiLCJuYW1lIjoiQV9EaWN0aW9uYXJ5IiwiZW1haWwiOiJub2FoaDI4QHdpbGR3b29kLm9yZyIsImdhbWVzUGxheWVkIjo2OCwiaGFzUGFzc3dvcmQiOmZhbHNlLCJwbGFuIjoiU3RhcnRlciIsInJvbGUiOiJTdHVkZW50Iiwic3RyaXBlIjoiY3VzX0tXVU0zR0lseDViellLIiwiZGF0ZUNyZWF0ZWQiOiIyMDIxLTExLTAyVDE4OjA2OjIwLjY2NVoiLCJleHAiOjE2MzcyNDg2NzZ9.t4jXH_DmeqX1NWdiJa5WoJPB68Dm_EUZFjJEYzEPMT0 net::ERR_INTERNET_DISCONNECTED
getName @ VM83:2
addCurrencies @ VM83:26
(anonymous) @ VM83:38
VM83:2  Uncaught (in promise) TypeError: Failed to fetch
    at getName (<anonymous>:2:28)
    at addCurrencies (<anonymous>:26:25)
    at <anonymous>:38:1
getName @ VM83:2
addCurrencies @ VM83:26
(anonymous) @ VM83:38
async function (async)
addCurrencies @ VM83:26
(anonymous) @ VM83:38"

**Comment by BlooketHeck** [comment]
@glixzzy close this one too

**Comment by glixzzy** [comment]
> > it works perfectly fine
> 
> now it says "VM83:2 GET https://api.blooket.com/api/users/verify-token?token= net::ERR_INTERNET_DISCONNECTED getName @ VM83:2 addCurrencies @ VM83:26 (anonymous) @ VM83:38 VM83:2 Uncaught (in promise) TypeError: Failed to fetch at getName (:2:28) at addCurrencies (:26:25) at :38:1 getName @ VM83:2 addCurrencies @ VM83:26 (anonymous) @ VM83:38 async function (async) addCurrencies @ VM83:26 (anonymous) @ VM83:38"

please don't leak your token, it gives people access to your account. And it still works fine
