### ISSUE TITLE
didnt get tokens

### ISSUE THREAD

**Issue by herbsxx** [glixzzy/blooket-hack#363]
when i entered the code it said this VM389:1 Uncaught ReferenceError: io is not defined
    at eval (eval at <anonymous> (615cd1edf98862008cc55362:3), <anonymous>:1:39657)

**Comment by ilikecatss** [comment]
hmmm?
working fine for me

**Comment by herbsxx** [comment]
it worked for the past few days but today it dosent work

**Comment by herbsxx** [comment]
nevermind it worked but i had to use this code fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/global/addTokens.js").then((res) => res.text().then((t) => eval(t)))

**Comment by herbsxx** [comment]
nvm it worked thx

**Comment by BlooketHeck** [comment]
@glixzzy close this
