### ISSUE TITLE
NOT AN ISSUE | How do you use school cheats

### ISSUE THREAD

**Issue by BlooketHeck** [glixzzy/blooket-hack#364]
Please tell me how to use it

**Comment by herbsxx** [comment]
i dont think it works anymore

**Comment by BlooketHeck** [comment]
how did u even get to it?

**Comment by herbsxx** [comment]
i saw the link in the video so i typed it in it didnt work

**Comment by BlooketHeck** [comment]
go to discussions bc this ain't an issue
