### ISSUE TITLE
pls add only 1 of the twiiter at the top left in everyanswer correct .It's very very laggy

### ISSUE THREAD

**Issue by yee-negative** [glixzzy/blooket-hack#369]

**Comment by Nobody-720** [comment]
what do yu mean ;=;

**Comment by Nobody-720** [comment]
oh ok

**Comment by wolfgoo** [comment]
?

**Comment by Greenlio** [comment]
what

**Comment by Greenlio** [comment]
oh I see yeah that's interesting
probably a misplaced line causing the watermark to appear many times so uhh @glixzzy

**Comment by wolfgoo** [comment]
Oh, Why don't ask glixzzy to cancel twiiter.

**Comment by Greenlio** [comment]
> Oh, Why don't ask glixzzy to cancel twitter.

What is your horrible logic here?
OP was just rightfully complaining that the watermark was sending itself hundreds of times that was causing lag for them, and whoever else is using it.

Your horrible sarcasm is weird, cringe, and horrendous.

**Comment by wolfgoo** [comment]
???

**Comment by Greenlio** [comment]
> ???

Hey, what drugs are you on? Crack? Weed? Heroin? Can I please have some?
Thanks.

**Comment by glixzzy** [comment]
yeah ok, fixed

**Comment by wolfgoo** [comment]
.......
