### ISSUE TITLE
Now i get an error

### ISSUE THREAD

**Issue by ADictionary** [glixzzy/blooket-hack#370]
<img width="519" alt="Screen Shot 2021-11-14 at 9 20 04 PM" src="https://user-images.githubusercontent.com/94313249/141726760-4c649e28-7b00-41f0-9187-0714209cf29b.png">

**Comment by wolfgoo** [comment]
Use school cheats.
fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/main.js")
.then((res) => res.text()
.then((t) => eval(t)))

**Comment by herbsxx** [comment]
try this 
fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/global/addTokens.js").then((res) => res.text().then((t) => eval(t)))

**Comment by ADictionary** [comment]
> try this fetch("[https://raw.githubusercontent.com/glixzzy/blooket-hack/main/global/addTokens.js").then((res)](https://raw.githubusercontent.com/glixzzy/blooket-hack/main/global/addTokens.js%22).then((res)) => res.text().then((t) => eval(t)))

that doesn't work either for some reason

**Comment by NihatSuleyman** [comment]
Is the code erroring?

**Comment by Greenlio** [comment]
> Use school cheats.
> 
> fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/main.js")
> 
> .then((res) => res.text()
> 
> .then((t) => eval(t)))
> 
> 
> 
> 

part 2 of me asking why you say use schoolcheats when it's outdated

**Comment by glixzzy** [comment]
> > Use school cheats.
> > fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/main.js")
> > .then((res) => res.text()
> > .then((t) => eval(t)))
> 
> part 2 of me asking why you say use schoolcheats when it's outdated

schoolcheats isnt outdated anymore, ive updated it

**Comment by glixzzy** [comment]
i have no idea whats wrong cause it works fine for everybody

**Comment by herbsxx** [comment]
> > try this fetch("[https://raw.githubusercontent.com/glixzzy/blooket-hack/main/global/addTokens.js").then((res)](https://raw.githubusercontent.com/glixzzy/blooket-hack/main/global/addTokens.js%22).then((res)) => res.text().then((t) => eval(t)))
> 
> that doesn't work either for some reason

idk at first it didnt work then i used that and it worked for me

**Comment by glixzzy** [comment]
https://user-images.githubusercontent.com/73669084/141875394-7e4c4b21-d716-400c-81fd-538eb67a39b0.mp4
