### ISSUE TITLE
I want To Ask Can Yu Make A Hack That Can "Hatch Boxes Without Using Your Tokens"   Yu Also Still get The Blooks That Yu Hacted

### ISSUE THREAD

**Issue by Nobody-720** [glixzzy/blooket-hack#371]

**Comment by wolfgoo** [comment]
I think it can't.

**Comment by Nobody-720** [comment]
see what glizxxy can do

**Comment by wolfgoo** [comment]
I don't know.

**Comment by wolfgoo** [comment]
glixzzy might turn off this issue.

**Comment by Nobody-720** [comment]
**Same I got The Feeling About That**

**Comment by Liam-12** [comment]
just create it with GitHub

**Comment by wolfgoo** [comment]
Now we are using this.(Github)

**Comment by Liam-12** [comment]
Why don't create it then?

**Comment by wolfgoo** [comment]
Nobody-720 you need to Change the issue  theme I want To Ask Can Yu Make A Hack That Can "Hatch Boxes Without Using Your Tokens" Yu Also Still get The Blooks That Yu Hacted  to I want to ask can You make a hack that can open boxes without using your tokens you also still get the blooks you open.

**Comment by wolfgoo** [comment]
> Why don't create it then?

I don't know.

**Comment by Nobody-720** [comment]
Idk how to create it ;=;

**Comment by Nobody-720** [comment]
Im not so clever

**Comment by Nobody-720** [comment]
Yu need to learn it like a subject

**Comment by Nobody-720** [comment]
It is not easy as its sound ;=;

**Comment by Nobody-720** [comment]
maybe it is server-side idk ;=;

**Comment by xXvince666Xx** [comment]
you can just use spamopen boxes becaus it dosent use tokens (¬_¬")

**Comment by xXvince666Xx** [comment]
but you dont know whant you will get

**Comment by Liam-12** [comment]
Give me Glixzzy's Discord and I will ask him/her

**Comment by wolfgoo** [comment]
No, spam open boxes need tokens.

**Comment by wolfgoo** [comment]
> Give me Glixzzy's Discord and I will ask him/her
https://discord.gg/K5xUbuDqmG

**Comment by therealwinner** [comment]
this function wouldnt work.

**Comment by wolfgoo** [comment]
Why?

**Comment by FreezeLucif3r** [comment]
Speak english.

**Comment by Greenlio** [comment]
interesting thought, but could be combined with the daily 500 glitch and the spam open blooks script to make something like that, idk

**Comment by wolfgoo** [comment]
Yes, glixzzy closed it.
