### ISSUE TITLE
Please make it so that we can get unlimited tokens! I know that you guys can find a way to sneak past blooket on this before it gets patched! please do this because only 500 per day is a lot but I want more!

### ISSUE THREAD

**Issue by therealwinner** [glixzzy/blooket-hack#372]

**Comment by wolfgoo** [comment]
I think glixzzy see it will turn off this issue.

**Comment by FreezeLucif3r** [comment]
For the last time, it's server-side. Please look at previously closed issues before opening a new one, because it's getting kinda annoying ngl.

**Comment by therealwinner** [comment]
bro

**Comment by Random0120** [comment]
@therealwinner It is very very very hard or even impossible to get more tokens than 500. You have to hack into the servers.

**Comment by Greenlio** [comment]
nah it's just impossible
