### ISSUE TITLE
Sadly This hack has been blocked by my admin

### ISSUE THREAD

**Issue by SwingWitMe** [glixzzy/blooket-hack#374]
Can you make another hack like this one?

**Comment by Greenlio** [comment]
wow a smart IT

**Comment by glixzzy** [comment]
hm are you saying schoolcheats or github has been blocked? or both?

**Comment by wesley61** [comment]
you can't change the console ability...😈

**Comment by SwingWitMe** [comment]
School cheats has been blocked within the couple days when i was using it then i tried using the ThatFruedDued hack and it worked but when i used the mod menu in games it kicked me out so idk.

**Comment by wesley61** [comment]
screenshots please,  @SwingWitMe

**Comment by SwingWitMe** [comment]
alr 
![Screenshot 2021-11-16 08 20 11](https://user-images.githubusercontent.com/94390684/141993327-8f63cdb6-abd8-437f-84a9-fdabec501527.png)

**Comment by SwingWitMe** [comment]
my admin probs looked through my history and clicked on the link and saw what it was

**Comment by wesley61** [comment]
shhhh

**Comment by wesley61** [comment]
vpn

**Comment by SwingWitMe** [comment]
jit vpns are blocked to
