### ISSUE TITLE
getAllBlooksInGame.js doesn't work.

### ISSUE THREAD

**Issue by dontpingmem8** [glixzzy/blooket-hack#375]
The hack "getAllBlooksInGame.js" doesn't currently work on Blooket. Whenever I use it, it says it sent the script. But whenever I go back to Blooket, it doesn't work. And yes, I do go to the Blook select screen when I use it.

**Comment by Greenlio** [comment]
which blooket select screen?

your url should have "/play/lobby"

**Comment by wolfgoo** [comment]
Yes
