### ISSUE TITLE
Blooket kicks you out of the game if you use the coin hack

### ISSUE THREAD

**Issue by Exetion** [glixzzy/blooket-hack#376]

**Comment by Greenlio** [comment]
uh

**Comment by glixzzy** [comment]
which game mode are you using?

**Comment by wolfgoo** [comment]
I think you hacked very very mang coins like this(999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999) so you were forced to quit the game.

I don't know the above is just a guess

**Comment by Greenlio** [comment]
> I think you hacked very very mang coins like this(999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999) so you were forced to quit the game.
> 
> I don't know the above is just a guess

not how works
it will figuratively let you set any amount, including Infinity and letters.
so

**Comment by wolfgoo** [comment]
idk
