### ISSUE TITLE
open the bots doesn't work for me 

### ISSUE THREAD

**Issue by Cam1234fn** [glixzzy/blooket-hack#379]
open the bots doesn't work for me like i type in the name and the code and how many bots and enter and then it does nothing and im mad please help me please

**Comment by ilikecatss** [comment]
wdym "open the bots"

**Comment by ilikecatss** [comment]
u mean the flood hack?

**Comment by ilikecatss** [comment]
hmm working fine for me

**Comment by ilikecatss** [comment]
how many bots did you want

**Comment by ilikecatss** [comment]
it cannot be more then 100

**Comment by Cam1234fn** [comment]
It work sometimes now that is weird

**Comment by glixzzy** [comment]
yeah, blooket did something which i cant find a way around, so it wont work for some games pins.
