### ISSUE TITLE
Very amazing! I can use all the blooks when I play a game

### ISSUE THREAD

**Issue by Nyla-Blookethecker** [glixzzy/blooket-hack#381]
Nice!
 And my stats is almost level 100 :)))🥰✨👧^0^

**Comment by herbsxx** [comment]
this is not an issue tho , why did you make issue

**Comment by Nobody-720** [comment]
yeah It Is A    **R E P O R T**

**Comment by Greenlio** [comment]
y'all mean lmao

**Comment by usernakjhzkxjcxkjz** [comment]
THIS IS NOT AN ISSUE BASTARD
