### ISSUE TITLE
Will you make a blooket battle royal energy hack????

### ISSUE THREAD

**Issue by 301Bri** [glixzzy/blooket-hack#382]
I need it because I always lose at battle royal.

**Comment by Nobody-720** [comment]
agree

**Comment by Nobody-720** [comment]
battle royal is like racing who faster selected who is going to attack first

**Comment by wolfgoo** [comment]
ya

**Comment by wesley61** [comment]
"All Questions are on host's computer" "Multi-player, so server-side" "If [Glizzy] could, [Glizzy] would do it"

**Comment by wesley61** [comment]
If hack, it's illegal

**Comment by wolfgoo** [comment]
No that

**Comment by wolfgoo** [comment]
Is get energy( Your health in battle royal)hack

**Comment by wesley61** [comment]
@glixzzy

**Comment by wesley61** [comment]
help

**Comment by 301Bri** [comment]
YESYES
Help pls
I am a cat!!

**Comment by wesley61** [comment]
... -_-

**Comment by glixzzy** [comment]
no

**Comment by ilikecatss** [comment]
simply IMPOSSIBLE

**Comment by wolfgoo** [comment]
:(
