### ISSUE TITLE
Why cant addTokens.js add 9999999999 tokens and 9999999999 XP daily?

### ISSUE THREAD

**Issue by XRB999** [glixzzy/blooket-hack#383]

**Comment by XRB999** [comment]
Why cant addTokens.js add 9999999999 tokens and 9999999999 XP daily?

**Comment by wolfgoo** [comment]
Idk

**Comment by wolfgoo** [comment]
Because the tokens and XP daily are from the server.

**Comment by wolfgoo** [comment]
So you can't change tokens and XP daily.

**Comment by FlappyTheBats** [comment]
Because Blooket has a server side limit on maximum tokens. [Read closed issues before you create a new one.](https://github.com/glixzzy/blooket-hack/issues/380)

**Comment by Nobody-720** [comment]
so if yu want to get that much tokens and xp [ **break inside the server & become a hacker** ]

**Comment by wolfgoo** [comment]
ya

**Comment by wesley61** [comment]
But that's illegal

**Comment by wolfgoo** [comment]
I know

**Comment by Quancubaprocraft2912** [comment]
the most token we can add on a day is 500 & 300 exp

**Comment by ilikecatss** [comment]
pls JUST STOP OPENING UNNECESSARY ISSUES
