### ISSUE TITLE
the get everything cafe hack isnt working for me, I cant copy it.

### ISSUE THREAD

**Issue by therealwinner** [glixzzy/blooket-hack#387]

**Comment by ButterDogWasTaken** [comment]
That's probably a PC issue, It has worked for me in the past

**Comment by glixzzy** [comment]
huh?

**Comment by FlappyTheBats** [comment]
you open console with ctrl+shift+j and then paste `
fetch("https://raw.githubusercontent.com/glixzzy/blooket-hack/main/cafe/stockInfiniteFood.js").then((res) => res.text().then((t) => eval(t)))`

**Comment by varedz** [comment]
Method patched, use new method.
