### ISSUE TITLE
all correct answer issuse

### ISSUE THREAD

**Issue by Brandon981026** [glixzzy/blooket-hack#390]
hum..........
when i use the all correct answer hack, the computer gets VERY LAG
i don't know it is only my computer or everybody get the issue but if you have the same thing around, plz fix the problem.
@glixzzy your blooket hack was great, thank you so much that i have my special memory.
hope you have a nice day

**Comment by sheshawefse** [comment]
glixzzy the all answer correct hack doesn't really work good can you try your best and fix it thx for fiing it glixzzy your hacks are good you did a great job but just need some abit fix

**Comment by Ihatr1** [comment]
I'm pretty sure it's because of the credit oval that appears when you use the hack, there's something wrong with how it shows up or something.

**Comment by Brandon981026** [comment]
thank you guys for answer me 
i hope that @glixzzy see this and answer me
have a nice day guys

**Comment by XRB999** [comment]
same

**Comment by Gamehacker69** [comment]
This is up and working he fixed the lag issues just grab the new one from global and all answers correct

**Comment by Greenlio** [comment]
https://user-images.githubusercontent.com/62725108/143144972-d84d15de-e99d-45fb-b9fc-c8b36d8d2c46.mp4

**Comment by varedz** [comment]
Method patched, use new method.
