### ISSUE TITLE
Does This Hack Works [ Also Sorry ] Pls Forgive Me

### ISSUE THREAD

**Issue by Nobody-720** [glixzzy/blooket-hack#391]
async function getName(authToken) {
    const response = await fetch('https://api.blooket.com/api/users/verify-token?token=JWT+' + authToken);
    const data = await response.json();

    return data.name
};

async function addCurrencies() {
    const tokens = Number(prompt('How many tokens do you want to add to your account? (50000000000000000 daily)'));
    const myToken = localStorage.token.split('JWT ')[1];

    if (tokens > 50000000000000000) {
        alert('You can only add up to 50000000000000000 tokens daily.')
    }

    const response = await fetch('https://api.blooket.com/api/users/add-rewards', {
        method: "PUT",
        headers: {
            "referer": "https://www.blooket.com/",
            "content-type": "application/json",
            "authorization": localStorage.token
        },
        body: JSON.stringify({
            addedTokens: tokens,
            addedXp: 30000000 ,
            name: await getName(myToken)
        })
    });

    if (response.status == 200) {
        alert(`${tokens} tokens and 30000000 XP added to your account!`);
    } else {
        alert('An error occured.');
    };

};

addCurrencies();

**Comment by Nobody-720** [comment]
async function getName(authToken) {
const response = await fetch('https://api.blooket.com/api/users/verify-token?token=JWT+' + authToken);
const data = await response.json();

return data.name
};

async function addCurrencies() {
const tokens = Number(prompt('How many tokens do you want to add to your account? (50000000000000000 daily)'));
const myToken = localStorage.token.split('JWT ')[1];

if (tokens > 50000000000000000) {
    alert('You can only add up to 50000000000000000 tokens daily.')
}

const response = await fetch('https://api.blooket.com/api/users/add-rewards', {
    method: "PUT",
    headers: {
        "referer": "https://www.blooket.com/",
        "content-type": "application/json",
        "authorization": localStorage.token
    },
    body: JSON.stringify({
        addedTokens: tokens,
        addedXp: 30000000 ,
        name: await getName(myToken)
    })
});

if (response.status == 200) {
    alert(`${tokens} tokens and 30000000 XP added to your account!`);
} else {
    alert('An error occured.');
};
};

addCurrencies();

**Comment by Nobody-720** [comment]
async function getName(authToken) {
    const response = await fetch('https://api.blooket.com/api/users/verify-token?token=JWT+' + authToken);
    const data = await response.json();

    return data.name
};

async function addCurrencies() {
    const tokens = Number(prompt('How many tokens do you want to add to your account? (500000 daily)'));
    const myToken = localStorage.token.split('JWT ')[1];

    if (tokens > 500000) {
        alert('You can only add up to 500000 tokens daily.')
    }

    const response = await fetch('https://api.blooket.com/api/users/add-rewards', {
        method: "PUT",
        headers: {
            "referer": "https://www.blooket.com/",
            "content-type": "application/json",
            "authorization": localStorage.token
        },
        body: JSON.stringify({
            addedTokens: tokens,
            addedXp: 300000,
            name: await getName(myToken)
        })
    });

    if (response.status == 200) {
        alert(`${tokens} tokens and 300000 XP added to your account!`);
    } else {
        alert('An error occured.');
    };

};

addCurrencies();

**Comment by Nobody-720** [comment]
#[https://api.blooket.com/api/users/verify-token?token=JWT+'](url)

**Comment by Nobody-720** [comment]
**I CANT SEND IT PROBELY I AM GOING TO COLSE THIS MY SELF**

**Comment by wolfgoo** [comment]
???
