### ISSUE TITLE
i can't even get to the hack page where you put in the code and how many bots n other stuff.

### ISSUE THREAD

**Issue by imgaybentley** [glixzzy/blooket-hack#392]

**Comment by glixzzy** [comment]
i don't understand

**Comment by ButterDogWasTaken** [comment]
if you are on windows press shift control j at the same time then copy and paste the code, if you are on mac right-click press inspect then go to the console tab and copy and paste the code.

**Comment by ConfusedTacos** [comment]
Hey @glixzzy, I just wanted to let you know that the Blooket hacks gotta stop. My whole middle school has downloaded your hacks, so the game is dead. For example, when someone got an astronaut they will be excited, but instead now we will just think you hacked the game. I am not trying to be mean, but Blooket hacks mean that you are bad at the game and have to cheat in order to win. The token hack isn't bad, I used it a few times, but unlocking all the blooks and getting every answer correct dosn't teach you anything and is just making the person more tempted to hack.

**Comment by ilikecatss** [comment]
> Hey @glixzzy, I just wanted to let you know that the Blooket hacks gotta stop. My whole middle school has downloaded your hacks, so the game is dead. For example, when someone got an astronaut they will be excited, but instead now we will just think you hacked the game. I am not trying to be mean, but Blooket hacks mean that you are bad at the game and have to cheat in order to win. The token hack isn't bad, I used it a few times, but unlocking all the blooks and getting every answer correct dosn't teach you anything and is just making the person more tempted to hack.

if you don't like it then don't use it

**Comment by ilikecatss** [comment]
> > Hey @glixzzy, I just wanted to let you know that the Blooket hacks gotta stop. My whole middle school has downloaded your hacks, so the game is dead. For example, when someone got an astronaut they will be excited, but instead now we will just think you hacked the game. I am not trying to be mean, but Blooket hacks mean that you are bad at the game and have to cheat in order to win. The token hack isn't bad, I used it a few times, but unlocking all the blooks and getting every answer correct dosn't teach you anything and is just making the person more tempted to hack.
> 
> if you don't like it then don't use it

not trying to be offensive tho

**Comment by wolfgoo** [comment]
> > > Hey @glixzzy, I just wanted to let you know that the Blooket hacks gotta stop. My whole middle school has downloaded your hacks, so the game is dead. For example, when someone got an astronaut they will be excited, but instead, now we will just think you hacked the game. I am not trying to be mean, but Blooket hacks mean that you are bad at the game and have to cheat in order to win. The token hack isn't bad, I used it a few times, but unlocking all the blooks and getting every answer correct doesn't teach you anything and is just making the person more tempted to hack.
> > 
> > 
> > if you don't like it then don't use it
> 
> not trying to be offensive tho

I agree.

You don't like these hacks then why now you also use these hacks.

**Comment by NihatSuleyman** [comment]
> 
> 
> 
> 
> 
> 
> > > > Hey @glixzzy, I just wanted to let you know that the Blooket hacks gotta stop. My whole middle school has downloaded your hacks, so the game is dead. For example, when someone got an astronaut they will be excited, but instead, now we will just think you hacked the game. I am not trying to be mean, but Blooket hacks mean that you are bad at the game and have to cheat in order to win. The token hack isn't bad, I used it a few times, but unlocking all the blooks and getting every answer correct doesn't teach you anything and is just making the person more tempted to hack.
> 
> > > 
> 
> > > 
> 
> > > if you don't like it then don't use it
> 
> > 
> 
> > not trying to be offensive tho
> 
> 
> 
> I agree.
> 
> 
> 
> You don't like these hacks then why now you also use these hacks.

No, hacks are cool.

**Comment by wolfgoo** [comment]
@glixzzy I think @imgaybentley is don't know where the flood mode is.

**Comment by LegendMask-72** [comment]
hello

**Comment by LegendMask-72** [comment]
whats going on

**Comment by BlooketHeck** [comment]
> Hey @glixzzy, I just wanted to let you know that the Blooket hacks gotta stop. My whole middle school has downloaded your hacks, so the game is dead. For example, when someone got an astronaut they will be excited, but instead now we will just think you hacked the game. I am not trying to be mean, but Blooket hacks mean that you are bad at the game and have to cheat in order to win. The token hack isn't bad, I used it a few times, but unlocking all the blooks and getting every answer correct dosn't teach you anything and is just making the person more tempted to hack.

Yes same thing for my middle school now Im not allowed to use blooket in school anymore

**Comment by ConfusedTacos** [comment]
oof now we use kahoot like in the 1950's bruh. imagine

**Comment by Greenlio** [comment]
why does this issue still exist
if you want to complain, leave
go poof. you probably won't stop glixzzy.
actually, you won't. there's no probably.

**Comment by ConfusedTacos** [comment]
> > > Hey @glixzzy, I just wanted to let you know that the Blooket hacks gotta stop. My whole middle school has downloaded your hacks, so the game is dead. For example, when someone got an astronaut they will be excited, but instead now we will just think you hacked the game. I am not trying to be mean, but Blooket hacks mean that you are bad at the game and have to cheat in order to win. The token hack isn't bad, I used it a few times, but unlocking all the blooks and getting every answer correct dosn't teach you anything and is just making the person more tempted to hack.
> > 
> > 
> > if you don't like it then don't use it
> 
> dam u lucky also yo school like getting all the blooks like man thats coool it wont work for me so send me a link to get all blooks man

ARE YOU KENNAN BETTY

**Comment by GlizxyBoi** [comment]
no idk who dat it tho

**Comment by ConfusedTacos** [comment]
> why does this issue still exist if you want to complain, leave go poof. you probably won't stop glixzzy. actually, you won't. there's no probably.

yeah if you wanna complain about the code I bet you could never code the scripts so go cry somewhere else.

**Comment by GlizxyBoi** [comment]
did i ask l: also did i say i was going to stop him dum shit

**Comment by GlizxyBoi** [comment]
also faster way to see messages is in gmail much faster then being on here

**Comment by varedz** [comment]
Method patched, use new method.
https://schoolcheats.net/blooket/

**Comment by LegendMask-72** [comment]
uh

**Comment by GlizxyBoi** [comment]
i aint dumb ik its on school cheats

**Comment by thunderegg6** [comment]
> i don't understand

they are idiots

**Comment by thunderegg6** [comment]
they dont get how to do simple stuff that 5 year olds can do

**Comment by thunderegg6** [comment]
> > > > > Hey @glixzzy, I just wanted to let you know that the Blooket hacks gotta stop. My whole middle school has downloaded your hacks, so the game is dead. For example, when someone got an astronaut they will be excited, but instead, now we will just think you hacked the game. I am not trying to be mean, but Blooket hacks mean that you are bad at the game and have to cheat in order to win. The token hack isn't bad, I used it a few times, but unlocking all the blooks and getting every answer correct doesn't teach you anything and is just making the person more tempted to hack.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > if you don't like it then don't use it
> > 
> > 
> > > 
> > 
> > 
> > > not trying to be offensive tho
> > 
> > 
> > I agree.
> > You don't like these hacks then why now you also use these hacks.
> 
> No, hacks are cool.

well i agree with @glixzzy he should be able to do it just because if ya make him not be able to do this your restricting his rights

**Comment by donaldli2020** [comment]
> > > > > > Hey @glixzzy, I just wanted to let you know that the Blooket hacks gotta stop. My whole middle school has downloaded your hacks, so the game is dead. For example, when someone got an astronaut they will be excited, but instead, now we will just think you hacked the game. I am not trying to be mean, but Blooket hacks mean that you are bad at the game and have to cheat in order to win. The token hack isn't bad, I used it a few times, but unlocking all the blooks and getting every answer correct doesn't teach you anything and is just making the person more tempted to hack.
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > if you don't like it then don't use it
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > not trying to be offensive tho
> > > 
> > > 
> > > I agree.
> > > You don't like these hacks then why now you also use these hacks.
> > 
> > 
> > No, hacks are cool.
> 
> well i agree with @glixzzy he should be able to do it just because if ya make him not be able to do this your restricting his rights

i agree

**Comment by thunderegg6** [comment]
??

**Comment by Matyfurball883** [comment]
Hi people

**Comment by thunderegg6** [comment]
github is blocked

**Comment by GlizxyBoi** [comment]
my guy you on crack its not blocked

**Comment by thunderegg6** [comment]
it is for me

**Comment by GlizxyBoi** [comment]
ooof bozo + ratio lmao clown jk

**Comment by thunderegg6** [comment]
[image: Screenshot 2022-02-08 09.49.04.png] its a ss of me opening github
