### ISSUE TITLE
tokens 

### ISSUE THREAD

**Issue by GlizxyBoi** [glixzzy/blooket-hack#395]
bruh why am i not getting tokens

**Comment by Greenlio** [comment]
are you signed in?
if not, sign in.
if so, go to blooket stats page. go to bottom. how much does it say under "Daily Tokens Available"?
if it's 0, you have to wait until the timer on its right to go up before you can get 500 more.

**Comment by Brandon981026** [comment]
great comment

**Comment by NihatSuleyman** [comment]
> bruh why am i not getting tokens 

Maximum tokens you can get is 500. Make sure you entered the right amount and make sure you are signed in to your blooket account.
