### ISSUE TITLE
No tokens after game

### ISSUE THREAD

**Issue by Duggeewoof** [glixzzy/blooket-hack#399]
I played a solo game of Factory, but at the end it said "Max amount of tokens (500) and XP (300)" But before I tried this hack, it gave me coins after a game. What happened??

**Comment by SwingWitMe** [comment]
Its because you use the coin hack already and got max tokens and XP so you have to wait till the daily token limit resets.

**Comment by Quancubaprocraft2912** [comment]
yeah thats right
