### ISSUE TITLE
Are there any clearer source files?

### ISSUE THREAD

**Issue by Infiniti20** [glixzzy/blooket-hack#4]
I was just trying to find any source files for this project that are not obfuscated, because this code is quite hard to read and understand, and no site was able to unobfuscate it. I'd really like to take a look at how you managed to decode Blooket's WebSocket messages, as they are very cryptic. I couldn't find any endpoints that you were requesting, as nothing looked like a URL. I'm not sure why you keep closing issues, but why post this on GitHub if you're doing this? GitHub's whole purpose is for open source software development, and not listening to issues, and obfuscating code ruins that. Thanks for reading this.

### **DO NOT CLOSE PLEASE**

**Comment by glixzzy** [comment]
I made this repo so it can show up on the search engine, which it did. I purposely made it heavily obfuscated so no one can read it.

Unobfuscated file: https://github.com/glixzzy/blooket-hack/blob/main/global/addTokens.js

**Comment by Portat** [comment]
I agree with Infiniti20. I also found a problem. On the Tower Defense Round Change, it works the first time but the second time on it multiplies the level by 10.

**Comment by PhilParr7** [comment]
just deobfussicate and then put in to a JavaScript pretty print

**Comment by ThatFruedDued** [comment]
I suspect the reason @glixzzy obfuscates is to protect the scripts from getting patched. However, I also agree that is probably more important for people to tinker around with the code, because the features are easy to patch anyway when you know what they do.
