### ISSUE TITLE
Why does school cheats have to be blocked (Btw Glizxy its me @Swingwitme)

### ISSUE THREAD

**Issue by ammoVR3** [glixzzy/blooket-hack#400]
Is there a way or site to bypass blocked sites (VPNS ARE BLOCKED SO DONT SAY VPN)

**Comment by ConfusedTacos** [comment]
> Is there a way or site to bypass blocked sites (VPNS ARE BLOCKED SO DONT SAY VPN)

umm well try turning off your wifi and turning it back on then immidetly go to the website you want.

**Comment by Greenlio** [comment]
bookmarklets

**Comment by ammoVR3** [comment]
Thats what i used i put the code in a bookmark and it takes me to the site

**Comment by Greenlio** [comment]
use the individual file bookmarklets, like click on a folder and it'll tell you the code for that specific file.

**Comment by ammoVR3** [comment]
what do i do with the code?

**Comment by wolfgoo** [comment]
?

**Comment by wolfgoo** [comment]
school cheats not blocked.

**Comment by wolfgoo** [comment]
I also can use school cheats now
