### ISSUE TITLE
Permanent Blooks Using API

### ISSUE THREAD

**Issue by P1uffy** [glixzzy/blooket-hack#404]
Could you maybe add another hack where you can get permanent blooks? 
Im not sure but maybe this API might help? https://api.blooket.com/api/users/unlockblook

**Comment by Greenlio** [comment]
Nopers, that's the endpoint to open **boxes** such as Bot Box, Aquatic Box, etc. Refer to [this](https://github.com/glixzzy/blooket-hack/blob/f9c2ce1703367b5dc545fa4e0cb72c5241999b27/global/spamOpenBoxes.js#L29) to see it used.

**Comment by GlizxyBoi** [comment]
> Could you maybe add another hack where you can get permanent blooks? Im not sure but maybe this API might help? https://api.blooket.com/api/users/unlockblook

that would be cool but the link aint working
