### ISSUE TITLE
Nothing is Working

### ISSUE THREAD

**Issue by NCGamer118** [glixzzy/blooket-hack#406]

**Comment by GlizxyBoi** [comment]
> _No description provided._

what do you mean nothing is working? just copy them then do inspect then paste in the console then hit enter like its so simple also explain how nothing is working

**Comment by glixzzy** [comment]
elaborate

**Comment by ilikecatss** [comment]
EVERYTHING is working

**Comment by varedz** [comment]
Method patched, use new method.
https://schoolcheats.net/blooket/
