### ISSUE TITLE
Spamopenboxes Isn't working

### ISSUE THREAD

**Issue by Coolkid560** [glixzzy/blooket-hack#409]
I clicked it and nothing happend, please help!

**Comment by ilikecatss** [comment]
you need to paste the code

**Comment by ilikecatss** [comment]
not just click

**Comment by Nobody-720** [comment]
**clicked the code ;=; **

_bro read the instrution_

**Comment by Coolkid560** [comment]
No i did that, It still isn't working
HELP

**Comment by ConfusedTacos** [comment]
> No i did that, It still isn't working HELP

You can't spam open boxes unless you have tokens. Also, it does work it legit tells you when you paste the code.

**Comment by Greenlio** [comment]
https://user-images.githubusercontent.com/62725108/143144591-962d9e09-e425-4601-9a58-201d2ff9a06e.mp4

**Comment by varedz** [comment]
Method patched, use new method.
https://schoolcheats.net/blooket/
