### ISSUE TITLE
Glizzy pls answer

### ISSUE THREAD

**Issue by Gamehacker69** [glixzzy/blooket-hack#410]
@glixzzy  idk were to ask you this but here i was wondering if you could look into making hacks for gimkit cause all of my teachers starting to only do gimkit now

**Comment by wolfgoo** [comment]
gimkit???

**Comment by ilikecatss** [comment]
Pls don't make random issues

**Comment by ilikecatss** [comment]
If you have a request, ask @glixzzy on discord

**Comment by ilikecatss** [comment]
too many issues will give this hack a bad rep

**Comment by ilikecatss** [comment]
oh yeah click this #380

**Comment by ilikecatss** [comment]
#380

**Comment by wolfgoo** [comment]
ya

**Comment by Greenlio** [comment]
here's why we don't make Gimkit hacks:

Gimkit politely asked us not to. They aren't a thousand dollar company with multiple employees like Blooket or Quizizz or Kahoot, and it's only one guy running the entire website.
Now you know.

**Comment by varedz** [comment]
Method was patched, use new method.
https://schoolcheats.net/blooket/
https://www.youtube.com/watch?v=uuCwUL-dEDk

**Comment by ashley20946** [comment]
THE HACKS DONT WORK >=(
