### ISSUE TITLE
can you please make it so i can use it on "my blooks" tab?

### ISSUE THREAD

**Issue by blookethack** [glixzzy/blooket-hack#411]
that would be great

**Comment by Nobody-720** [comment]
Well YU can if yu seach in github

**Comment by Nobody-720** [comment]
https://github.com/rebound37/BlooketUnlockAllPerm [ this link ] 
https://github.com/Moonboy05/BlooketHacks [ this link { in global - Spoof All Blooks on Blooks Page }

Pls Note This : **Wont Add Any Blooks To Your Acc**

**Comment by Greenlio** [comment]
English
