### ISSUE TITLE
wanna stats hack?

### ISSUE THREAD

**Issue by itzmederpy** [glixzzy/blooket-hack#412]
first you go to your blooket stats and see up it will say https://www.blooket.com/stats then you type up ther until like this:https://www.blooket.com/stats?name= and then enter a name. ( you can find names in discover) try to hack me! im lowyuchen2he

**Comment by itzmederpy** [comment]
it's fun!

**Comment by Nobody-720** [comment]
ok ;=; [ we dont even know its real or not ]

**Comment by Nobody-720** [comment]
but I have every thing execpt [ **blizzard box / all chromas** ]

**Comment by Nobody-720** [comment]
this isnt a stas hack [ its just see other people stast only ]

**Comment by wolfgoo** [comment]
yes

**Comment by therealwinner** [comment]
this page is only meant for **issues** not for advertising or suggestions.

**Comment by Greenlio** [comment]
> this page is only meant for **issues** not for advertising or suggestions.

well it's not advertising.. and in my opinion suggestions are definitely welcomed along with fixes of things already made so

**Comment by ilikecatss** [comment]
#381 <--pls dont open random issues like this guy
