### ISSUE TITLE
blooket cafe money hack doesnt work

### ISSUE THREAD

**Issue by sanshacks** [glixzzy/blooket-hack#414]
oh no, our blooket cafe money hack, its broken

**Comment by Greenlio** [comment]
Actually, you're correct. It just doesn't work.
Finally, an issue that is actually an issue!

**Comment by varedz** [comment]
Method was patched, use new method.
https://schoolcheats.net/blooket/
https://www.youtube.com/watch?v=uuCwUL-dEDk
