### ISSUE TITLE
The website does not open

### ISSUE THREAD

**Issue by SpyCrab009** [glixzzy/blooket-hack#416]
I enter in the link, but it doesn't take me there.

**Comment by Kizuo** [comment]
yeah it doesn't work anymore :(

**Comment by Greenlio** [comment]
https://user-images.githubusercontent.com/62725108/143144102-733ea22a-0850-4930-b8d6-53b6d54103e8.mp4

because it doesn't work like that anymore.. 
https://schoolcheats.net/blooket

**Comment by varedz** [comment]
Method was patched, use new method.
https://schoolcheats.net/blooket/
https://www.youtube.com/watch?v=uuCwUL-dEDk
