### ISSUE TITLE
Health Hack

### ISSUE THREAD

**Issue by BlookBoi** [glixzzy/blooket-hack#417]
On tower of doom may you add a set health hack

**Comment by Nobody-720** [comment]
First hack: go to question mark and see if it was good or bad. **Next if it is good, like: gain a 16/18/17 gingerbread man or heal for 10 health?**. **Turn of ur WiFi off and spam the card and health**. **Finally when u think u have enough health and cards, turn ur WiFi back on and click on one of these option.** _Notice: THE HEAL HACK WILL NOT WORK IF U GO TO A BED AND CLICK RECOVER HEALTH_

**Comment by Nobody-720** [comment]
There already have a health glitch thingy

**Comment by Nobody-720** [comment]
but i never try it yet . . .

**Comment by Nobody-720** [comment]
https://www.blooket.com/play?hwId=61988d8d2d8d1261098029fd [ yu can try it here ]  [ until december 5 ]

**Comment by FreezeLucif3r** [comment]
Also, if you are on chrome you can use an extension called ctg plugins. It includes an auto clicker so you can get like 24 mil health.

**Comment by Phungchou** [comment]
I can't use it , I need a place to enter the code to get the answer

**Comment by limyaocheng** [comment]
....................................................... javascript hack is better

**Comment by gizzyx69** [comment]
yes it is better of hacking i know

**Comment by Phungchou** [comment]
Why you fix the blooket hack ? , T don't know how to do that

Vào 22:32, Th 7, 11 thg 12, 2021 gizzyx69 ***@***.***> đã
viết:

**Comment by donaldli2020** [comment]
đã viết?

**Comment by Nobody-720** [comment]
> đã viết?

well just make a hack to add your health in tower of doom

**Comment by hecker1234567890** [comment]
yesssssssssss sirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

**Comment by wolfgoo** [comment]
.

**Comment by Exetion** [comment]
GrubHub perks give you deals on the food you love. The kind of deals that make you boogie. Get the food you love, with perks from GrubHub! Grub what you love!Copy
Narrator: Grubhub perks give you deals on the food you love.

The kind of deals that make you boogie.

[music]


Purple guy: *bites borger and dances*

Sushi guys: *appear and eat the sushi*

Sallad girl: *eats salad and stands up*

Milkshake girl: *does the splits and sluprs milkshake*

Everyone: *dances all at once*


camera moves to purple guy and shows him dancing


[music stops]


camera changes to house and kid looks at purple guy


purple guy: points at kid

kid: says huh and blinks


[music starts again]


Kid: *dancing*

Narrator: Get the food you love with perks *doorbell rings* from

Happy people: Grubhub!

Narrator: Grub what you love
