### ISSUE TITLE
I was just wondering can yu add [ addXpOnly.js & addTokensOnly.js & InstantAddTokens&Xp.js ]   { Can Yu Add Mine ? } [ TQ and sry This Isnt A Issues ] 

### ISSUE THREAD

**Issue by Nobody-720** [glixzzy/blooket-hack#418]
TQ :) It Is Your Choice If Yu want to add or not

**Comment by Nobody-720** [comment]
https://github.com/Nobody-720/Blooket_Hacks [ mine ]

**Comment by Greenlio** [comment]
the long issue name makes me want to die

why would he do that..
i'm atm making a way to customize both how much xp and tokens you get so

**Comment by Nobody-720** [comment]
ok

**Comment by Nobody-720** [comment]
should i just close this issue

**Comment by blockerss** [comment]
actually its impossible to do only xp or tokens from my point of view. blooket connected them both. adding tokens gets you xp. thats why xp only aint a hack.

**Comment by Greenlio** [comment]
> actually its impossible to do only xp or tokens from my point of view. blooket connected them both. adding tokens gets you xp. thats why xp only aint a hack.

just send a request with 0 as one of them
like it did before we updated a few weeks ago

**Comment by Nobody-720** [comment]
> 

`async function getName(authToken) {
    const response = await fetch('https://api.blooket.com/api/users/verify-token?token=JWT+' + authToken);
    const data = await response.json();

    return data.name
};

async function addCurrencies() {
    const Xp = Number(prompt('How many Xp do you want to add to your account? (300 daily)'));
    const myToken = localStorage.token.split('JWT ')[1];

    if (Xp > 500) {
        alert('You can only add up to 300 Xp daily.')
    }

    const response = await fetch('https://api.blooket.com/api/users/add-rewards', {
        method: "PUT",
        headers: {
            "referer": "https://www.blooket.com/",
            "content-type": "application/json",
            "authorization": localStorage.token
        },
        body: JSON.stringify({
            addedXp: Xp,
            name: await getName(myToken)
        })
    });

    if (response.status == 200) {
        alert(`${Xp} XP added to your account!`);
    } else {
        alert('An error occured.');
    };

};

addCurrencies();`

**Comment by Nobody-720** [comment]
> > actually its impossible to do only xp or tokens from my point of view. blooket connected them both. adding tokens gets you xp. thats why xp only aint a hack.
> 
> just send a request with 0 as one of them like it did before we updated a few weeks ago

https://github.com/Nobody-720/Blooket_Hacks/blob/main/%F0%9D%90%9A%F0%9D%90%9D%F0%9D%90%9D%F0%9D%90%97%F0%9D%90%A9%F0%9D%90%8E%F0%9D%90%A7%F0%9D%90%A5%F0%9D%90%B2.%F0%9D%90%A3%F0%9D%90%AC

[ Try This Hack ]

**Comment by Greenlio** [comment]
no
stop advertising yourself
go away
+ ratio
+ you're banned from the glizzers discord for being underage + L bozo
