### ISSUE TITLE
Nothing Works

### ISSUE THREAD

**Issue by Amit-Choudhary11** [glixzzy/blooket-hack#419]
When I copy it, then paste it in the console, this is what pops up:

Refused to connect to 'https://raw.githubusercontent.com/glixzzy/blooket-hack/main/main.js' because it violates the document's Content Security Policy.

**Comment by PBCup** [comment]
yes, same here!!!

**Comment by glixzzy** [comment]
fixed:

https://user-images.githubusercontent.com/73669084/142743662-a2aa7099-7e83-4449-9840-b598ae5e53f8.mp4
