### ISSUE TITLE
Nothing works anymore!!!

### ISSUE THREAD

**Issue by PBCup** [glixzzy/blooket-hack#420]
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/93473423/142731711-2120aa7c-b77b-4175-b655-c27895f0155d.png">

Idk if its just safari but this worked on google the other day, It worked on safari before for me, I think that they patched it?

**Comment by PBCup** [comment]
Idk if its just safari but this worked on google the other day, It worked on safari before for me, I think that they patched it?

**Comment by PBCup** [comment]
now I have to play factory for an hour to get 500 coins lol

**Comment by PBCup** [comment]
<img width="1115" alt="Screen Shot 2021-11-20 at 10 17 44 AM" src="https://user-images.githubusercontent.com/93473423/142731703-3bd0221c-d546-43f5-858e-674485b5e5ad.png">

**Comment by Kizuo** [comment]
oh god... why ben???

he definitely blocked it because it worked on opera, firefox, chrome, and safari, but now it doesn't. Shoot, there goes my chroma grinding plan.

**Comment by DerpChest** [comment]
Ben is an asshole

**Comment by glixzzy** [comment]
fixed:

https://user-images.githubusercontent.com/73669084/142743658-369c7a00-f121-4e0d-b842-ab39539bd23e.mp4
