### ISSUE TITLE
It doesn't work anymore...

### ISSUE THREAD

**Issue by Kizuo** [glixzzy/blooket-hack#421]
Refused to connect to 'https://raw.githubusercontent.com/glixzzy/blooket-hack/main/main.js' because it violates the following Content Security Policy directive: "connect-src 'self' https://api.blooket.com kit.fontawesome.com ka-f.fontawesome.com www.google-analytics.com www.googleapis.com firebase.googleapis.com firebaseinstallations.googleapis.com *.firebaseio.com wss://*.firebaseio.com res.cloudinary.com api.cloudinary.com images.unsplash.com".

(anonymous) @ VM266:1
VM266:1 Refused to connect to 'https://raw.githubusercontent.com/glixzzy/blooket-hack/main/main.js' because it violates the document's Content Security Policy.
(anonymous) @ VM266:1
VM266:1 Uncaught (in promise) TypeError: Failed to fetch
    at <anonymous>:1:1

This is what I get if I try to run the main hack, not sure why but I think it may be because of them finally realizing how overpowered this is. They then fixed it. Trying to get a chroma but now its gonna take forever :(

**Comment by DarklordX89X** [comment]
Im gonna try and get around this

**Comment by Random0120** [comment]
Ben, (The creator of Blooket), fixed it so you can't hack anymore.

**Comment by glixzzy** [comment]
fixed:

https://user-images.githubusercontent.com/73669084/142743652-4579e189-77ae-4ca1-96f8-1ca745a07e09.mp4
