### ISSUE TITLE
It broke

### ISSUE THREAD

**Issue by maxim-iakovlev** [glixzzy/blooket-hack#423]
When i pste it into the console it states:
VM459:1 Refused to connect to 'https://raw.githubusercontent.com/glixzzy/blooket-hack/main/tower-of-doom/lowerAllEnemyStats.js' because it violates the following Content Security Policy directive: "connect-src 'self' https://api.blooket.com kit.fontawesome.com ka-f.fontawesome.com www.google-analytics.com www.googleapis.com firebase.googleapis.com firebaseinstallations.googleapis.com *.firebaseio.com wss://*.firebaseio.com res.cloudinary.com api.cloudinary.com images.unsplash.com".

**Comment by Random0120** [comment]
Ben, (The creator of Blooket), fixed it so you can't hack anymore.

**Comment by Random0120** [comment]
Never mind, paste in this code instead:

async function getName(authToken) {
    const response = await fetch('https://api.blooket.com/api/users/verify-token?token=JWT+' + authToken);
    const data = await response.json();

    return data.name
};

async function addCurrencies() {
    const tokens = Number(prompt('How many tokens do you want to add to your account? (500 daily)'));
    const myToken = localStorage.token.split('JWT ')[1];

    if (tokens > 500) {
        alert('You can only add up to 500 tokens daily.')
    }

    const response = await fetch('https://api.blooket.com/api/users/add-rewards', {
        method: "PUT",
        headers: {
            "referer": "https://www.blooket.com/",
            "content-type": "application/json",
            "authorization": localStorage.token
        },
        body: JSON.stringify({
            addedTokens: tokens,
            addedXp: 300,
            name: await getName(myToken)
        })
    });

    if (response.status == 200) {
        alert(`${tokens} tokens and 300 XP added to your account!`);
    } else {
        alert('An error occured.');
    };

};

addCurrencies();

**Comment by glixzzy** [comment]
fixed

https://user-images.githubusercontent.com/73669084/142743645-5611f876-0e8c-483a-9084-869486263383.mp4
