### ISSUE TITLE
it broke, nothing works anymore, says that i

### ISSUE THREAD

**Issue by Phoenix490** [glixzzy/blooket-hack#424]
"Refused to connect to 'https://raw.githubusercontent.com/glixzzy/blooket-hack/main/main.js' because it violates the document's Content Security Policy. (anonymous)Uncaught (in promise) 
TypeError: Failed to fetch at <anonymous>:1:1"

**Comment by DerpChest** [comment]
Happened to me too

**Comment by Random0120** [comment]
Ben, (The creator of Blooket), fixed it so you can't hack anymore.

**Comment by Random0120** [comment]
Never mind, paste in this code instead:

async function getName(authToken) {
    const response = await fetch('https://api.blooket.com/api/users/verify-token?token=JWT+' + authToken);
    const data = await response.json();

    return data.name
};

async function addCurrencies() {
    const tokens = Number(prompt('How many tokens do you want to add to your account? (500 daily)'));
    const myToken = localStorage.token.split('JWT ')[1];

    if (tokens > 500) {
        alert('You can only add up to 500 tokens daily.')
    }

    const response = await fetch('https://api.blooket.com/api/users/add-rewards', {
        method: "PUT",
        headers: {
            "referer": "https://www.blooket.com/",
            "content-type": "application/json",
            "authorization": localStorage.token
        },
        body: JSON.stringify({
            addedTokens: tokens,
            addedXp: 300,
            name: await getName(myToken)
        })
    });

    if (response.status == 200) {
        alert(`${tokens} tokens and 300 XP added to your account!`);
    } else {
        alert('An error occured.');
    };

};

addCurrencies();

**Comment by glixzzy** [comment]
fixed

https://user-images.githubusercontent.com/73669084/142743640-5006c061-59ce-43c4-8ca9-32c15e18c1e8.mp4
