### ISSUE TITLE
glixzzly blooket -Hack is not working

### ISSUE THREAD

**Issue by Amlica** [glixzzy/blooket-hack#427]
the codes and the url have changed when I added tokens it said 0 tokens added 0 can You believe that it used to work fine but now the code changed and it is not working

**Comment by Greenlio** [comment]
https://user-images.githubusercontent.com/62725108/143143822-89052c50-873b-4a94-a3e5-5447a38a871b.mp4

**Comment by Greenlio** [comment]
that's all you have to do

im already on limit so it's simply impossible but the procedure works

**Comment by varedz** [comment]
Method was patched, use new method.
https://schoolcheats.net/blooket/
https://www.youtube.com/watch?v=uuCwUL-dEDk

**Comment by Amlica** [comment]
thank You but I have an easier way of doing it you just need to go to the bar and type in Javascript: and enter the url
