### ISSUE TITLE
not getting tokens

### ISSUE THREAD

**Issue by herbsxx** [glixzzy/blooket-hack#431]
when  i enter the code on console it says  

main.js?attr=Nig4j0qPAW-CBhJoN_3aVIsbA5yer3m17N6MiW4tov3m3HRl6TMgvoYW1BBoTcZh:2562 Uncaught (in promise) TypeError: Failed to fetch
    at fetchCallImpl (main.js?attr=Nig4j0qPAW-CBhJoN_3aVIsbA5yer3m17N6MiW4tov3m3HRl6TMgvoYW1BBoTcZh:2562)
    at window.fetch (main.js?attr=Nig4j0qPAW-CBhJoN_3aVIsbA5yer3m17N6MiW4tov3m3HRl6TMgvoYW1BBoTcZh:2564)
    at <anonymous>:1:1
fetchCallImpl @ main.js?attr=Nig4j0qPAW-CBhJoN_3aVIsbA5yer3m17N6MiW4tov3m3HRl6TMgvoYW1BBoTcZh:2562
window.fetch @ main.js?attr=Nig4j0qPAW-CBhJoN_3aVIsbA5yer3m17N6MiW4tov3m3HRl6TMgvoYW1BBoTcZh:2564
(anonymous) @ VM89:1
Promise.then (async)
(anonymous) @ VM89:1

**Comment by herbsxx** [comment]
also is there no more sell dupe blooks?

**Comment by glixzzy** [comment]
brought back bookmarklets like before so everything should work fine now
