### ISSUE TITLE
It says i have to join some discord wich i would do but my school blocked that site, so now i cant get the hacks

### ISSUE THREAD

**Issue by Ashempower** [glixzzy/blooket-hack#433]

**Comment by glixzzy** [comment]
you don't have to join any discord server??? go to https://schoolcheats.net/blooket and scroll down lol
![image](https://user-images.githubusercontent.com/73669084/142749088-def5d87a-ad9d-4341-9230-ff8c134d24ec.png)

**Comment by glixzzy** [comment]
brought back bookmarklets so you can use easily llike before

**Comment by Ashempower** [comment]
> you don't have to join any discord server??? go to https://schoolcheats.net/blooket and scroll down lol ![image](https://user-images.githubusercontent.com/73669084/142749088-def5d87a-ad9d-4341-9230-ff8c134d24ec.png)

Ok thanks.
