### ISSUE TITLE
blooket 

### ISSUE THREAD

**Issue by ashley20946** [glixzzy/blooket-hack#438]
make the hacks back on the website because thare blooked

**Comment by glixzzy** [comment]
k

**Comment by ashley20946** [comment]
thank you =)

**Comment by ashley20946** [comment]
thank you thank you thank you =)

**Comment by ashley20946** [comment]
your the best

**Comment by ashley20946** [comment]
changed my name i think

**Comment by ashley20946** [comment]
Is there a hack where you can keep hacked blookes but not in game?
