### ISSUE TITLE
NOTHING WORKS

### ISSUE THREAD

**Issue by CyberElektro** [glixzzy/blooket-hack#441]
pls bring back the original code bc the schoolcheats version DOESNT WORK the atob whatever no work pls use back the raw github whatever thingy i beggg u i need to grind for winter why ru ruining it

**Comment by ilikecatss** [comment]
please elaborate

**Comment by ilikecatss** [comment]
we dont know whats ur issue

**Comment by ShiixeN** [comment]
the fact that it was moved to schoolcheats honestly dissapoints me.

**Comment by Greenlio** [comment]
> the fact that it was moved to schoolcheats honestly dissapoints me.

hey, by all means, open a pull request if you have a fix for it.

**Comment by glixzzy** [comment]
everything works.
