### ISSUE TITLE
issues 

### ISSUE THREAD

**Issue by GlizxyBoi** [glixzzy/blooket-hack#449]
ummm btw the spam open boxes aint working so can yall fix it

**Comment by glixzzy** [comment]
it does work.

https://user-images.githubusercontent.com/73669084/142940867-63f3c7d2-679b-4f07-a93c-df4adcdbf1c1.mp4

**Comment by GlizxyBoi** [comment]
Thank you

**Comment by GlizxyBoi** [comment]
I did it once and it worked now it dont work

**Comment by GlizxyBoi** [comment]
btw how u have so many coins too open boxes is there a hack for that to?

**Comment by GlizxyBoi** [comment]
yeah how u got so many coins is there a hack for that too?
