### ISSUE TITLE
Nothing is loading up 

### ISSUE THREAD

**Issue by willutgilugpiulg** [glixzzy/blooket-hack#451]
i do javascript: then i paste in school cheats or the strait up script it wont Go anywhere it stays on blooket no things open up or anything

**Comment by glixzzy** [comment]
what script are you putting?

**Comment by glixzzy** [comment]
everyone cheat is at https://schoolcheats.net/blooket

**Comment by varedz** [comment]
Method was patched, use new method.
https://schoolcheats.net/blooket/
https://www.youtube.com/watch?v=uuCwUL-dEDk
