### ISSUE TITLE
blooket

### ISSUE THREAD

**Issue by CurtisBarnes1** [glixzzy/blooket-hack#453]
chest esp is broken

**Comment by ilikecatss** [comment]
working fine for me

**Comment by blockerss** [comment]
some people like me bookmark the hacks. if you bookmark it chest esp works once and then becomes frozen in place

**Comment by Seantheboy101** [comment]
i love the hacks

**Comment by yee-negative** [comment]
sometimes chest esp show wrong item.this happen sometimes (only) then it will changed into the right item

**Comment by glixzzy** [comment]
fixed
