### ISSUE TITLE
School Cheats broken

### ISSUE THREAD

**Issue by ilikecatss** [glixzzy/blooket-hack#454]
Some of the scripts from school cheats aren't working 
example: addtokens.js

**Comment by ilikecatss** [comment]
it wont add any tokens whatsoever

**Comment by Itsmantis** [comment]
it still work tho even till now im still using it

**Comment by glixzzy** [comment]
all the scripts schoolcheat has is in here too idk wym its broken lmfao

**Comment by Greenlio** [comment]
https://user-images.githubusercontent.com/62725108/143143522-875e921c-dd36-43bd-9d8b-7478d287125f.mp4

example uses the one here, but they're literally the same

**Comment by varedz** [comment]
Method was patched, use new method.
https://schoolcheats.net/blooket/
https://www.youtube.com/watch?v=uuCwUL-dEDk
