### ISSUE TITLE
if i try to bookmark the hacks only around half of them work.

### ISSUE THREAD

**Issue by blockerss** [glixzzy/blooket-hack#457]
a lot of the hacks bookmarked like addtokens don't work. and the choice esp only activates once (you have to keep going back and using the bookmark because it works once and then becomes frozen in place) unlike it used to be stable (changing throughout the game). please try to fix this, i do understand that you might have some pressure from the community who uses these hacks. just try your best.

**Comment by glixzzy** [comment]
2 days ago blooket made a huge change that broke all these hacks, we tried out best to fix them and still are

**Comment by varedz** [comment]
Method was patched, use new method.
https://schoolcheats.net/blooket/
https://www.youtube.com/watch?v=uuCwUL-dEDk
