### ISSUE TITLE
Spam open boxes is confusing.

### ISSUE THREAD

**Issue by funlover2** [glixzzy/blooket-hack#459]
When I spamed, I got a ton of stuff, and it left me with $3994. Then, when I sold everything, I got less money. I now have $2694. Why did I lose money from selling stuff?

**Comment by GlizxyBoi** [comment]
> because when you sell them you dont always get the same amount back

no say i have 2000 and i spam and type 10 for the space box i spam then i would have 1800 then i sell you would have more say i went to 2200 then you dont lose money selling them

**Comment by glixzzy** [comment]
no its not, youre just putting the box name incorrectly. it gives you an example: `Space`
