### ISSUE TITLE
add the currency does no longer work for my school district

### ISSUE THREAD

**Issue by Meaperson** [glixzzy/blooket-hack#467]
um............................................................................................................................................................................................................................................................yeah, so when you do it it ethier kicks you out or does not add it.P.S. is ther a way to add more than 500 tokens a day?

**Comment by glixzzy** [comment]
i'm confused what doesn't work?

**Comment by Greenlio** [comment]
> um............................................................................................................................................................................................................................................................yeah, so when you do it it ethier kicks you out or does not add it.P.S. is ther a way to add more than 500 tokens a day?

A) No, there isn't a way to get more than 500 tokens a day. It's server side.
B)

https://user-images.githubusercontent.com/62725108/143382866-f85e0c6c-f055-42d9-944a-8df3e6a6af0b.mp4
