### ISSUE TITLE
spam open boxes does not work

### ISSUE THREAD

**Issue by Meaperson** [glixzzy/blooket-hack#468]
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

**Comment by glixzzy** [comment]
https://user-images.githubusercontent.com/73669084/143333310-a6725408-f33e-4029-83fc-2095a5793124.mp4

**Comment by Meaperson** [comment]
it still does not do that
