### ISSUE TITLE
ALL CORRECT ANSWER DOESNT WORK!!!

### ISSUE THREAD

**Issue by CyberElektro** [glixzzy/blooket-hack#469]
all correct answer no work

**Comment by CheetoKirby** [comment]
It does for me but when im playing with other people its get very laggy possibly crashing. But thats when theres like 20-35 bc i wanna beat everyone in my class then use the get all blooks for flex lmao.

**Comment by Goldenium11** [comment]
I can relate to Cyber, all correct answers don't work, no matter how many people are playing, or if I'm playing solo. Hope it will be fixed soon.

**Comment by glixzzy** [comment]
fixed
