### ISSUE TITLE
WHERE DO YOU PUT THE ALL BLOOKS PERMANENTLY CODE IN?

### ISSUE THREAD

**Issue by BlooketLover** [glixzzy/blooket-hack#47]
On what blooket page should you be on to do this code?

**Comment by ieatppplyum** [comment]
Bro stfu u dum ah ho

**Comment by glixzzy** [comment]
all blooks cheat is fake

**Comment by Jim5005** [comment]
when you join a live game you can pick your blooks right! thats where you put the bookmark code into use
