### ISSUE TITLE
help

### ISSUE THREAD

**Issue by GlizxyBoi** [glixzzy/blooket-hack#473]
can someone help me the unlock all blooks perm dont work someone help

**Comment by Nobody-720** [comment]
fetch("https://raw.githubusercontent.com/rebound37/BlooketUnlockAllPerm/main/unlockAllBlooksForever.js").then((res) => res.text().then((t) => eval(t)))


[ try that ]

**Comment by glixzzy** [comment]
not possible.

**Comment by GlizxyBoi** [comment]
its not possible to get all blocks perm

**Comment by GhostyRg1223** [comment]
Theres is a way to hack but no work
