### ISSUE TITLE
I have a problem!

### ISSUE THREAD

**Issue by therealwinner** [glixzzy/blooket-hack#475]
first of all the get all answers correct doesn't work and second can you please work on classic and battle royale because those suck so much, and I would really enjoy it if you helped fix this. I would also like a damage feature for tower defense so that you could be on there for a hosting blooket. thank you! -@therealwinner>50.

**Comment by ilikecatss** [comment]
impossible to make classic and battle royale hack

**Comment by Goldenium11** [comment]
I don't exactly relate to the tower defense, but I would appreciate if the all answers correct would be fixed.

**Comment by glixzzy** [comment]
fixed
