### ISSUE TITLE
New game

### ISSUE THREAD

**Issue by donaldli2020** [glixzzy/blooket-hack#478]
Santa's Workshop

**Comment by ilikecatss** [comment]
pls dont open random issues like this ==>#381

**Comment by itzmederpy** [comment]
j

**Comment by itzmederpy** [comment]
sucks

**Comment by Greenlio** [comment]
To my knowledge, we _plan_ to have cheats for Santa's Workshop a few days after it comes out. However, there are no guarantees. 
Also stop be cringe, this isn't a "random" issue lmao.

**Comment by ilikecatss** [comment]
> To my knowledge, we _plan_ to have cheats for Santa's Workshop a few days after it comes out. However, there are no guarantees. Also stop be cringe, this isn't a "random" issue lmao.

kind of tho...

**Comment by ilikecatss** [comment]
> To my knowledge, we _plan_ to have cheats for Santa's Workshop a few days after it comes out. However, there are no guarantees. Also stop be cringe, this isn't a "random" issue lmao.

kind of random tho

**Comment by gizzyx69** [comment]
if not we can get it next year

**Comment by wolfgoo** [comment]
I got Santa's workshop hacks

**Comment by wolfgoo** [comment]
Use multitool I also have used it to use Santa's Workshop hack.

on Gbazil find multitool copy and paste the multitool the bookmarklet and in blooket to use.

link:(https://www.gbasil.dev/blooket)

**Comment by hecker1234567890** [comment]
lmao!!!!























it is blocked.....

**Comment by wolfgoo** [comment]
?

**Comment by wolfgoo** [comment]
not blocked
