### ISSUE TITLE
ITS HORRIBLE

### ISSUE THREAD

**Issue by Tra123456** [glixzzy/blooket-hack#479]
THE ADD COINS ON TOWER OF DOOM IS NOT WORKING.
WHENEVER I USE IT, IT WILL STOP THE GAME
WHAT SHOULD I DO 
@glixzzy

**Comment by GlizxyBoi** [comment]
what yall talking about it works for me just fine

**Comment by Greenlio** [comment]
@GlizxyBoi bruh, what kind of among us computer you running. You say everything works fine when it's actually broken.

Likely due to the bing bong security update Ben randomly did. Tested, definitely doesn't work.

**Comment by GlizxyBoi** [comment]
bruh wuch u mean by among us computer like tower of doom and coins
dont work tf it does why people still have that issue god dam

**Comment by Greenlio** [comment]
Because it doesn't work?!

**Comment by Greenlio** [comment]
Tower of Doom is actually broken and you're oblivious.

**Comment by GlizxyBoi** [comment]
its not

**Comment by Greenlio** [comment]
You're just wrong lol. Anyway, why cringe impersonation. You aren't gliz.

**Comment by GlizxyBoi** [comment]
ik that... btw i am not wrong ok i am right tower of doom add coins works

**Comment by glixzzy** [comment]
fixed, run the code twice for it to work
