### ISSUE TITLE
Free Tokens

### ISSUE THREAD

**Issue by LonIsHere** [glixzzy/blooket-hack#485]
The free token is not working and every time I refresh the coins are still the same. It worked this morning but not its just not doing anything. Please fix so I can flex my legendary blooks to my friends LOL. (jk that last part was a joke).

**Comment by Greenlio** [comment]
From glizzers discord:

copy the code from the GitHub file as the fetch doesn’t work for addTokens

**Comment by bachhacker** [comment]
free tokens 100000
