### ISSUE TITLE
My school doesnt allow bookmarklets.

### ISSUE THREAD

**Issue by Adithr123** [glixzzy/blooket-hack#488]
What can i do?

**Comment by Greenlio** [comment]
Do you have access to console? (Ctrl + Shift + J) or (Ctrl + Shift + I)?

**Comment by Adithr123** [comment]
No, it's blocked

**Comment by GlizxyBoi** [comment]
> No, it's blocked

ooooooooooooooooof

**Comment by Greenlio** [comment]
Yeah, that's a giant yikes. Not many things we can do without either of those.

**Comment by Wizard-0** [comment]
If the code is in " javascript: ... " form then just type " javascript: [the code your using] " and hit enter

**Comment by GlizxyBoi** [comment]
yeah ik
