### ISSUE TITLE
Can you give me Write access because blizzard box is 20 coins not 25 coins

### ISSUE THREAD

**Issue by Liam-12** [glixzzy/blooket-hack#489]

**Comment by GlizxyBoi** [comment]
how do you know you cant buy anything yet

**Comment by Greenlio** [comment]
You probably won't get write access. Furthermore, we don't have anything on Blizzard Box yet, as it kind of isn't out. If you'd like, submit a pull request when it comes out tomorrow.

**Comment by GlizxyBoi** [comment]
k

**Comment by cvanga1382** [comment]
it is 25 coins

**Comment by 3kh0** [comment]
Can we close this @glixzzy, the blizzard box is 25 tokens

**Comment by 3kh0** [comment]
![image](https://user-images.githubusercontent.com/58097612/144442685-16ed2697-0593-488e-b764-4e9e76c28ef6.png)

**Comment by donaldli2020** [comment]
![image](https://user-images.githubusercontent.com/74021676/144693263-d0b73cd1-5349-4eb9-9457-e8d903d2cf2a.png)

**Comment by 3kh0** [comment]
> ![image](https://user-images.githubusercontent.com/74021676/144693263-d0b73cd1-5349-4eb9-9457-e8d903d2cf2a.png)

Nice photoshop skills

**Comment by donaldli2020** [comment]
lol

**Comment by donaldli2020** [comment]
> > ![image](https://user-images.githubusercontent.com/74021676/144693263-d0b73cd1-5349-4eb9-9457-e8d903d2cf2a.png)
> 
> Nice photoshop skills

lol
