### ISSUE TITLE
Spam open 

### ISSUE THREAD

**Issue by MumaPadres** [glixzzy/blooket-hack#492]
spam open blooket does not work properly
<img width="526" alt="Screen Shot 2021-11-30 at 9 04 31 AM" src="https://user-images.githubusercontent.com/95298611/144072222-8f228176-7eec-4786-81a1-30a454e1f7fd.png">
y

**Comment by GlizxyBoi** [comment]
omg one sec 
![image](https://user-images.githubusercontent.com/94561504/144097656-26f7497a-ab69-4042-a97b-687a162706bf.png)
do that then the command

**Comment by Greenlio** [comment]
#499

**Comment by glixzzy** [comment]
Fixed.
