### ISSUE TITLE
nothing at all works

### ISSUE THREAD

**Issue by vbpatel27** [glixzzy/blooket-hack#496]
none of the hacks work for me

**Comment by GlizxyBoi** [comment]
how explain ok send vid or screenshot something

**Comment by Greenlio** [comment]
Use Ctrl + Shift + J to see the error and screenshot it here using:
Gyazo,
Snipping Tool,
Snip & Sketch,
ShareX, 
etc.

**Comment by DarkTyrant22** [comment]
The way you are putting in the hack may not be the right way, depending on what platform you are using. Just saying.

**Comment by GlizxyBoi** [comment]
no

**Comment by glixzzy** [comment]
Elaborate.

**Comment by DarkTyrant22** [comment]
Depending on what you are using. Such as a Google device, like a Chrome Book. In that case the easiest and best way to apply the hacks is to copy the "hack" that you want such as the addcoins hack when playing towerdefence. You would then right click on the middle of the screen and choose Inspect (It should be at the bottom). When you click inspect the coding for the game pops up. You want to select console, which will be at the top of all the coding along with some other labels. You paste the copied hack there and click enter. When you click enter, you will be asked, "How much gold" or something along those lines. Type in the amount of gold you would like to receive and click next or ok. When that is done you will then have the amount of coins you put it. with some of the other hacks that are not for one of the game modes, you have to be on whatever it is you are trying to hack. Such as the 500 gold and XP. you have to be on your blooket account home page in order for it to successfully go through the process. But I digress, certain platforms are easier than others.

**Comment by GlizxyBoi** [comment]
ik i have done them before

**Comment by glixzzy** [comment]
fixed
