### ISSUE TITLE
Request?

### ISSUE THREAD

**Issue by resolvebeta** [glixzzy/blooket-hack#50]
If it is possible and you have time, some way to bypass the 500 daily limit. I understand that this takes you time, but I would be grateful if you could.
:)

**Comment by resolvebeta** [comment]
> Please @resolvebeta do not bother glixzzy im sure he is having some issues already

I have just said that when he has time, plus look at your last 3 issue posts

**Comment by BlooketLover** [comment]
Pls Do Not Start An Argument☺

**Comment by resolvebeta** [comment]
> Actually I am 12
![Screenshot 2021-10-07 4 30 47 PM](https://user-images.githubusercontent.com/92038282/136457712-339b1615-0d39-4b13-b2b3-81e4697184d6.png)
lol

**Comment by Minesraft2** [comment]
It’s not possible to bypass the daily limit, it’s managed server side

**Comment by resolvebeta** [comment]
> It’s not possible to bypass the daily limit, it’s managed server side

Thank you, for letting me know.
