### ISSUE TITLE
cant copy

### ISSUE THREAD

**Issue by HOGRIDAAAA** [glixzzy/blooket-hack#502]
I cant copy it with a button anymore i have to select all of it with my cursor and it takes 5 mins to copy all the code.

**Comment by glixzzy** [comment]
huh?

**Comment by donaldli2020** [comment]
Easy shortcut:
1. Open the file.
2. Scroll click "Raw."
3. Click on the popup tab.
4. Type Ctrl + A (means Select All).
5. You can copy now.

**Comment by donaldli2020** [comment]
It only takes 10 seconds. You may now close the issue.
