### ISSUE TITLE
Answer all correct is broken!

### ISSUE THREAD

**Issue by Brandon981026** [glixzzy/blooket-hack#509]
answer all correct hack is broken
i play crypto and it doesn't work for me
i hope you can fix it
thank you

**Comment by Greenlio** [comment]
duplicate, but it wouldn't work in crypto anyway

**Comment by Brandon981026** [comment]
it will work in crypto before
i hope you can fix it

**Comment by Greenlio** [comment]
it didn't work in crypto before ??

**Comment by 3kh0** [comment]
It had never worked in crypto. It only works in a few gamemodes.

**Comment by glixzzy** [comment]
fixed
