### ISSUE TITLE
box spam is not working

### ISSUE THREAD

**Issue by Gamehacker69** [glixzzy/blooket-hack#514]
hello i have tried box spam but it has not been working.

**Comment by Ihatr1** [comment]
Works for me.

What box are you opening?

**Comment by glixzzy** [comment]
how?

**Comment by 3kh0** [comment]
> hello i have tried box spam but it has not been working.

@Gamehacker69 what browser do you have? You need to be more clear

**Comment by Laduppong** [comment]
I cant

**Comment by 3kh0** [comment]
> I cant

so the box spam bookmarklet does not work for you either? What browser do you have? What are you trying? This information helps @glixzzy solve the problem. Please make sure you provide it!

**Comment by Gamehacker69** [comment]
so i was trying to use the unobfuscate script but now it works when i just use the obfuscated script

**Comment by 3kh0** [comment]
> so i was trying to use the unobfuscate script but now it works when i just use the obfuscated script

Ok, do not try to de-obfuscate the script, it breaks it and it will not work. Just use the premade bookmarklet.

**Comment by Laduppong** [comment]
i have goolge

**Comment by Laduppong** [comment]
and space box

**Comment by Laduppong** [comment]
Google my bad

**Comment by glixzzy** [comment]
fixed
