### ISSUE TITLE
Blizzard

### ISSUE THREAD

**Issue by GlizxyBoi** [glixzzy/blooket-hack#518]
wait if i did spam open boxes can i still get a chroma?

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
Yes

**Comment by 3kh0** [comment]
> wait if i did spam open boxes can i still get a chroma?

Wait what is a chroma?

**Comment by glixzzy** [comment]
yes

**Comment by GlizxyBoi** [comment]
fr if i do i can get a chroma

**Comment by GlizxyBoi** [comment]
fr tho can i????????????

**Comment by 3kh0** [comment]
> fr tho can i???????????? 

Yes you can if the odds are in your favor
