### ISSUE TITLE
Golden Gift

### ISSUE THREAD

**Issue by marfanis788** [glixzzy/blooket-hack#520]
Is it possible to add the Golden gift to the get all blooks script?

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
No it is not out and all blooks are server side and you can't hack the servers

**Comment by 3kh0** [comment]
> Is it possible to add the Golden gift to the get all blooks script?

The blook was not released and we can not add it yet. Sorry!

**Comment by glixzzy** [comment]
golden gift is not a real thing

**Comment by 3kh0** [comment]
> golden gift is not a real thing

I am so confused lol

**Comment by marfanis788** [comment]
It kind of is, just unimplemented as of now

**Comment by marfanis788** [comment]
But this hack will get so much better when the Potions of Pix'ahalia event happens. 250+ CHROMAS!!!
