### ISSUE TITLE
nvm

### ISSUE THREAD

**Issue by flipgore** [glixzzy/blooket-hack#525]

**Comment by glixzzy** [comment]
Re-word your issue.

**Comment by donaldli2020** [comment]
You must use it when waiting for host, not when viewing your Blook tab.

**Comment by flipgore** [comment]
> Re-word your issue.

nvm i didnt know it was used only for when ur in a game and not in the blooks u own

**Comment by 3kh0** [comment]
Can this be closed then?

**Comment by donaldli2020** [comment]
i think

**Comment by glixzzy** [comment]
fixed
