### ISSUE TITLE
Can you create a hack to circumvent the daily tokens limit

### ISSUE THREAD

**Issue by Undefineduser2** [glixzzy/blooket-hack#530]
It's annoying and I want like 9999999
sorry if it isn't possible

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
no it is server side sorry

**Comment by 3kh0** [comment]
^^^^^^^^^^^^^^

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
??????????????

**Comment by 3kh0** [comment]
No @Undefineduser2, 

You can not break the 500 daily tokens limit. It is all server-side and we can not change that. But maybe later we can do that! :)

**Comment by Greenlio** [comment]
impossible

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
No complete token hacking such as getting 999999999 is not possible the tokens are controlled by the servers
Maybe if you could hack into the servers than we could do that thank you and please close this😁
Ps stop making same issues over and over it is very annoying and time consuming to explain this to the people
Thank you for your request though😃😃😃
