### ISSUE TITLE
Add All Blooks Does Not Work

### ISSUE THREAD

**Issue by TomAdams2211** [glixzzy/blooket-hack#533]
WHen i do it (even on the page it tells me) it says "www.blooket.com says This cheat only works on the blook selecting page"

**Comment by BbyfoxY** [comment]
It only works when you are in the blook select screen of a blooket game

**Comment by TomAdams2211** [comment]
oh ok thanks man!

**Comment by Greenlio** [comment]
url should include ``/play/lobby``
