### ISSUE TITLE
is there a way to get all blookets permenently with a code

### ISSUE THREAD

**Issue by leonutana** [glixzzy/blooket-hack#535]
is there a way to get all blookets permenently with a code

@glixzzy

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
No all blooks perm is not possible all blooks are controlled by the servers
Maybe if you could hack into the servers than we could do that thank you and please close this thank you😁
We are sorry we cannot do this at the moment but please stop making the same issues over and over again
