### ISSUE TITLE
Missing the Code of Conduct in the root branch

### ISSUE THREAD

**Issue by FahimFBA** [glixzzy/blooket-hack#536]
Your project is currently missing an important item, the Code of Conduct in the root directory. Please consider adding that if you want. For your information, I can also submit a PR including that if you want.

Thank you!

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
Thonk you for your concern and we will look into this
Ps can we please close this

**Comment by glixzzy** [comment]
> Your project is currently missing an important item, the Code of Conduct in the root directory. Please consider adding that if you want. For your information, I can also submit a PR including that if you want.
> 
> Thank you!

Um, is it really needed? If so, yeah you can go ahead and make a PR, thanks appreciate it.

**Comment by 3kh0** [comment]
> > Your project is currently missing an important item, the Code of Conduct in the root directory. Please consider adding that if you want. For your information, I can also submit a PR including that if you want.
> > Thank you!
> 
> Um, is it really needed? If so, yeah you can go ahead and make a PR, thanks appreciate it.

We should also make issue templates while we are at it. So we do not always have to ask for more information.

**Comment by glixzzy** [comment]
> > > Your project is currently missing an important item, the Code of Conduct in the root directory. Please consider adding that if you want. For your information, I can also submit a PR including that if you want.
> > > Thank you!
> > 
> > 
> > Um, is it really needed? If so, yeah you can go ahead and make a PR, thanks appreciate it.
> 
> We should also make issue templates while we are at it. So we do not always have to ask for more information.

Sure, make a PR if you'd like.

**Comment by Greenlio** [comment]
ill make a pr

**Comment by Greenlio** [comment]
#539
