### ISSUE TITLE
hey can you make a hack that pertinently unlocks all the blookes

### ISSUE THREAD

**Issue by mrNoodleYT** [glixzzy/blooket-hack#537]
hey can you make a hack that pertinently unlocks all the blookes

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
No all blooks perm is not possible all blooks are controlled by the servers 
Maybe if you could hack into the servers than we could do that thank you and please close this thank you😁

**Comment by glixzzy** [comment]
not possible
