### ISSUE TITLE
is it possible to make a hack so that you could afk farm tower defence 

### ISSUE THREAD

**Issue by leonutana** [glixzzy/blooket-hack#538]
every time you go to a different tab on google tower defence pauses makeing it impossible to afk farm while still useing a different tab

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
Please re explain

**Comment by leonutana** [comment]
i want to be able to have tower defence running in the back round but it pauses if you arnt looking at the exact tab

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
Could be possible will look into it

**Comment by leonutana** [comment]
ok thank you

**Comment by glixzzy** [comment]
Yeah, that's possible but I don't really think it's needed for now unless others suggest the same.
