### ISSUE TITLE
Add Coins for tower of doom.

### ISSUE THREAD

**Issue by givemeusername199** [glixzzy/blooket-hack#540]
Add coins for  tower of doom is broken. I used the hack and then tried to select a character, it gave me 400 bad request. please look into this. I am on chrome OS so.

**Comment by Greenlio** [comment]
Duplicate.

**Comment by glixzzy** [comment]
huh it doesn't use requests?

**Comment by 3kh0** [comment]
It does work for me? werid

**Comment by CollynGaming** [comment]
get a windows computer or install windows on your crhome book

if you want help to install windows on I am free to help ya soon

**Comment by glixzzy** [comment]
fixed
