### ISSUE TITLE
Dose not work on iPad 

### ISSUE THREAD

**Issue by VIPKING-O1** [glixzzy/blooket-hack#544]
I tried using some of the hacks on iPad it says an error ocured
On chrome btw

**Comment by 3kh0** [comment]
Ok, so for iPad I do not know if it works I have not tested it yet but you need to make sure you add `javascript:` to the beginning for the code.

Let me know if that works!

**Comment by glixzzy** [comment]
> Ok, so for iPad I do not know if it works I have not tested it yet but you need to make sure you add `javascript:` to the beginning for the code.
> 
> 
> 
> Let me know if that works!

Mobile/iPads are not supported

**Comment by CollynGaming** [comment]
use a computer dude what are you doing on an ipad
