### ISSUE TITLE
what is the word i put first before the thing that copies in my clipboard

### ISSUE THREAD

**Issue by OverDrive11** [glixzzy/blooket-hack#546]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Envoirment (please complete the following information):**

 - OS: [e.g. ChromeOS]
 - Browser: [e.g. chrome, firefox]
 - Code type: [e.g. Bookmarklet or console]

**Additional context**

**Comment by Tuckerbutsmarter** [comment]
javascript:(Code goes here)
