### ISSUE TITLE
profit calculator in spamOpenBoxes

### ISSUE THREAD

**Issue by frogopu** [glixzzy/blooket-hack#548]
Something that shows the amount of profit you gain (in tokens) in the Results section of sellAllDupes. Could be useful for knowing how much you made without manual calculation.

**Comment by Nobody-720** [comment]
**smart boi**

**Comment by 3kh0** [comment]
This man is talking stonks

**Comment by donaldli2020** [comment]
maybe record the cash of before selling then subtract from after selling

**Comment by Greenlio** [comment]
very possible. will work on this eventually, added to todo list.

**Comment by edward-not** [comment]
Ok this is good, but we should definitely consider putting this on its flipside and making it a 'loss calculator', as 90% of the time we will lose money from 1 round of spam box opening assuming you sell all the blooks back. @Greenlio keep this is mind pls

**Comment by donaldli2020** [comment]
> Ok this is good, but we should definitely consider putting this on its flipside and making it a 'loss calculator', as 90% of the time we will lose money from 1 round of spam box opening assuming you sell all the blooks back. @Greenlio keep this is mind pls

if you do breakfast, there is 75 chance losing

**Comment by edward-not** [comment]
I am working on this. I have almost finished.

**Comment by edward-not** [comment]
Ok. I've finished, pull request submitted

**Comment by donaldli2020** [comment]
pls close

**Comment by donaldli2020** [comment]
solved #726

**Comment by edward-not** [comment]
@frogopu pls close

**Comment by frogopu** [comment]
Appreciated

**Comment by Nobody-720** [comment]
It won't work ;=;

**Comment by donaldli2020** [comment]
> It won't work ;=;

I can't replicate.

**Comment by edward-not** [comment]
> It won't work ;=;

In what way?
