### ISSUE TITLE
get all blooks is broken 

### ISSUE THREAD

**Issue by henrybay42** [glixzzy/blooket-hack#549]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Envoirment (please complete the following information):**

 - OS: [e.g. ChromeOS]
 - Browser: [e.g. chrome, firefox]
 - Code type: [e.g. Bookmarklet or console]

**Additional context**

**Comment by glixzzy** [comment]
no its not, and almsot the issue template isnt meant for copy pasting its a template.

**Comment by henrybay42** [comment]
I am sorry
