### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by donaldli2020** [glixzzy/blooket-hack#552]
**Is your feature request related to a problem? Please describe.**
It's annoying when people just post "issues" that are just comments.
**Describe the solution you'd like**
Open the discussions in settings.
**Describe alternatives you've considered**
Discord
**Additional context**

**Comment by glixzzy** [comment]
This isn't even a issue.

**Comment by donaldli2020** [comment]
I used the feature request template.

**Comment by donaldli2020** [comment]
Can we add a "Discussion" tab?
