### ISSUE TITLE
Can Yu CHange A Little For sellDupeBlook.js 

### ISSUE THREAD

**Issue by Nobody-720** [glixzzy/blooket-hack#554]
Can yu add like this things to sellDupeBlook.js

Yu have an options to not sell chromas, legendary, epic, rare, uncommon 

TQ i helps alot 

 Pls 👍

**Comment by XJSWAG** [comment]
I see purpose for chromas but not the rest

**Comment by Nobody-720** [comment]
**but its better to do it all right ?**

**Comment by Greenlio** [comment]
Not really.. but this would be possible (it would just take so much time)
