### ISSUE TITLE
tokens not working

### ISSUE THREAD

**Issue by jakhoff** [glixzzy/blooket-hack#561]
around 20 minutes ago i was trying to paste the add token cheat into the console but then i was shocked to see it was not working and when i looked at the issues tab it said it was patched

**Comment by AFunkyOrange** [comment]
YEAH M2

**Comment by jasdfasdf** [comment]
Guys I found how to do. If you go in this link and copy all the code and paste in console, it works. https://github.com/glixzzy/blooket-hack/blob/main/global/addTokens.js

**Comment by glixzzy** [comment]
fixed
