### ISSUE TITLE
Tower Defense - Change Round

### ISSUE THREAD

**Issue by Aquamarine110313** [glixzzy/blooket-hack#566]
whenever I use this it says "An error occured, would you like to report this in the support discord server?"  what do I do lol, and I don't have any more space for discord servers.  valid proof is attached.
<img width="432" alt="Screen Shot 2021-12-05 at 2 11 22 PM" src="https://user-images.githubusercontent.com/86901460/144760204-20c6cb82-e011-43ec-958d-02cf1790fab3.png">

**Comment by glixzzy** [comment]
works fine now.

**Comment by Aquamarine110313** [comment]
ok thanks
