### ISSUE TITLE
no chats work 

### ISSUE THREAD

**Issue by entityythehackerr** [glixzzy/blooket-hack#572]
i think blooket updated there website all the cheats are broken

**Comment by 3kh0** [comment]
Yes, 

There was an update to the site. Please re-add the hacks.

**Comment by BlooketHackerLoL** [comment]
re-add?

**Comment by 3kh0** [comment]
> re-add?

Are you using the bookmarklet or the paste into console method?

**Comment by entityythehackerr** [comment]
no im using bookmark
