### ISSUE TITLE
Please add more skins to the skin hack.

### ISSUE THREAD

**Issue by BannanaPants** [glixzzy/blooket-hack#581]
Please add these skins:
https://www.youtube.com/watch?v=i68QgH0FA44
https://www.youtube.com/watch?v=L3XLflj55H4
https://www.youtube.com/watch?v=L3XLflj55H4
https://www.youtube.com/watch?v=UztqfepQPyo
https://www.youtube.com/watch?v=0LghMlZssyk
https://www.youtube.com/watch?v=tL777VhawJU

**Comment by BannanaPants** [comment]
What do you mean select the skin?

**Comment by GitHubUserPy** [comment]
Are those even real?

**Comment by RayC123456** [comment]
I doubt these skins are real his videos have ratings and comments off.
(also his twitter is suspended)

**Comment by BannanaPants** [comment]
Oh, I'm sorry I bothered you, I'm gonna go report him now.
