### ISSUE TITLE
Get every answer correct

### ISSUE THREAD

**Issue by OffTHEWINNER** [glixzzy/blooket-hack#585]
How is this supposed to work I use it but I can still get stuff wrong

**Comment by glixzzy** [comment]
hmm what game mode?

**Comment by earhdev** [comment]
> How is this supposed to work I use it but I can still get stuff wrong

Only works in some gamemodes since this hack is trash

**Comment by 3kh0** [comment]
> > How is this supposed to work I use it but I can still get stuff wrong
> 
> Only works in some game modes since this hack is trash

If the hack is so bad then why don't you improve it?

**Comment by glixzzy** [comment]
works fin

https://user-images.githubusercontent.com/73669084/144957199-c4f566ec-483a-4fe8-9474-61b86c1902c1.mp4
