### ISSUE TITLE
Tower Defense’s Add Cash Script Encoding

### ISSUE THREAD

**Issue by TheGamer1002** [glixzzy/blooket-hack#589]
Hi there,

I am currently trying to decipher the cash add script for the Tower Defense mode. While testing my shortcut, it throws an error about a closing bracket. What is in the code is hard to decipher, so is there access to a raw version of the code?

Thanks!

**Comment by earhdev** [comment]
Skid!

**Comment by glixzzy** [comment]
Try again?

**Comment by glixzzy** [comment]
Are you in a tower defense game? is the url include: `/defense` ?

**Comment by TheGamer1002** [comment]
You betcha! I’m on a saved game if that makes any difference.

Upon further inspection, it appears it modifies the local storage tables? Correct me if I’m wrong.

**Comment by glixzzy** [comment]
Thats interesting cause when ever I try the getCash tower defense hack it always works?

**Comment by TheGamer1002** [comment]
My guess is that it's iOS exclusive.

**Comment by glixzzy** [comment]
> My guess is that it's iOS exclusive.

Yeah probably.

**Comment by donaldli2020** [comment]
> > My guess is that it's iOS exclusive.
> 
> Yeah probably.

i guess probably bc it's loaded from saved game but i'm unsure
