### ISSUE TITLE
Every Answer Correct

### ISSUE THREAD

**Issue by LeaderOfTheEvilFrenchGhostBlook** [glixzzy/blooket-hack#597]
It Is Broken

**Comment by glixzzy** [comment]
what game mode were you using the hack on?

**Comment by glixzzy** [comment]
Some game modes aren't supported like 2 of them aren't. Battle royale and classic. But it works.


https://user-images.githubusercontent.com/73669084/144957235-8f8c1a26-97ca-4435-b282-5bd7b47034be.mp4
