### ISSUE TITLE
Santa's Workshop

### ISSUE THREAD

**Issue by liftloplol** [glixzzy/blooket-hack#604]
Where is hack for Santa's Workshop?

**Comment by 3kh0** [comment]
It is still being worked on. Please wait.

**Comment by donaldli2020** [comment]
> It is still being worked on. Please wait.

and its out for plus only

**Comment by HahHeanKee** [comment]
ok, just use mine
email: m-11440239@moe-dl.edu.my
pass: Student@40360
Tip: do not log in to my google acc and I have set 2 step verication

**Comment by HahHeanKee** [comment]
> > It is still being worked on. Please wait.
> 
> and its out for plus only

ok, just use mine
email: m-11440239@moe-dl.edu.my
pass: Student@40360
Tip: do not log in to my google acc and I have set 2 step verication (Tommorow will be deleted the comment)

**Comment by Greenlio** [comment]
I don't think it's even underway. I don't even think we've considered that yet.

**Comment by KonoPowaD** [comment]
It is for everyone already

**Comment by hecker1234567890** [comment]
poggers

**Comment by KonoPowaD** [comment]
Did you have the hack now???

**Comment by wolfgoo** [comment]
i have

**Comment by wolfgoo** [comment]
Use multitool I also have used it to use Santa's Workshop hack.

on Gbazil find multitool copy and paste the multitool the bookmarklet and in blooket to use.

link:(https://www.gbasil.dev/blooket)

**Comment by wolfgoo** [comment]
?

**Comment by wolfgoo** [comment]
can't use?
