### ISSUE TITLE
AddTokens

### ISSUE THREAD

**Issue by P1uffy** [glixzzy/blooket-hack#606]
Using the addTokens hack doesn't work anymore and instead comes up with this in the console

VM80:1 Refused to connect to 'https://res.cloudinary.com/school-cheats/raw/upload/v1637452213/globalAddTokens.js' because it violates the following Content Security Policy directive: "connect-src 'self' https://api.blooket.com kit.fontawesome.com ka-f.fontawesome.com www.google-analytics.com www.googleapis.com firebase.googleapis.com firebaseinstallations.googleapis.com *.firebaseio.com wss://*.firebaseio.com securetoken.googleapis.com media.blooket.com api.cloudinary.com images.unsplash.com".

(anonymous) @ VM80:1

and 

Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by frogopu** [comment]
There was a recent blooket update, please update your script/replace your bookmarlet here https://github.com/glixzzy/blooket-hack

**Comment by 3kh0** [comment]
> Using the addTokens hack doesn't work anymore and instead comes up with this in the console
> 
> VM80:1 Refused to connect to 'https://res.cloudinary.com/school-cheats/raw/upload/v1637452213/globalAddTokens.js' because it violates the following Content Security Policy directive: "connect-src 'self' https://api.blooket.com kit.fontawesome.com ka-f.fontawesome.com [www.google-analytics.com](http://www.google-analytics.com) [www.googleapis.com](http://www.googleapis.com) firebase.googleapis.com firebaseinstallations.googleapis.com _.firebaseio.com wss://_.firebaseio.com securetoken.googleapis.com media.blooket.com api.cloudinary.com images.unsplash.com".
> 
> (anonymous) @ VM80:1
> 
> and
> 
> Failed to load resource: the server responded with a status of 401 (Unauthorized)

Please make sure you re-add the code

**Comment by glixzzy** [comment]
all the links were updated here: https://github.com/glixzzy/blooket-hack

**Comment by donaldli2020** [comment]
> Using the addTokens hack doesn't work anymore and instead comes up with this in the console
> 
> VM80:1 Refused to connect to 'https://res.cloudinary.com/school-cheats/raw/upload/v1637452213/globalAddTokens.js' because it violates the following Content Security Policy directive: "connect-src 'self' https://api.blooket.com kit.fontawesome.com ka-f.fontawesome.com [www.google-analytics.com](http://www.google-analytics.com) [www.googleapis.com](http://www.googleapis.com) firebase.googleapis.com firebaseinstallations.googleapis.com _.firebaseio.com wss://_.firebaseio.com securetoken.googleapis.com media.blooket.com api.cloudinary.com images.unsplash.com".
> 
> (anonymous) @ VM80:1
> 
> and
> 
> Failed to load resource: the server responded with a status of 401 (Unauthorized)

unauthorized? make sure you're signed in
