### ISSUE TITLE
Icons Switch

### ISSUE THREAD

**Issue by Super379ss** [glixzzy/blooket-hack#610]
The icons keep switching to other gamemodes. If this happens on even ONE of them, then it will not work at all, and you have to refresh the page until it works.
![image](https://user-images.githubusercontent.com/95702383/145070880-46cbb266-05e4-480d-bc7a-ffa0a864981d.png)

**Comment by TheGamer1002** [comment]
Can confirm. iOS 15

**Comment by 3kh0** [comment]
> The icons keep switching to other gamemodes. If this happens on even ONE of them, then it will not work at all, and you have to refresh the page until it works. ![image](https://user-images.githubusercontent.com/95702383/145070880-46cbb266-05e4-480d-bc7a-ffa0a864981d.png)

Just use the codes listed here: https://github.com/glixzzy/blooket-hack

**Comment by donaldli2020** [comment]
i can replicate

**Comment by varedz** [comment]
School Cheats icon bug has been fixed.
