### ISSUE TITLE
Add new feature

### ISSUE THREAD

**Issue by MYNAMEISUHIDK21** [glixzzy/blooket-hack#614]
I have a suggestion for a new hack. if its possible can u change the add tokens to go threw daily limit. i also have another one. can you make a battle royal hack that lets you automatically win and drain peoples energy.

**Comment by donaldli2020** [comment]
> I have a suggestion for a new hack. if its possible can u change the add tokens to go threw daily limit. i also have another one. can you make a battle royal hack that lets you automatically win and drain peoples energy.

there is a hard limit on tokens, its really annoying
