### ISSUE TITLE
Limited Time

### ISSUE THREAD

**Issue by marfanis788** [glixzzy/blooket-hack#624]
Could you add a script that gives you plus and limited time gamemodes no matter what?

**Comment by ZackiBoiz** [comment]
Yo, thats a great idea!

**Comment by ilikecatss** [comment]
might not be possible

**Comment by gimmy74** [comment]
okrs script had it before he stopped working on the script

**Comment by Bacon-boi** [comment]
pog

**Comment by hecker1234567890** [comment]
lmao that would be poggers, but how would that work?

**Comment by wolfgoo** [comment]
ask glixzzy

**Comment by marfanis788** [comment]
how, didn't posting it in issues do that?
________________________________

**Comment by gIixzzy** [comment]
glixzzy's got this
