### ISSUE TITLE
Only Certain hacks Work

### ISSUE THREAD

**Issue by Whiskqr** [glixzzy/blooket-hack#628]
only the add tokens, spam open boxes, and sell dupes work. I can get them to work on my PC, but on iPad, only they work. Some other codes by other devs also work. I think it might be only the hacks that have multiple lines of code, but idk. No errors pop up, but when they dont work it says JavaScript has been completed, and nothing happens.

**Comment by Whiskqr** [comment]
I’m using it through shortcuts

**Comment by 3kh0** [comment]
These hacks do not fully work on iPad. They should only work on PC

**Comment by glixzzy** [comment]
This hack isn't supported for iPad/mobile
