### ISSUE TITLE
Auto Box Opener Sometimes allows you uto go in negetives if you open too much with laggy wifi

### ISSUE THREAD

**Issue by VerifiedPerson** [glixzzy/blooket-hack#632]
<img width="1440" alt="Screen Shot 2021-12-08 at 2 01 51 PM" src="https://user-images.githubusercontent.com/93888954/145268673-93058b7b-369d-475b-a0ef-f6ec27de0f0a.png">

**Comment by glixzzy** [comment]
no? lol

**Comment by donaldli2020** [comment]
lol

**Comment by VerifiedPerson** [comment]
> no? lol

Yes I can show you on a vc or somthing.

**Comment by VerifiedPerson** [comment]
> ![image](https://user-images.githubusercontent.com/74021676/145315325-98a538ba-7994-4cc6-a2a0-e30c56133832.png)

but u inspected that..

**Comment by donaldli2020** [comment]
> > ![image](https://user-images.githubusercontent.com/74021676/145315325-98a538ba-7994-4cc6-a2a0-e30c56133832.png)
> 
> but u inspected that..

i just decreased the interval and typed a huge number
