### ISSUE TITLE
Wont let me click

### ISSUE THREAD

**Issue by BlooketHeck** [glixzzy/blooket-hack#636]
On schoolcheats.net/blooket im trying to click on global scripts and it does nothing

**Comment by glixzzy** [comment]
get the bookmarklets from here https://github.com/glixzzy/blooket-hack

**Comment by donaldli2020** [comment]
working

**Comment by donaldli2020** [comment]
btw spam boxes is awesome spammed 100 of each blizzard and space got 
![image](https://user-images.githubusercontent.com/74021676/145304963-fd5471c3-fb0f-468a-b03b-ef1c0f270ea9.png)
![image](https://user-images.githubusercontent.com/74021676/145304976-d93731cb-1646-4861-868b-2e570fcd9a3b.png)
