### ISSUE TITLE
The hacks work, but not  on my school computer

### ISSUE THREAD

**Issue by JorMama3** [glixzzy/blooket-hack#644]
My school mustve blocked blooket hacks

**Comment by glixzzy** [comment]
no they didn't get the bookmarklets from here https://github.com/glixzzy/blooket-hack

**Comment by donaldli2020** [comment]
don't use the console

**Comment by donaldli2020** [comment]
if it's blocked

**Comment by donaldli2020** [comment]
https://user-images.githubusercontent.com/73669084/142779206-6cef86be-b2a5-4958-8637-cb6bde2a42da.mp4
