### ISSUE TITLE
All hacks are down

### ISSUE THREAD

**Issue by ZzBladeMoonzZ** [glixzzy/blooket-hack#648]
Got on at 6:57 am est to find the hacks not working, please fix them when possible.

**Comment by BlooketHacks123** [comment]
Yes plz, this happens a lot and its very unexpecting

**Comment by Cookie-Carky** [comment]
me too
none of the hacks work

**Comment by Cookie-Carky** [comment]
the addTokens say 404 Not found

**Comment by varedz** [comment]
Updated code is on https://schoolcheats.net/blooket/ Firebase Database was deleted rendering the old scripts to be useless.
