### ISSUE TITLE
Someone stealing the hacks

### ISSUE THREAD

**Issue by 3kh0** [glixzzy/blooket-hack#657]
I found this person just stealing the codes and updating the codes when it breaks. 

There is no links or mention of the original source ( this repo ) 

Here is the repo: [`https://github.com/yesskiable/blooket`](https://github.com/yesskiable/blooket)

![image](https://user-images.githubusercontent.com/58097612/145426308-6769fcae-d50a-4f9d-87fa-7d43cb0200fd.png)

![image](https://user-images.githubusercontent.com/58097612/145426351-7d4bd92d-4098-4d37-a517-45384d443fd6.png)

**Comment by Greenlio** [comment]
Literally everyone does this. I don't think anyone cares.

**Comment by varedz** [comment]
None of these are functional, doesn’t matter.
