### ISSUE TITLE
Add tokens

### ISSUE THREAD

**Issue by Hacker1000000** [glixzzy/blooket-hack#658]
Can you fix the hack for add tokens it isn't working for me?

**Comment by 3kh0** [comment]
It works for me, what are you doing?

**Comment by Hacker1000000** [comment]
I type javascript: and put the code there and it doesn't pop up how many coins you want to sign. I haven't gone over 500 and also I have been opening new blookets and it still doesn't work.

**Comment by Laduppong** [comment]
same

**Comment by Greenlio** [comment]
Yes, the hacks here don't work.
Try here:
https://schoolcheats.net/blooket
https://schoolcheats.pages.dev/blooket

**Comment by Hacker1000000** [comment]
Hey can you fix the hack

**Comment by varedz** [comment]
Updated code is on https://schoolcheats.net/blooket/ Firebase Database was deleted rendering the old scripts to be useless.
