### ISSUE TITLE
hsc brokrn

### ISSUE THREAD

**Issue by psspdfkgmfbd** [glixzzy/blooket-hack#659]
hacls are nbroken i am vusing chromebook and the bookmark;ets but it not working pls help

**Comment by psspdfkgmfbd** [comment]
i mean when i use chromebook and school wifi and inspect is blocked so i use the bookmarks but it not work pls help me pLsSSSSSSSSSSSSSSsLSSSS  i jidt wsanr tohack blookt ZPZLS

**Comment by Greenlio** [comment]
Yes, the hacks here don't work.
Try here:
https://schoolcheats.net/blooket
https://schoolcheats.pages.dev/blooket

**Comment by varedz** [comment]
Updated code is on https://schoolcheats.net/blooket/ Firebase Database was deleted rendering the old scripts to be useless.
