### ISSUE TITLE
hacks are no work using boooMARK

### ISSUE THREAD

**Issue by psspdfkgmfbd** [glixzzy/blooket-hack#660]
**_

- [ ] ### 1. > pls im in chromebook on scoool wifi and inspect is blocked so i use the bookmarklet and i do exactly as it says but still no working i EVEN SHUT DOWN MY BOOK NO WORKING

_**

**Comment by Greenlio** [comment]
Yes, the hacks here don't work.
Try here:
https://schoolcheats.net/blooket
https://schoolcheats.pages.dev/blooket

**Comment by psspdfkgmfbd** [comment]
> Yes, the hacks here don't work. Try here: https://schoolcheats.net/blooket https://schoolcheats.pages.dev/blooket

these working without console?

**Comment by Greenlio** [comment]
Go to that website, press the cheat you want, and paste it into console.

**Comment by cottoish** [comment]
> Go to that website, press the cheat you want, and paste it into console.

I tried that but it the links on the website did not work. Do you know why?

**Comment by varedz** [comment]
Updated code is on https://schoolcheats.net/blooket/ Firebase Database was deleted rendering the old scripts to be useless.

**Comment by cottoish** [comment]
> Updated code is on https://schoolcheats.net/blooket/ Firebase Database was deleted rendering the old scripts to be useless.

I know the ones here don't work it's the ones on the other website.
