### ISSUE TITLE
Add tokens not working

### ISSUE THREAD

**Issue by Laduppong** [glixzzy/blooket-hack#661]

**Comment by XxwolfsisxXYT** [comment]
No hacks are working right now

**Comment by LILHOLLOW** [comment]
there is a pinned comment. ¨All hacks are broken¨

**Comment by varedz** [comment]
Updated code is on https://schoolcheats.net/blooket/ Firebase Database was deleted rendering the old scripts to be useless.

**Comment by Davisredmond** [comment]
> Updated code is on https://schoolcheats.net/blooket/ Firebase Database was deleted rendering the old scripts to be useless.

is there an other place with add tokens
