### ISSUE TITLE
blooket patched the scripts

### ISSUE THREAD

**Issue by Telantix** [glixzzy/blooket-hack#665]
it got patched

**Comment by michael50376** [comment]
yep :P

**Comment by 7727259314** [comment]
yeah nothing is working

**Comment by 7727259314** [comment]
I figured it out, the updated & working versions of the codes are at [https://schoolcheats.net/blooket/](url). If this site is blocked for you, use a web proxy like [https://analystinn.net/](url)

**Comment by Telantix** [comment]
URL for the web proxy doesnt turn anything up

**Comment by glixzzy** [comment]
Its fixed go to https://schoolcheats.net/blooket for the new scripts
