### ISSUE TITLE
Nothing Working

### ISSUE THREAD

**Issue by Glizzysplease** [glixzzy/blooket-hack#667]
At the start of this week the hacks have stopped working just wanted to let people know!

**Comment by 7727259314** [comment]
I figured it out, the updated & working versions of the codes are at https://schoolcheats.net/blooket/. If this site is blocked for you, use a web proxy like https://analystinn.net/

**Comment by glixzzy** [comment]
Its fixed go to https://schoolcheats.net/blooket for the new scripts
