### ISSUE TITLE
blooket

### ISSUE THREAD

**Issue by mohammad126** [glixzzy/blooket-hack#668]
blooket hack started not working today i think blooket  has new csp or a blocker

**Comment by 7727259314** [comment]
I figured it out, the updated & working versions of the codes are at https://schoolcheats.net/blooket/. If this site is blocked for you, use a web proxy like https://analystinn.net/

**Comment by glixzzy** [comment]
Its fixed go to https://schoolcheats.net/blooket for the new scripts
