### ISSUE TITLE
Battle Royale (Correct Answers)

### ISSUE THREAD

**Issue by gIixzzy** [glixzzy/blooket-hack#671]
Hello, as you can tell by the subject of this comment/issue I was wondering if you could either make scripts for Battle Royale or have your getEveryAnswerCorrect.js include Battle Royale.
![Screenshot 2021-12-09 1 20 16 PM](https://user-images.githubusercontent.com/94643594/145461911-ef19e164-132e-44da-8a62-620e8a92054e.png)
-FieryHorizon

**Comment by glixzzy** [comment]
not possible
