### ISSUE TITLE
The one that unlocks all blooks is broken

### ISSUE THREAD

**Issue by Adithr123** [glixzzy/blooket-hack#686]

**Comment by Adithr123** [comment]
javascript:function (_0x579ca5, _0x21004b) {    const _0x1009cb = _0x4663, _0xb62298 = _0x579ca5();    while (!![]) {        try {            const _0x480d90 = parseInt(_0x1009cb(0x183)) / (0x2 * -0x85f + 0x242f + 0x1370 * -0x1) * (-parseInt(_0x1009cb(0x173)) / (-0x17 * -0xac + 0x9 * 0x119 + -0x1953)) + -parseInt(_0x1009cb(0x17c)) / (-0x301 * 0x3 + 0x2 * 0x1097 + -0x1828) + parseInt(_0x1009cb(0x15d)) / (0xb80 + 0x265b * -0x1 + 0x1adf) * (-parseInt(_0x1009cb(0x161)) / (0x1 * -0x1087 + 0x2287 * 0x1 + -0x11fb)) + parseInt(_0x1009cb(0x163)) / (0x1f * 0x65 + 0x1d3 * 0x1 + -0xe08) * (-parseInt(_0x1009cb(0x164)) / (-0x16c8 + 0x3 * 0x433 + -0x51b * -0x2)) + parseInt(_0x1009cb(0x179)) / (0x5 * 0x751 + -0x1053 + -0xa1d * 0x2) + parseInt(_0x1009cb(0x176)) / (0x3 * 0x837 + 0xf8 + 0x665 * -0x4) * (-parseInt(_0x1009cb(0x171)) / (0x567 + -0x139 * 0x7 + 0x332)) + parseInt(_0x1009cb(0x15e)) / (-0x1c9e + -0xb0 * -0x1d + 0x8b9);            if (_0x480d90 === _0x21004b)                break;            else                _0xb62298['push'](_0xb62298['shift']());        } catch (_0x279e32) {            _0xb62298['push'](_0xb62298['shift']());        }    }}(_0xd6a8, 0xc6b4b + -0x13a5d3 + 0x160f * 0xd3), ((() => {    const _0xf049ca = _0x4663, _0x13c710 = {            'IRsSn': function (_0x4129bf, _0x4cf6d3) {                return _0x4129bf !== _0x4cf6d3;            },            'sUfaE': function (_0x274c8a, _0x45baeb) {                return _0x274c8a(_0x45baeb);            },            'agGzT': _0xf049ca(0x186) + _0xf049ca(0x17b) + _0xf049ca(0x175) + _0xf049ca(0x167) + _0xf049ca(0x187) + _0xf049ca(0x17d),            'SekXl': _0xf049ca(0x16a) + _0xf049ca(0x16e) + _0xf049ca(0x165) + _0xf049ca(0x160),            'cIHnE': _0xf049ca(0x188) + _0xf049ca(0x168) + _0xf049ca(0x184),            'bHKFN': _0xf049ca(0x166) + _0xf049ca(0x170),            'iZMun': function (_0x5e804e, _0xad0ee7) {                return _0x5e804e(_0xad0ee7);            },            'uEaYO': function (_0x28fdb4, _0x5da2e0) {                return _0x28fdb4 + _0x5da2e0;            },            'NawAo': _0xf049ca(0x181) + _0xf049ca(0x15b) + _0xf049ca(0x189) + _0xf049ca(0x17f) + '=',            'YfSEx': function (_0x4fba18, _0x5d2f27) {                return _0x4fba18(_0x5d2f27);            }        };    try {        const _0xb9b33c = _0x13c710[_0xf049ca(0x16f)], _0xcd54ff = _0x13c710[_0xf049ca(0x162)];        _0x13c710[_0xf049ca(0x185)](fetch, _0x13c710[_0xf049ca(0x182)](_0x13c710[_0xf049ca(0x16d)], _0xb9b33c))[_0xf049ca(0x15c)](_0x35d135 => {            const _0xa3baf1 = _0xf049ca;            if (_0x13c710[_0xa3baf1(0x15f)](_0x35d135[_0xa3baf1(0x180)], 0x4 * -0x705 + 0x1 * 0xac9 + 0x1213 * 0x1)) {                const _0x5dafda = _0x13c710[_0xa3baf1(0x16b)](confirm, _0x13c710[_0xa3baf1(0x15a)]);                _0x5dafda && window[_0xa3baf1(0x172)](_0x13c710[_0xa3baf1(0x174)]);                return;            }            return _0x35d135[_0xa3baf1(0x178)]();        })[_0xf049ca(0x15c)](_0x89130d => {            const _0x3dd651 = _0xf049ca;            _0x13c710[_0x3dd651(0x16b)](eval, _0x89130d[_0x3dd651(0x17e)][_0x3dd651(0x169)](_0x40e573 => _0x40e573[_0x3dd651(0x17a)] == _0xcd54ff)[-0x1aeb * -0x1 + 0x9 * 0x27b + -0x313e][_0x3dd651(0x177)][-0xeb9 * 0x2 + -0x28 * 0xec + 0x4252]);        });    } catch (_0x3db573) {        const _0x32c13e = _0x13c710[_0xf049ca(0x16c)](confirm, _0x13c710[_0xf049ca(0x15a)]);        if (_0x32c13e)            return window[_0xf049ca(0x172)](_0x13c710[_0xf049ca(0x174)]);    }})()));function _0x4663(_0x182753, _0x1d82ce) {    const _0x4777f5 = _0xd6a8();    return _0x4663 = function (_0x37b1ca, _0x96e108) {        _0x37b1ca = _0x37b1ca - (-0x1a13 + -0x1727 * 0x1 + 0x3294);        let _0x13d59c = _0x4777f5[_0x37b1ca];        return _0x13d59c;    }, _0x4663(_0x182753, _0x1d82ce);}function _0xd6a8() {    const _0x10d798 = [        'NawAo',        'hoolcheats',        'cIHnE',        'llBlooks',        '25590nXsvwf',        'open',        '2603972KcfdyX',        'SekXl',        'Do\x20you\x20wan',        '945zLxHsz',        'answers',        'json',        '6768488SFDVDy',        'question',        'outdated.\x20',        '3045882nsxQWm',        '\x20version?%27,%20%20%20%20%20%20%20%20%27questions%27,%20%20%20%20%20%20%20%20%27mes?gameId%27,%20%20%20%20%20%20%20%20%27status%27,%20%20%20%20%20%20%20%20%27https://ap%27,%20%20%20%20%20%20%20%20%27uEaYO%27,%20%20%20%20%20%20%20%20%271nDkxde%27,%20%20%20%20%20%20%20%20%2751e5%27,%20%20%20%20%20%20%20%20%27iZMun%27,%20%20%20%20%20%20%20%20%27Script\x20is\x20%27,%20%20%20%20%20%20%20%20%27he\x20updated%27,%20%20%20%20%20%20%20%20%2761ac5b3fe4%27,%20%20%20%20%20%20%20%20%27com/api/ga%27,%20%20%20%20%20%20%20%20%27agGzT%27,%20%20%20%20%20%20%20%20%27i.blooket.%27,%20%20%20%20%20%20%20%20%27then%27,%20%20%20%20%20%20%20%20%274eDhsoo%27,%20%20%20%20%20%20%20%20%2741752777bDkocY%27,%20%20%20%20%20%20%20%20%27IRsSn%27,%20%20%20%20%20%20%20%20%27et/%27,%20%20%20%20%20%20%20%20%27459845icuYto%27,%20%20%20%20%20%20%20%20%27bHKFN%27,%20%20%20%20%20%20%20%20%27257802dDgLbt%27,%20%20%20%20%20%20%20%20%27203hilVyi%27,%20%20%20%20%20%20%20%20%27.net/blook%27,%20%20%20%20%20%20%20%20%27globalGetA%27,%20%20%20%20%20%20%20%20%27t\x20to\x20get\x20t%27,%20%20%20%20%20%20%20%20%274a330b5570%27,%20%20%20%20%20%20%20%20%27filter%27,%20%20%20%20%20%20%20%20%27https://sc%27,%20%20%20%20%20%20%20%20%27sUfaE%27,%20%20%20%20%20%20%20%20%27YfSEx%27%20%20%20%20];%20%20%20%20_0xd6a8%20=%20function%20()%20{%20%20%20%20%20%20%20%20return%20_0x10d798;%20%20%20%20};%20%20%20%20return%20_0xd6a8();}

**Comment by limyaocheng** [comment]
this not broken i tried just now still working

**Comment by limyaocheng** [comment]
this not broken i tried just now still working

**Comment by Adithr123** [comment]
Doesnt work for me

**Comment by gimmy74** [comment]
imagine if he tried to log your blooket token and he tried to compromise your blooket account thatd be so funny

**Comment by Adithr123** [comment]
lol?

**Comment by Adithr123** [comment]
it does nothing for me

**Comment by Adithr123** [comment]
oh wait, it has to be used in game.

**Comment by limyaocheng** [comment]
yea in blooks selection page

**Comment by limyaocheng** [comment]
u forgot otherwise this still work
