### ISSUE TITLE
ISsue with new fetch

### ISSUE THREAD

**Issue by ZiteDesigns** [glixzzy/blooket-hack#691]
The school i go to has blocked this site can we get the fetch like before

**Comment by BlooketHacks123** [comment]
Idk if that works anymore

**Comment by 3kh0** [comment]
@glixzzy moving all of the hacks over to schoolcheats.net seems to be causing a lot of problems, it there a way we can re-add it back to the README in the folders? It seams to work better that way

**Comment by varedz** [comment]
> @glixzzy moving all of the hacks over to schoolcheats.net seems to be causing a lot of problems, it there a way we can re-add it back to the README in the folders? It seams to work better that way

48,424 uses yesterday : 5 issues ratio

**Comment by littlekevinandtheboys** [comment]
bro literally go to global or whatever you want and click the hacks themselves and you can copy it, like instead of scrolling or clicking the readme click into the hacks themselves

**Comment by littlekevinandtheboys** [comment]
@ZiteDesigns https://schoolcheats.pages.dev/blooket/

**Comment by Leonelleon7700** [comment]
My school doesn't allow to use inspect element and they blocked schoocheats and the only thing that worked is the fetch commands
