### ISSUE TITLE
School Cheats are not working

### ISSUE THREAD

**Issue by ElijahT170** [glixzzy/blooket-hack#694]
My school Chromebook blokes School Cheats

**Comment by ElijahT170** [comment]
is there away that u can do javascripts agin

**Comment by littlekevinandtheboys** [comment]
bro literally go to global or whatever you want and click the hacks themselves and you can copy it, like instead of scrolling or clicking the readme click into the hacks themselves

**Comment by littlekevinandtheboys** [comment]
nvm here: [](https://schoolcheats.pages.dev/blooket/)

**Comment by littlekevinandtheboys** [comment]
https://schoolcheats.pages.dev/blooket/

**Comment by ElijahT170** [comment]
it blocks it
