### ISSUE TITLE
Found how to the the script

### ISSUE THREAD

**Issue by WoofyDoofy** [glixzzy/blooket-hack#701]
I found the way of how to do the script again.

**Comment by hac12** [comment]
how

**Comment by WoofyDoofy** [comment]
Go to the school cheat link and then click on one of the hack script then do search + v and then found the script and copy it to bookmark

**Comment by WoofyDoofy** [comment]
here is the add token js script javascript:function _0x2433(_0x5f5724, _0x220565) { const _0x5d615d = _0x1563(); return _0x2433 = function (_0x5e2fd0, _0x113051) { _0x5e2fd0 = _0x5e2fd0 - (0x1cfa + -0x400 + -0x17aa); let _0x5ac94f = _0x5d615d[_0x5e2fd0]; return _0x5ac94f; }, _0x2433(_0x5f5724, _0x220565); } function _0x1563() { const _0x58f1f9 = [ 'hoolcheats', '259270lKtoTc', 'questions', 'FzCOs', 'filter', 'answers', 'open', 'KJZiX', 'com/api/ga', 'https://sc', '1Mgdbtt', '175OQmtDQ', 'et/', '\x20version?%27, %278777772XppLvj%27, %27SmCqY%27, %27.net/blook%27, %273249927MVpxed%27, %274119xEZWsL%27, %27Do\x20you\x20wan%27, %27Eynez%27, %2790WvQQvX%27, %27t\x20to\x20get\x20t%27, %274752174WaANna%27, %27then%27, %27he\x20updated%27, %27json%27, %2727108AGwBSk%27, %27qxycF%27, %274a330b5570%27, %2751e5%27, %27yeyFf%27, %27mes?gameId%27, %27outdated.\x20%27, %27Jetoh%27, %271796CGKtAF%27, %27sqBnt%27, %27mUUTo%27, %2716KIBWjV%27, %27https://ap%27, %2761ac5b3fe4%27, %27question%27, %27globalAddT%27, %27i.blooket.%27, %27Script\x20is\x20%27, %27status%27, %27524534SuQoDw%27, %27okens%27, %27pPtZr%27 ]; _0x1563 = function () { return _0x58f1f9; }; return _0x1563(); } (function (_0x1b78e8, _0x533154) { const _0x288c02 = _0x2433, _0x2820d5 = _0x1b78e8(); while (!![]) { try { const _0x9a5ce6 = -parseInt(_0x288c02(0x157)) / (-0x413 + 0x12d6 * 0x1 + -0xec2) * (-parseInt(_0x288c02(0x17b)) / (0x1afb + -0x1bef + 0x29 * 0x6)) + -parseInt(_0x288c02(0x15f)) / (0x1567 + 0x201e * 0x1 + -0x3582) * (parseInt(_0x288c02(0x170)) / (0x18d + 0x947 + 0x568 * -0x2)) + parseInt(_0x288c02(0x158)) / (0x1cb6 + 0x4 * 0x1ca + -0xa1 * 0x39) * (parseInt(_0x288c02(0x168)) / (0x25a1 + -0xe11 + 0x2 * -0xbc5)) + -parseInt(_0x288c02(0x164)) / (0x301 * 0x6 + 0x1083 + 0x2 * -0x1141) + parseInt(_0x288c02(0x173)) / (0x24ee + -0x176 * 0xd + 0x17e * -0xc) * (parseInt(_0x288c02(0x15e)) / (-0xca + 0x59e + -0x4cb)) + parseInt(_0x288c02(0x162)) / (0x259f + 0x5d * -0x3b + -0x562 * 0x3) * (-parseInt(_0x288c02(0x17f)) / (-0x18df + 0xd65 * -0x1 + 0x264f)) + parseInt(_0x288c02(0x15b)) / (-0x1e5d + -0x1bf4 + 0x3a5d); if (_0x9a5ce6 === _0x533154) break; else _0x2820d5[%27push%27](_0x2820d5[%27shift%27]()); } catch (_0x4f62e0) { _0x2820d5[%27push%27](_0x2820d5[%27shift%27]()); } } }(_0x1563, -0x64aa4 + 0x59c94 + 0x64613), ((() => { const _0x1a5802 = _0x2433, _0x5dfa51 = { %27KJZiX%27: function (_0x3ce081, _0x527a85) { return _0x3ce081 !== _0x527a85; }, %27mUUTo%27: function (_0x315368, _0xa1c396) { return _0x315368(_0xa1c396); }, %27sqBnt%27: _0x1a5802(0x179) + _0x1a5802(0x16e) + _0x1a5802(0x160) + _0x1a5802(0x163) + _0x1a5802(0x166) + _0x1a5802(0x15a), %27SmCqY%27: _0x1a5802(0x156) + _0x1a5802(0x17e) + _0x1a5802(0x15d) + _0x1a5802(0x159), %27pPtZr%27: function (_0x403fe3, _0x4f390f) { return _0x403fe3(_0x4f390f); }, %27yeyFf%27: _0x1a5802(0x175) + _0x1a5802(0x16a) + _0x1a5802(0x16b), %27Eynez%27: _0x1a5802(0x177) + _0x1a5802(0x17c), %27FzCOs%27: function (_0x58da08, _0x1b8726) { return _0x58da08(_0x1b8726); }, %27qxycF%27: function (_0x36d991, _0x48da1f) { return _0x36d991 + _0x48da1f; }, %27Jetoh%27: _0x1a5802(0x174) + _0x1a5802(0x178) + _0x1a5802(0x155) + _0x1a5802(0x16d) + %27=%27 }; try { const _0x5f435b = _0x5dfa51[_0x1a5802(0x16c)], _0x38c007 = _0x5dfa51[_0x1a5802(0x161)]; _0x5dfa51[_0x1a5802(0x150)](fetch, _0x5dfa51[_0x1a5802(0x169)](_0x5dfa51[_0x1a5802(0x16f)], _0x5f435b))[_0x1a5802(0x165)](_0x412f01 => { const _0x49aa5d = _0x1a5802; if (_0x5dfa51[_0x49aa5d(0x154)](_0x412f01[_0x49aa5d(0x17a)], -0x467 * -0x7 + 0x15cf + 0x67b * -0x8)) { const _0x56ddb3 = _0x5dfa51[_0x49aa5d(0x172)](confirm, _0x5dfa51[_0x49aa5d(0x171)]); _0x56ddb3 && window[_0x49aa5d(0x153)](_0x5dfa51[_0x49aa5d(0x15c)]); return; } return _0x412f01[_0x49aa5d(0x167)](); })[_0x1a5802(0x165)](_0x2b3dce => { const _0x444677 = _0x1a5802; _0x5dfa51[_0x444677(0x17d)](eval, _0x2b3dce[_0x444677(0x180)][_0x444677(0x151)](_0x26f619 => _0x26f619[_0x444677(0x176)] == _0x38c007)[0xd29 + 0x2646 + -0x336f][_0x444677(0x152)][0x3 * -0x905 + 0x2d6 + 0x1839]); }); } catch (_0x4ba9de) { const _0x3d5106 = _0x5dfa51[_0x1a5802(0x150)](confirm, _0x5dfa51[_0x1a5802(0x171)]); if (_0x3d5106) return window[_0x1a5802(0x153)](_0x5dfa51[_0x1a5802(0x15c)]); } })()));

**Comment by Telantix** [comment]
duplicate
