### ISSUE TITLE
New coin limit 

### ISSUE THREAD

**Issue by gizzyx69** [glixzzy/blooket-hack#712]
i think if we make a new coin limit it could get us red asoturnots left and right

**Comment by edward-not** [comment]
I'm sure that answering this question isn't really worth glixzzy's time. There is simply no possible way to bypass the 500-coin limit. It is managed by Blooket's servers, so unless we pull off some Oceans 12 style bullshit that's just impossible. Please don't clog up the **Issues** section with this type of stuff.

**Comment by varedz** [comment]
Not possible.
