### ISSUE TITLE
[Bug] buttons

### ISSUE THREAD

**Issue by GodlyGavin1** [glixzzy/blooket-hack#722]
**None** of the buttons work.

**Comment by GodlyGavin1** [comment]
Sorry, none of the buttons for the blooket work is what I meant to say.

**Comment by donaldli2020** [comment]
https://github.com/glixzzy/blooket-hack

**Comment by donaldli2020** [comment]
use the github ones if they don't work

**Comment by glixzzy** [comment]
they work.
