### ISSUE TITLE
too many requests in pop

### ISSUE THREAD

**Issue by donaldli2020** [glixzzy/blooket-hack#723]
![image](https://user-images.githubusercontent.com/74021676/145695255-59fdc691-cbe4-4141-92fd-e6030f94efe9.png)

**Comment by GodlyGavin1** [comment]
E?

**Comment by 3kh0** [comment]
Go to the main site, https://www.benstewartyt.com/pop

**Comment by donaldli2020** [comment]
I spammed sells and the thing happened
