### ISSUE TITLE
cool suggestion 

### ISSUE THREAD

**Issue by jquadri** [glixzzy/blooket-hack#724]
I found this other hack for another game (quizizz) where you could activate it then type in someone's name in the game then the next question they answer no matter what it will be wrong. it would be amazing If you could make something like that so you could activate it then type in someone's name in the blooket and instead of just the next question it would make all of the next questions that they answer all wrong. if it is too hard don't do it but I think it would be soooooo cool.

**Comment by donaldli2020** [comment]
this may be impossible

**Comment by edward-not** [comment]
it's probs only possible on quizziz because of some weakness in quizziz, which for no reason would be present in blooket

**Comment by glixzzy** [comment]
quizizz hacks: https://schoolcheats.net/quizizz
