### ISSUE TITLE
Hacks very laggy or broken

### ISSUE THREAD

**Issue by cryptominecrafter** [glixzzy/blooket-hack#732]
So I use the bookmarklet method of the hacks. I just finished putting the bookmarklets from schoolcheats onto my bookmarks bar. Now I went onto a blooket game, and whenever I hover over the specific bookmark for the hack, my computer becomes very laggy. As soon as I move my cursor away, my computer goes back to normal. Now the problem is that I try to run it, and then nothing happens. I don't know if this is an issue with the hack, or it takes too much computer processing power to run it. I don't know if only I'm having this issue because just a few days ago the hacks were working fine, except the laggy part, that was still there.

**Comment by glixzzy** [comment]
Ok.

**Comment by cryptominecrafter** [comment]
Any solution?
