### ISSUE TITLE
Why are some of the cheats obfuscated into hex or other?

### ISSUE THREAD

**Issue by RhinoCodes** [glixzzy/blooket-hack#738]
Title. Really stifles contribution

**Comment by donaldli2020** [comment]
it's base-64

**Comment by RhinoCodes** [comment]
My point still stands lmao

**Comment by RhinoCodes** [comment]
And some aren't either. Like  `getGold.js`. That one is un-obfuscated code that is easy to read

**Comment by donaldli2020** [comment]
> And some aren't either. Like `getGold.js`. That one is un-obfuscated code that is easy to read

idk why

**Comment by glixzzy** [comment]
why do you care lol? just use the hacks i make the code part is none of your business

**Comment by RhinoCodes** [comment]
Because I want to be able to use it in my own projects or contribute. open source and all. Plus it might be not allowed since you have the MIT license on it.

**Comment by RhinoCodes** [comment]
`, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:`

Obfuscation sounds pretty limiting to me
