### ISSUE TITLE
The issue is that I didn't win the event cuz its over now

### ISSUE THREAD

**Issue by coolawsome2009** [glixzzy/blooket-hack#741]

**Comment by zxtremedemon** [comment]
Im so sad... At first I joined Dream Guild and at the end i was like yay im gonna get a mystical blook until guild8332 overtaken us and my team KICKED ME OUT at the last 2 minutes so I found Dream guild 2 and I joined AND I GOT KICKED OUT AT 30 SECONDS LEFT and I can't find another good guild in time so I lost

**Comment by limyaocheng** [comment]
same I only got 13 tokens when the events end cuz no script for the event!

**Comment by zxtremedemon** [comment]
i got 427,890 tokens and i was 2nd in my team but i dont understand why they kicked me out

**Comment by limyaocheng** [comment]
no mystical blooks for me millions of players only 25 get nooooooooooooooooooooooooooo ... cuz maybe they thought u are sucks o only 427 890 tokens they are all millions tokens

**Comment by limyaocheng** [comment]
i am gonna tear glizzy in to pieces

**Comment by glixzzy** [comment]
stop https://github.com/glixzzy/blooket-hack/issues/740
