### ISSUE TITLE
Add a kick-specific player js script

### ISSUE THREAD

**Issue by WoofyDoofy** [glixzzy/blooket-hack#742]
Glixzzy can you add a kick-specific player javascript in the global hack. Just wanted to troll around.

**Comment by Bacon-boi** [comment]
same

**Comment by glixzzy** [comment]
Do you not understand? Stop making issues and ask in the discord server https://github.com/glixzzy/blooket-hack/issues/740

**Comment by donaldli2020** [comment]
> Glixzzy can you add a kick-specific player javascript in the global hack. Just wanted to troll around.

that is probably server-side
