### ISSUE TITLE
AddTokens bug?

### ISSUE THREAD

**Issue by P1uffy** [glixzzy/blooket-hack#746]
When you use the AddTokens hack it won't refresh your tokens until you reload the page. Instead, it might be a good idea for the script to "inspect element" and change the text to how much it gave you.

**Comment by glixzzy** [comment]
Issues are going to be closed soon pleasee see this announcement https://github.com/glixzzy/blooket-hack/issues/740 and stop making issues thanks.

**Comment by vfd65536** [comment]
It says that announcement (issue#740) was deleted. Btw, @P1uffy, you can fix this by adding 
```js
location.reload();
```
to the end of the code in addTokens.js
