### ISSUE TITLE
Why the issues are closing

### ISSUE THREAD

**Issue by jrs1rules** [glixzzy/blooket-hack#747]
Here is the reason I think this screenshot shows it.
![Screenshot 2021-12-13 9 59 41 AM](https://user-images.githubusercontent.com/95642271/145835675-6de0d317-9256-442e-b53b-f3658bc37f62.png)

**Comment by glixzzy** [comment]
Stop https://github.com/glixzzy/blooket-hack/issues/740

**Comment by donaldli2020** [comment]
> Here is the reason I think this screenshot shows it. ![Screenshot 2021-12-13 9 59 41 AM](https://user-images.githubusercontent.com/95642271/145835675-6de0d317-9256-442e-b53b-f3658bc37f62.png)

He/she probably doesn't want so much spam.
