### ISSUE TITLE
change rarities on the blooks so that it is easier to get legendaries

### ISSUE THREAD

**Issue by DEEZNUTS16208** [glixzzy/blooket-hack#752]

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
no it is server side

**Comment by donaldli2020** [comment]
> no it is server side

that is correct, pls close

**Comment by Undefineduser2** [comment]
Server side stuff can't be hacked easily if not impossible.
Likely impossible.

**Comment by glixzzy** [comment]
stop making issues please read this https://github.com/glixzzy/blooket-hack/issues/740
