### ISSUE TITLE
Global Scripts not working

### ISSUE THREAD

**Issue by Or-byte-tron** [glixzzy/blooket-hack#754]
global scripts not working-
when I use the global scripts hack, it shows a error saying "VM86:85 Uncaught (in promise) EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://api.blooket.com https://blooket.s3.us-east-2.amazonaws.com https://kit.fontawesome.com https://www.google-analytics.com https://www.googletagmanager.com https://*.firebaseio.com https://apis.google.com https://js.stripe.com https://www.recaptcha.net https://www.gstatic.com".

    at eval (<anonymous>)
    at Object.VnBse (<anonymous>:85:24)
    at <anonymous>:114:40" please fix this

**Comment by glixzzy** [comment]
stop making issues please read https://github.com/glixzzy/blooket-hack/issues/740

**Comment by donaldli2020** [comment]
> global scripts not working- when I use the global scripts hack, it shows a error saying "VM86:85 Uncaught (in promise) EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://api.blooket.com https://blooket.s3.us-east-2.amazonaws.com https://kit.fontawesome.com https://www.google-analytics.com https://www.googletagmanager.com https://*.firebaseio.com https://apis.google.com https://js.stripe.com https://www.recaptcha.net https://www.gstatic.com".
> 
> ```
> at eval (<anonymous>)
> at Object.VnBse (<anonymous>:85:24)
> at <anonymous>:114:40" please fix this
> ```

use the ones from github

**Comment by edward-not** [comment]
This is because of the Content Security Policy header. Just open the `.js` files and copy from there
