### ISSUE TITLE
fix for spam open box

### ISSUE THREAD

**Issue by hac12** [glixzzy/blooket-hack#762]
hey glixzzy i found a new hack for it if u type hac12 and open hackblooket u need to go to global and got to spam open at the top like yours but i changed it so it works now your welcome

**Comment by edward-not** [comment]
Stop being an idiot. This is way more complex than the real hack, which works perfectly fine. Pls don't be a cocky mf saying 'your welcome' even though ur 'hack' isn't clear and isn't a 'fix' like you said. Pls close @hac12

**Comment by donaldli2020** [comment]
> hey glixzzy i found a new hack for it if u type hac12 and open hackblooket u need to go to global and got to spam open at the top like yours but i changed it so it works now your welcome

i still don't understand

**Comment by hac12** [comment]
im sorry i just wanted to help

**Comment by donaldli2020** [comment]
this thing doesn`t work for bookmarks, as it doesn`t work for me

**Comment by donaldli2020** [comment]
oops why am i in fr (ca)?
