### ISSUE TITLE
Possible Help

### ISSUE THREAD

**Issue by ZiteDesigns** [glixzzy/blooket-hack#763]
hello glixzzy i have used your hacks and noticed that most school blocks that site for the new hacks Could you supply them

**Comment by frogopu** [comment]
use a proxy like [analystinn.net](url)

**Comment by Hacker1000000** [comment]
that doesn't work there are no hacks there

**Comment by frogopu** [comment]
use the proxy to go to the hack website

**Comment by MYNAMEISUHIDK21** [comment]
that website not working i click on blooket and it just changes the order of them

**Comment by mamadub03** [comment]
Just naviagate through the repo and run the code you want through the console or a bookmark

**Comment by glixzzy** [comment]
use https://schoolcheats.pages.dev/blooket its the another official site for schoolcheats

**Comment by donaldli2020** [comment]
> use https://schoolcheats.pages.dev/blooket its the another official site for schoolcheats

https://schoolcheats.pages.dev/blooket buttons are broken
