### ISSUE TITLE
Add tokens don't work

### ISSUE THREAD

**Issue by Hacker1000000** [glixzzy/blooket-hack#764]
The adding tokens don't work any more.

**Comment by Hacker1000000** [comment]
I have not been going over 500 or rewriting the code.

**Comment by Hacker1000000** [comment]
Also I have been putting javacript:

**Comment by frogopu** [comment]
try to get newer version of the script at schoolcheats.net

**Comment by Hacker1000000** [comment]
> try to get newer version of the script at schoolcheats.net

I'll try it and see what happends

**Comment by Hacker1000000** [comment]
Well it's blocked for me

**Comment by jrs1rules** [comment]
it works for me so idk why it dose not work for you.

**Comment by edward-not** [comment]
Try to use console instead of bookmarklet

**Comment by glixzzy** [comment]
> Well it's blocked for me

go to https://schoolcheats.pages.dev/blooket instead of schoolcheats.net

**Comment by donaldli2020** [comment]
> Also I have been putting javacript:

looks like you are using bookmarks
the whole thing is // commented out
@glixzzy rejects my pr for making it bookmark friendly
