### ISSUE TITLE
Hacks for Santa's Workshop

### ISSUE THREAD

**Issue by Hacker1000000** [glixzzy/blooket-hack#765]
Hey, glixzzy can you make hacks for Santa's Workshop since it's open to all.

**Comment by CollynGaming** [comment]
hackker used the gold rush hacks as santas work shop is just reskinned gold quesst

**Comment by Hacker1000000** [comment]
oh ok

**Comment by Hacker1000000** [comment]
I hope it works

**Comment by Hacker1000000** [comment]
I hope it works

**Comment by wolfgoo** [comment]
no

**Comment by wolfgoo** [comment]
not gold guest
