### ISSUE TITLE
schoolcheats doesnt open

### ISSUE THREAD

**Issue by MTGALAXI** [glixzzy/blooket-hack#767]

**Comment by glixzzy** [comment]
don't understand but if you mean schoolcheats.net is blocked then try: https://schoolcheats.pages.dev

**Comment by donaldli2020** [comment]
yeah it's blocked in many schools
use github then

**Comment by Atlas-Can-Code** [comment]
You can’t click any of the buttons

**Comment by Hacker1000000** [comment]
use these Script Repository

**Comment by varedz** [comment]
The scripts on school cheats are the same as the github repo. No need for me to add pages.dev domain to the API.
