### ISSUE TITLE
Sometimes they just don't work

### ISSUE THREAD

**Issue by yodaluca23** [glixzzy/blooket-hack#769]
Sometimes they just don't work, I will click on my Bookmarklet and nothing happens I have to refresh and do it again. Except when Im in the middle of a game I CANT!!.

Using Chromebook
On school wifi

**Comment by donaldli2020** [comment]
i tried to make some scripts bookmark-friendly via pr but @glixzzy rejects them

**Comment by yodaluca23** [comment]
> I tried to make some scripts bookmark-friendly via pr but @glixzzy rejects them

You should make a new unofficial branch.

**Comment by Nobody-720** [comment]
> Sometimes they just don't work, I will click on my Bookmarklet and nothing happens I have to refresh and do it again. Except when Im in the middle of a game I CANT!!.
> 
> Using Chromebook On school wifi

Maybe it have to do something with the **school wifi**

**Comment by donaldli2020** [comment]
there's a security policy by blooket or something and doesn't work on any computer :cry:

**Comment by donaldli2020** [comment]
![1f622](https://user-images.githubusercontent.com/74021676/146107345-309e2816-3ee4-4a05-b088-e685a2627048.png)

**Comment by Greenlio** [comment]
No, @donaldli2020, you make inconsistent pull requests that change little to nothing. The bookmarklets found at https://schoolcheats.net/blooket are actively maintained and work perfectly. Furthermore, if **any** collaborator denies a pull request, there's a 99% chance they have valid reason or cause.

**Comment by iplayblooket** [comment]
e

**Comment by jrs1rules** [comment]
same man just refresh it is the way the code is but I don,t really care about it though I just use it.

**Comment by donaldli2020** [comment]
schoolcheats.net bookmarks conflict with a security policy and don't work
I tried to make it so that github hacks work on bookmarks

**Comment by Greenlio** [comment]
Wrong. Schoolcheats doesn't even use fetch() so that's impossible. Stop using funny words that aren't even true.

**Comment by donaldli2020** [comment]
oh, i didnt know its updated

**Comment by wolfgoo** [comment]
yes

**Comment by Exetion** [comment]
omggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
