### ISSUE TITLE
Sell Dupe Blooks does not work

### ISSUE THREAD

**Issue by yodaluca23** [glixzzy/blooket-hack#770]
Sell Dupe Blooks does not work I've tried getting it to work but when I click on my bookmarklet nothing happens.

Using Chromebook
On school Wifi.

**Comment by glixzzy** [comment]
i just tried and it works try getting the new scripts from https://schoolcheats.net/

**Comment by donaldli2020** [comment]
i tried to fix this by pr but @glixzzy rejects them
