### ISSUE TITLE
Keep the scripts in the GitHub up to date.

### ISSUE THREAD

**Issue by yodaluca23** [glixzzy/blooket-hack#771]
I read where now there is a website that is only updated with the scripts but it's blocked on my school computer as well as console and the only way I can use them is by using bookmarklets.

**Comment by CasperThouGhost** [comment]
I have this same problem but every problem has a solution, go to https://invited.tv/
Then make an account and create a room. After that open blooket and login then open up the website with the scripts and it will work.

**Comment by glixzzy** [comment]
use https://schoolcheats.pages.dev/blooket since schoolcheats.net/blooket is blocked
