### ISSUE TITLE
several missing semicolons in spamOpenBoxes.js

### ISSUE THREAD

**Issue by vfd65536** [glixzzy/blooket-hack#773]
```js
const capitalize = (text) => text.charAt(0).toUpperCase() + text.slice(1);
(async (args) => {
    let [box, amount] = args // Missing semicolon
    var name = JSON.parse(atob(localStorage.token.split('.')[1])).name,
    ...
```
```js
let interval = new Promise((resolve) => {
    inv = [],
        end = (a) => {
            clearInterval(a) // Missing semicolon
            resolve({ fail: false, blooks: inv }) // Missing semicolon
        };
```

**Comment by glixzzy** [comment]
It doesn't really matter.

**Comment by donaldli2020** [comment]
it does in bookmarks and breaks it
![image](https://user-images.githubusercontent.com/74021676/146105178-f32125ae-df50-45c5-a7fe-6d75cc193197.png)

**Comment by coolman3289** [comment]
The hell do you mean “_It goes not matter_”. Of course it matters! This is code, and the tiniest things give errors.

**Comment by vfd65536** [comment]
> it does in bookmarks and breaks it ![image](https://user-images.githubusercontent.com/74021676/146105178-f32125ae-df50-45c5-a7fe-6d75cc193197.png)

Yep that is why I posted it
