### ISSUE TITLE
Give all blooks isn't working

### ISSUE THREAD

**Issue by IronMike2** [glixzzy/blooket-hack#774]
Hello. The reason I am writing this is that when I use the code for the "Give all Blooks" hack, it isn't working, as it just says "you need to be on the blook selection page" even when I am on the page. This may be a mistake on my part, but I would recommend looking into the code for the hack. If you can fix it, or be able to show me my mistake, I would be thankful. Thank you.

**Comment by donaldli2020** [comment]
you must be the part after the nickname thing and it works

**Comment by Nobody-720** [comment]
**It is not in the blooket blooks page**
_it is in the game of selecting blooks _

**Comment by donaldli2020** [comment]
pls close

**Comment by Greenlio** [comment]
> pls close

no need to tell to close. collaborators check issues every few hours.
anyway, your url should include ``/play/lobby``

**Comment by Greenlio** [comment]
https://user-images.githubusercontent.com/62725108/146113878-10872cec-69d0-4e30-b608-341de4795b43.mp4
