### ISSUE TITLE
issue with history

### ISSUE THREAD

**Issue by donaldli2020** [glixzzy/blooket-hack#777]
if the number gets too big on some kind of currency, this happens
![image](https://user-images.githubusercontent.com/74021676/146107769-9941cc4c-1b43-43a3-bfbc-585beb4bc6e1.png)

**Comment by Nobody-720** [comment]
yeah it goes out of the box [ **and the blooks yu use disappeared ** ]

**Comment by Nobody-720** [comment]
_Which another people says yur hacking_

**Comment by donaldli2020** [comment]
oops

**Comment by Greenlio** [comment]
duh, but that's not our fault.

**Comment by donaldli2020** [comment]
> duh, but that's not our fault.

lol

**Comment by Nobody-720** [comment]
> duh, but that's not our fault.

**well it is our fault cause we are the one who is using hacks ;=; **

**Comment by donaldli2020** [comment]
hope glixzzy sets a limit to prevent
