### ISSUE TITLE
Add coins for cafe wont work

### ISSUE THREAD

**Issue by tacticalwolf56** [glixzzy/blooket-hack#781]
When i type in how many coins i want it says coins added buti dont get them?
Im on chromebook btw

**Comment by donaldli2020** [comment]
works for me unless ur using schoolcheats.net

**Comment by wolfgoo** [comment]
sometimes work

**Comment by hecker1234567890** [comment]
still works lmao

**Comment by Exetion** [comment]
omggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
