### ISSUE TITLE
The Bookmarklets don’t work

### ISSUE THREAD

**Issue by coolman3289** [glixzzy/blooket-hack#783]
The bookmarklet method does not work.

**Comment by glixzzy** [comment]
just add `javascript:` and then the code

**Comment by coolman3289** [comment]
Still does not work

**Comment by donaldli2020** [comment]
I tried to fix it, but @glixzzy rejects it.

**Comment by coolman3289** [comment]
Then make your own project with the fix.

**Comment by donaldli2020** [comment]
which hack

**Comment by donaldli2020** [comment]
global...

**Comment by donaldli2020** [comment]
?
