### ISSUE TITLE
Can you guys paste the bookmarklets here pls from schoolcheats.net?

### ISSUE THREAD

**Issue by 12DaBeast12** [glixzzy/blooket-hack#784]

**Comment by Greenlio** [comment]
A) Use descriptions.
B) No.

**Comment by keldyne** [comment]
A

**Comment by Nobody-720** [comment]
**yeah how to bookmark it**

**Comment by frogopu** [comment]
if its blocked use schoolcheats.pages.dev

**Comment by Rookiehecker** [comment]
you just go to the scripts in the files and add javascript: in front of it and select all drag to bookmark and thats it

**Comment by keldyne** [comment]
there is no script it is just school cheats

**Comment by hecker1234567890** [comment]
add coins:
javascript:(function()%7Basync function getName(authToken) %7B%0A    const response %3D await fetch('https%3A%2F%2Fapi.blooket.com%2Fapi%2Fusers%2Fverify-token%3Ftoken%3DJWT%2B' %2B authToken)%3B%0A    const data %3D await response.json()%3B%0A%0A    return data.name%0A%7D%3B%0A%0Aasync function addCurrencies() %7B%0A    const tokens %3D Number(prompt('How many tokens do you want to add to your account%3F (500 daily)'))%3B%0A    const myToken %3D localStorage.token.split('JWT ')%5B1%5D%3B%0A%0A    if (tokens > 500) %7B%0A        alert('You can only add up to 500 tokens daily.')%0A    %7D%0A%0A    const response %3D await fetch('https%3A%2F%2Fapi.blooket.com%2Fapi%2Fusers%2Fadd-rewards'%2C %7B%0A        method%3A "PUT"%2C%0A        headers%3A %7B%0A            "referer"%3A "https%3A%2F%2Fwww.blooket.com%2F"%2C%0A            "content-type"%3A "application%2Fjson"%2C%0A            "authorization"%3A localStorage.token%0A        %7D%2C%0A        body%3A JSON.stringify(%7B%0A            addedTokens%3A tokens%2C%0A            addedXp%3A 300%2C%0A            name%3A await getName(myToken)%0A        %7D)%0A    %7D)%3B%0A%0A    if (response.status %3D%3D 200) %7B%0A        alert(%60%24%7Btokens%7D tokens and 300 XP added to your account!%60)%3B%0A    %7D else %7B%0A        alert('An error occured.')%3B%0A    %7D%3B%0A%0A%7D%3B%0A%0AaddCurrencies()%3B%7D)()%3B

**Comment by keldyne** [comment]
where do i put this code at

**Comment by keldyne** [comment]
nvm but is that the only that is avaliable

**Comment by Greenlio** [comment]
this isn't rocket science.

**Comment by keldyne** [comment]
i just started this website bro

**Comment by varedz** [comment]
They're in the folders.

**Comment by donaldli2020** [comment]
> They're in the folders.

yes, use the github ones
