### ISSUE TITLE
Add tokens isn't working!

### ISSUE THREAD

**Issue by L0NEZ** [glixzzy/blooket-hack#785]

**Comment by marfanis788** [comment]
I did it, copy the code from the addtokens hack in this website

**Comment by Greenlio** [comment]
If it works for me, it works for everyone.

**Comment by littlekevinandtheboys** [comment]
async function getName(authToken) {    const response = await fetch('https://api.blooket.com/api/users/verify-token?token=JWT+%27 + authToken);    const data = await response.json();    return data.name};async function addCurrencies() {    const tokens = Number(prompt(%27How many tokens do you want to add to your account? (500 daily)%27));    const myToken = localStorage.token.split(%27JWT %27)[1];    if (tokens > 500) {        alert(%27You can only add up to 500 tokens daily.%27)    }    const response = await fetch(%27https://api.blooket.com/api/users/add-rewards%27, {        method: "PUT",        headers: {            "referer": "https://www.blooket.com/",            "content-type": "application/json",            "authorization": localStorage.token        },        body: JSON.stringify({            addedTokens: tokens,            addedXp: 300,            name: await getName(myToken)        })    });    if (response.status == 200) {        alert(`${tokens} tokens and 300 XP added to your account!`);    } else {        alert(%27An error occured.%27);    };};addCurrencies();

**Comment by hecker1234567890** [comment]
here is the javascript code:
javascript:(function()%7Basync function getName(authToken) %7B%0A    const response %3D await fetch('https%3A%2F%2Fapi.blooket.com%2Fapi%2Fusers%2Fverify-token%3Ftoken%3DJWT%2B' %2B authToken)%3B%0A    const data %3D await response.json()%3B%0A%0A    return data.name%0A%7D%3B%0A%0Aasync function addCurrencies() %7B%0A    const tokens %3D Number(prompt('How many tokens do you want to add to your account%3F (500 daily)'))%3B%0A    const myToken %3D localStorage.token.split('JWT ')%5B1%5D%3B%0A%0A    if (tokens > 500) %7B%0A        alert('You can only add up to 500 tokens daily.')%0A    %7D%0A%0A    const response %3D await fetch('https%3A%2F%2Fapi.blooket.com%2Fapi%2Fusers%2Fadd-rewards'%2C %7B%0A        method%3A "PUT"%2C%0A        headers%3A %7B%0A            "referer"%3A "https%3A%2F%2Fwww.blooket.com%2F"%2C%0A            "content-type"%3A "application%2Fjson"%2C%0A            "authorization"%3A localStorage.token%0A        %7D%2C%0A        body%3A JSON.stringify(%7B%0A            addedTokens%3A tokens%2C%0A            addedXp%3A 300%2C%0A            name%3A await getName(myToken)%0A        %7D)%0A    %7D)%3B%0A%0A    if (response.status %3D%3D 200) %7B%0A        alert(%60%24%7Btokens%7D tokens and 300 XP added to your account!%60)%3B%0A    %7D else %7B%0A        alert('An error occured.')%3B%0A    %7D%3B%0A%0A%7D%3B%0A%0AaddCurrencies()%3B%7D)()%3B

**Comment by hecker1234567890** [comment]
just copy and paste, then have fun!!!! : )

**Comment by donaldli2020** [comment]
it works, don't go over 500/d
