### ISSUE TITLE
can someone paste chest esp for gold quest 

### ISSUE THREAD

**Issue by Telantix** [glixzzy/blooket-hack#786]
i have all the scripts but i missed this one i need  it school cheats is blocked at my school

**Comment by frogopu** [comment]
use schoolcheats.pages.dev/blooket

**Comment by Telantix** [comment]
for some reason when i click on the hacks for the .dev version copying
doesnt work.

**Comment by Telantix** [comment]
like i cant copy the script

**Comment by Greenlio** [comment]
Yes, the .dev doesn't work. Wait for @varedz to fix it or wait for the weekend.

**Comment by varedz** [comment]
The scripts on school cheats are the same as the github repo. No need for me to add pages.dev domain to the API.
