### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by jrs1rules** [glixzzy/blooket-hack#787]
I think we should get a new website because school cheats is block for me I think it should be like a alt for school cheats because it is blocked.

**Comment by hecker1234567890** [comment]
you do not need website to use hacks

**Comment by Telantix** [comment]
thats not what he means :/

**Comment by jrs1rules** [comment]
yeah hecker1234567890

**Comment by Greenlio** [comment]
Paste the raw code into console if you need a way.

**Comment by varedz** [comment]
> I think we should get a new website because school cheats is block for me I think it should be like a alt for school cheats because it is blocked.

The scripts in the repo folders are the same as School Cheats.
