### ISSUE TITLE
change round not working

### ISSUE THREAD

**Issue by CorbanO2** [glixzzy/blooket-hack#789]
change round script for tower defense returns an error

"An error occured, would you like to report this in the support discord server?"

**Comment by Greenlio** [comment]
"All issues will be fixed this weekend." - glixzzy

**Comment by donaldli2020** [comment]
> change round script for tower defense returns an error
> 
> "An error occured, would you like to report this in the support discord server?"

me too

**Comment by wolfgoo** [comment]
Idk sometimes work sometimes don't

**Comment by wolfgoo** [comment]
multitool and school cheat sometimes work sometimes don't work
