### ISSUE TITLE
The schoolcheats website doesnt work because its blocked so can you put the script instead of "go to school cheats website"

### ISSUE THREAD

**Issue by NovaBomb124** [glixzzy/blooket-hack#790]
The schoolcheats website doesnt work because its blocked so can you put the script instead of "go to school cheats website"

**Comment by hecker1234567890** [comment]
use bookmarklet maker

**Comment by Greenlio** [comment]
Paste the raw code that's in the GitHub file into console.

**Comment by varedz** [comment]
The scripts on school cheats are the same as the github repo. No need for me to add pages.dev domain to the API.
