### ISSUE TITLE
.dev version of school cheats is broken lol

### ISSUE THREAD

**Issue by Telantix** [glixzzy/blooket-hack#792]
.dev is broken nothing works on it including copying scripts and kahoot flooding. Maybe its just my school internet blocking but is this happening to anyone else

**Comment by Greenlio** [comment]
Yep, it's not authorized on the API. @varedz said they'd fix it, but it hasn't been done so you just have to wait.

**Comment by varedz** [comment]
The scripts on school cheats are the same as the github repo. No need for me to add pages.dev domain to the API.
