### ISSUE TITLE
This is for Glixzzy 

### ISSUE THREAD

**Issue by gIixzzy** [glixzzy/blooket-hack#793]
Is it fine if I'm impersonating you? If not tell me. 

Reply to my previous statement - 
@glixzzy  ( it was a joke ) I realize that you can't tell that I was being sarcastic because it's on an online text. Sorry for not putting this into consideration. 

I also made sure to put in my bio - "I am the fake glixzzy"

**Comment by glixzzy** [comment]
No. Why would you do that in the first place? Impersonating someone of GitHub is against the rules.

**Comment by hecker1234567890** [comment]
you can't impersonate people and that is also illegal in the first place

**Comment by hecker1234567890** [comment]
you can go to jail for 3 years and Glixzzy can charge you money or anything of value, so the moral of story, do not be a sussy imposter

**Comment by wolfgoo** [comment]
!

**Comment by wolfgoo** [comment]
But I didn't do that so I'm not afraid.

**Comment by wolfgoo** [comment]
> Is it fine if I'm impersonating you? If not tell me.

Who are u?

**Comment by jrs1rules** [comment]
> Is it fine if I'm impersonating you? If not tell me.

WOW IT THE REAL GLIZZY jk bruh why you do this?

**Comment by gIixzzy** [comment]
I mean, I did say in my bio I am the fake gLixzzy
