### ISSUE TITLE
hacks   no work

### ISSUE THREAD

**Issue by hecker1234567890** [glixzzy/blooket-hack#795]
some of the blooket hacks not work, so can you change and debug them? And can you also add back some of the deleted hacks again? I had fun flooding servers.

**Comment by donaldli2020** [comment]
flooding servers broke, i believe

**Comment by wolfgoo** [comment]
yes

**Comment by wolfgoo** [comment]
but I got another flooding mode hacks

**Comment by mollthecoder** [comment]
Whenever it stops working for me I make sure the code I'm running is up-to-date. That normally fixes it.

**Comment by gIixzzy** [comment]
If you want to flood servers, go to - https://www.gbasil.dev/blooket?xenonaut=cool - scroll down find the green highlighted word (MultiTool) drag it up to your bookmark tab then use it in game. It should have an option to flood the game.
