### ISSUE TITLE
Can Yu Add Santa's Workshop Hack Since It Is Out For Free . . . TQ

### ISSUE THREAD

**Issue by Nobody-720** [glixzzy/blooket-hack#797]

**Comment by donaldli2020** [comment]
i think they're working on it

**Comment by wolfgoo** [comment]
?

**Comment by wolfgoo** [comment]
Use multitool I also have used it to use Santa's Workshop hack.

on Gbazil find multitool copy and paste the multitool the bookmarklet and in blooket to use.

link:(https://www.gbasil.dev/blooket)

**Comment by wolfgoo** [comment]
???

**Comment by Greenlio** [comment]
No, we're not working on it, and one will not be made because it's a limited time gamemode.
