### ISSUE TITLE
fishing frenzy weight setting script got patched

### ISSUE THREAD

**Issue by Telantix** [glixzzy/blooket-hack#801]
i tried with multi tool and the school cheats version but they both dont work

**Comment by gIixzzy** [comment]
![image](https://user-images.githubusercontent.com/94643594/146574992-e9053ef0-7ddf-4437-a54a-a05c98dd93d9.png)

It still works

**Comment by Greenlio** [comment]
Imposter. You are not real. Anyway, yes, the imposter is correct and it works.

**Comment by hecker1234567890** [comment]
lmao

**Comment by hecker1234567890** [comment]
sheeeeeesh, fake glixzzy, your name is tyler?
