### ISSUE TITLE
School blocked schoolcheats.com

### ISSUE THREAD

**Issue by Oat99** [glixzzy/blooket-hack#803]

**Comment by gIixzzy** [comment]
just go to mine, I added the exact ones he has on schoolcheats.com

**Comment by gIixzzy** [comment]
Or just get on a non controlled computer go to schoolcheats.com then copy the bookmarklets and make an email to your self

**Comment by Greenlio** [comment]
Imposter! Again, but like, change your name. It's not cool man. 
Later today when my pull request is merged they'll be back.

**Comment by hecker1234567890** [comment]
lmao

**Comment by hecker1234567890** [comment]
go to a bookmarklet maker and paste the hack's code into it, then generate a javascript code, then you just copy and paste javascript into a bookmark!! nice and eez

**Comment by glixzzy** [comment]
get the scripts from https://github.com/glixzzy/blooket-hack/

**Comment by Oat99** [comment]
ok
