### ISSUE TITLE
Tower Defense Coins Hack Not Working

### ISSUE THREAD

**Issue by HawkFalcon787** [glixzzy/blooket-hack#805]
It says that coins are added, I added a 100, but it still only shows 4 tokens in blooket, and when I spend them all, the 4 tokens, I can't buy any other towers.

**Comment by gIixzzy** [comment]
This can happen a lot. If this does happen just make sure you wait until you see the question screen, then type in the amount of coins you want.

![image](https://user-images.githubusercontent.com/94643594/146591885-ee0f3ee9-c350-4093-9c9e-a5a2dc688f38.png)

![image](https://user-images.githubusercontent.com/94643594/146592001-e3921bd5-dabc-45e5-bc40-77a9d799d593.png)

**Comment by HawkFalcon787** [comment]
Thanks, I wasn't doing it on the question screen, I was doing it after. Thx!

**Comment by Greenlio** [comment]
Works. Imposter not cool.

**Comment by hecker1234567890** [comment]
lmao, is this person now nicknamed "imposter" now?

**Comment by gIixzzy** [comment]
yes
