### ISSUE TITLE
Change Round saying Error Occured (Tower Defense)

### ISSUE THREAD

**Issue by HawkFalcon787** [glixzzy/blooket-hack#815]

**Comment by gIixzzy** [comment]
It should be fixed over the weekend

**Comment by HawkFalcon787** [comment]
ty!

**Comment by Greenlio** [comment]
Will be fixed this weekend. Also, Imposter not cool swag!

**Comment by HawkFalcon787** [comment]
> Will be fixed this weekend. Also, Imposter not cool swag!

wdym imposter

**Comment by Greenlio** [comment]
They aren't the real glixzzy.

**Comment by marfanis788** [comment]
Fake-zzy

**Comment by HawkFalcon787** [comment]
> It should be fixed over the weekend

Also, what about the clear enemies, when do I do it?

**Comment by hecker1234567890** [comment]
idk

**Comment by hecker1234567890** [comment]
you use clear enemies when you are about to die or lose or something

**Comment by gIixzzy** [comment]
ah yes I am the great imposter now lmfao

**Comment by gIixzzy** [comment]
at least I'm a helpful one

**Comment by TheRandomCat** [comment]
lol
