### ISSUE TITLE
Getting all blooks in game.

### ISSUE THREAD

**Issue by Xlotl** [glixzzy/blooket-hack#819]
when i try typing in the code on the blook selecting page, it says i have to be on the blook selecting page???

**Comment by donaldli2020** [comment]
waiting for host page

**Comment by gIixzzy** [comment]
@Xlotl When someone hosts a game, and you join them by putting in the code than typing your nickname a selection page for which blook you want will show up. When you see this page use your way of "Getting all blooks in-game" and it should work just fine.

**Comment by donaldli2020** [comment]
The page should say waiting for host.
Use the hack on that page.
