### ISSUE TITLE
Once I use a hack, I have to reload

### ISSUE THREAD

**Issue by HawkFalcon787** [glixzzy/blooket-hack#831]
Is there a way for the bookmarklet hacks to work all the time without reloading?

**Comment by marfanis788** [comment]
No I think he means like Fishing Frenzy for example, it won't add weight until you refresh the page, but doing that kicks you out of the game

**Comment by pdwolfmine** [comment]
It reloads every 3 am, so you can add 500 tokens every day. Yes you have 2 reload or you can just leave the cite and come back.

**Comment by HawkFalcon787** [comment]
i mean like for any game hack, I can use it once, then when I use again doesn't work @frogopu @marfanis788 @pdwolfmine

**Comment by glixzzy** [comment]
will be fixed soon
