### ISSUE TITLE
add tokens

### ISSUE THREAD

**Issue by Bunnytoes** [glixzzy/blooket-hack#833]
for the add tokens script to work, you have to copy the raw contents without the comment in it
P.S. what would happen if you fork it and change the box costs?

**Comment by donaldli2020** [comment]
yeah for bookmarks

**Comment by donaldli2020** [comment]
you can for console

**Comment by Bunnytoes** [comment]
I know. I meant for the bookmarklet

**Comment by glixzzy** [comment]
??

**Comment by Bunnytoes** [comment]
if you paste the addtokens.js into the search browser in blooket, it doesn't work, but if you delete the comments at the top, it works
