### ISSUE TITLE
Add Santa's Workshop cheat

### ISSUE THREAD

**Issue by Faloof** [glixzzy/blooket-hack#844]
Nothing works for Santa's workshop, patch please.

**Comment by HawkFalcon787** [comment]
> Nothing works for Santa's workshop, patch please.

There is no hack for Santa's Workshop yet

**Comment by donaldli2020** [comment]
> > Nothing works for Santa's workshop, patch please.
> 
> There is no hack for Santa's Workshop yet

@glixzzy confirmed that it would not be worked on.

**Comment by gimmy74** [comment]
I made a nodejs script for it 💀

**Comment by wolfgoo** [comment]
Basil have Santa's Workshop hacks.

https://www.gbasil.dev/blooket

**Comment by wolfgoo** [comment]
copy the multitool and paste it on the bookmarklet.

You need in blooket to use it.

**Comment by donaldli2020** [comment]
please close

**Comment by Greenlio** [comment]
It will not be worked on due to the fact it's a limited mode. Every Answer Correct works to my knowledge.
