### ISSUE TITLE
ok so 500 coin hack be like-

### ISSUE THREAD

**Issue by Aquamarine110313** [glixzzy/blooket-hack#845]
yes i'm back but when i use it this happens

"Uncaught (in promise) TypeError: Cannot read properties of null (reading 'name')
    at getName (<anonymous>:5:17)
    at async addCurrencies (<anonymous>:26:19)
getName @ VM87:5
await in getName (async)
(anonymous) @ VM87:38"

**Comment by donaldli2020** [comment]
Make sure you have enough on your daily coin limit.

**Comment by donaldli2020** [comment]
stats page

**Comment by gimmy74** [comment]
> yes i'm back but when i use it this happens
> 
> "Uncaught (in promise) TypeError: Cannot read properties of null (reading 'name') at getName (:5:17) at async addCurrencies (:26:19) getName @ VM87:5 await in getName (async) (anonymous) @ VM87:38"

If you are using this script by yourself and you fetched your token and username by yourself then maybe there is a misspell in the name or auth token, If this is just you using the bookmarklet then someone must have logged into your account or something.

**Comment by wolfgoo** [comment]
???

**Comment by wolfgoo** [comment]
then use other autofill token

**Comment by wolfgoo** [comment]
Use basil

(https://www.gbasil.dev/blooket)

**Comment by wolfgoo** [comment]
copy the autofill token on below Basil and paste it on the bookmarklet.

You need in blooket to use it.

**Comment by Greenlio** [comment]
@wolfgoo if you're gonna tell people to use basils then you are doing nothing to solve the issue so just don't say anything at all lol, they're looking for a fix to this repositories and here they are:
A) you aren't on blooket
B) you aren't signed in on blooket

**Comment by Aquamarine110313** [comment]
hey i am

**Comment by Piplup7575** [comment]
@Aquamarine110313 
Did you run this?
``` async function getName(t){const o=await fetch("https://api.blooket.com/api/users/verify-token?token=JWT+"+t);return(await o.json()).name}async function addCurrencies(){const t=Number(prompt("How many tokens do you want to add to your account? (500 daily)")),o=localStorage.token.split("JWT ")[1];t>500&&alert("You can only add up to 500 tokens daily."),200==(await fetch("https://api.blooket.com/api/users/add-rewards",{method:"PUT",headers:{referer:"https://www.blooket.com/","content-type":"application/json",authorization:localStorage.token},body:JSON.stringify({addedTokens:t,addedXp:300,name:await getName(o)})})).status?alert(`${t} tokens and 300 XP added to your account!`):alert("An error occured.")}addCurrencies();```
If the comments are still in the code, then you need to remove them to run the code.
It works fine for me though

**Comment by Nobody-720** [comment]
> @Aquamarine110313 Did you run this? `` async function getName(t){const o=await fetch("https://api.blooket.com/api/users/verify-token?token=JWT+"+t);return(await o.json()).name}async function addCurrencies(){const t=Number(prompt("How many tokens do you want to add to your account? (500 daily)")),o=localStorage.token.split("JWT ")[1];t>500&&alert("You can only add up to 500 tokens daily."),200==(await fetch("https://api.blooket.com/api/users/add-rewards",{method:"PUT",headers:{referer:"https://www.blooket.com/","content-type":"application/json",authorization:localStorage.token},body:JSON.stringify({addedTokens:t,addedXp:300,name:await getName(o)})})).status?alert(`${t} tokens and 300 XP added to your account!`):alert("An error occured.")}addCurrencies(); `` If the comments are still in the code, then you need to remove them to run the code. It works fine for me though

Yeah Yu Should Use That

`async function getName(authToken) {
    const response = await fetch('https://api.blooket.com/api/users/verify-token?token=JWT+' + authToken);
    const data = await response.json();

    return data.name;
};

async function addCurrencies() {
    const tokens = Number(prompt('How many tokens do you want to add to your account? (500 daily)'));
    const myToken = localStorage.token.split('JWT ')[1];

    if (tokens > 500) {
        alert('You can only add up to 500 tokens daily.');
    };

    const response = await fetch('https://api.blooket.com/api/users/add-rewards', {
        method: "PUT",
        headers: {
            "referer": "https://www.blooket.com/",
            "content-type": "application/json",
            "authorization": localStorage.token
        },
        body: JSON.stringify({
            addedTokens: tokens,
            addedXp: 300,
            name: await getName(myToken)
        })
    });

    if (response.status == 200) {
        alert(`${tokens} tokens and 300 XP added to your account!`);
    } else {
        alert('An error occured.');
    };

};

addCurrencies();`

**Comment by glixzzy** [comment]
Blooket hack v3 has just been released! visit: https://github.com/glixzzy/blooket-hack for the scripts
