### ISSUE TITLE
no output esp

### ISSUE THREAD

**Issue by Dankcraft** [glixzzy/blooket-hack#846]
there is no esp for the output in crypto hack for when you answer correct

**Comment by wolfgoo** [comment]
esp???

**Comment by donaldli2020** [comment]
this is not an issue
please cose

**Comment by Greenlio** [comment]
A) spell close wrong if you're gonna tell people what to do with their issue
B) no, it's an enhancement which are allowed to be suggested

**Comment by Piplup7575** [comment]
did you delete the comment in the file?

**Comment by Dankcraft** [comment]
> did you delete the comment in the file?

what file?

**Comment by jrs1rules** [comment]
please cose. Learn grammer

**Comment by donaldli2020** [comment]
Gramm***e***r

**Comment by donaldli2020** [comment]
@jrs1rules

**Comment by Dankcraft** [comment]
why is my suggestion turning into a twitter argument?

**Comment by donaldli2020** [comment]
@Greenlio are -> is

**Comment by Greenlio** [comment]
are refers to plural - I'm referring to a group of suggestions, so my grammar is correct

**Comment by Greenlio** [comment]
> why is my suggestion turning into a twitter argument?

collaborators offline for holidays so it's up to these 12-13 year old contributors to respond to everything lmao

**Comment by donaldli2020** [comment]
"An enhancement" is singular, ***an***

**Comment by Greenlio** [comment]
> "An enhancement" is singular, ***an***

starts with a vowel so it's an

**Comment by donaldli2020** [comment]
I know, but the an means it's singular

**Comment by glixzzy** [comment]
Blooket hack v3 has just been released! visit: https://github.com/glixzzy/blooket-hack for the scripts
