### ISSUE TITLE
can't use twice

### ISSUE THREAD

**Issue by Dankcraft** [glixzzy/blooket-hack#847]
if I use one of the hacks, I can't use another one for some reason when I click it, it doesn't do anything.

**Comment by wolfgoo** [comment]
Idk

**Comment by donaldli2020** [comment]
then use console
it does that only for bookmarks for some reason

**Comment by Piplup7575** [comment]
Yes
@glixzzy said they were working on it in issue #831 
just deal with it for now

**Comment by Dankcraft** [comment]
> then use console it does that only for bookmarks for some reason

inspect is blocked in my school

**Comment by glixzzy** [comment]
Blooket hack v3 has just been released! visit: https://github.com/glixzzy/blooket-hack for the scripts
