### ISSUE TITLE
Yeah I agree with Dankcraft, we should get a reward ESP for crypto hack too! :D

### ISSUE THREAD

**Issue by FallGuysFan1234** [glixzzy/blooket-hack#849]
I think this would be really beneficial glixzzy! :D

**Comment by gimmy74** [comment]
Why tf would you make a whole new issue for this?

**Comment by Dankcraft** [comment]
idk

**Comment by jrs1rules** [comment]
wtf are you talking about?

**Comment by GitHubUserPy** [comment]
I doubt it is possible to get ESP on crypto since it wont show what you could've gotten, while gold does
