### ISSUE TITLE
Adding tokens are broken

### ISSUE THREAD

**Issue by t0misbest** [glixzzy/blooket-hack#851]
I have no idea why it's add for me 444 tokens instead of 500 tokens. Pls fix

**Comment by donaldli2020** [comment]
you have a 500 per day limit

**Comment by donaldli2020** [comment]
hacked and not hacked tota

**Comment by donaldli2020** [comment]
*total

**Comment by t0misbest** [comment]
> you have a 500 per day limit

dud it's doesn't add all 500 tokens for me

**Comment by varedz** [comment]
You must've played a game and received tokens from a gamemode you played that same day, thus not giving you the full 500.

**Comment by t0misbest** [comment]
> You must've played a game and received tokens from a gamemode you played that same day, thus not giving you the full 500.

thx
