### ISSUE TITLE
can you make a hack that gives you more of a specific blook

### ISSUE THREAD

**Issue by mrNoodleYT** [glixzzy/blooket-hack#852]
can you make a hack that gives you more of a specific blook

**Comment by Dankcraft** [comment]
So like puts it in your inventory?

**Comment by mrNoodleYT** [comment]
yes

**Comment by mrNoodleYT** [comment]
so basically you could get unlimited coins by selling the same blook over and over

**Comment by coolawsome2009** [comment]
that sounds dope

**Comment by donaldli2020** [comment]
impossible, server-side

**Comment by sahar233** [comment]
lemme know if it happens

**Comment by donaldli2020** [comment]
@mrNoodleYT @Dankcraft @coolawsome2009 @sahar233
This hack is impossible because it is server-side.
