### ISSUE TITLE
change game round doesn't work

### ISSUE THREAD

**Issue by Rookiehecker** [glixzzy/blooket-hack#854]
I tried to change round is td but doesn't work (btw it's a homework and only has one wave

**Comment by SebasFamilyTV150** [comment]
hey add santa workshop hacks

**Comment by t0misbest** [comment]
> hey add santa workshop hacks

yes

**Comment by glixzzy** [comment]
Blooket hack v3 has just been released! visit: https://github.com/glixzzy/blooket-hack for the scripts
