### ISSUE TITLE
Problem with spam open boxes

### ISSUE THREAD

**Issue by hihihhihihihihihihihihihih** [glixzzy/blooket-hack#856]
I can't use spam open boxes hack twice (unless I reload).  It is really annoying so plz fix this fast.

**Comment by hihihhihihihihihihihihihih** [comment]
It's been 2 days and still no reply TT

**Comment by donaldli2020** [comment]
Just don't go over your token count.

**Comment by Greenlio** [comment]
works for me

**Comment by glixzzy** [comment]
Blooket hack v3 has just been released! visit: https://github.com/glixzzy/blooket-hack for the scripts
