### ISSUE TITLE
Problem with getAllBlooksInGame.js

### ISSUE THREAD

**Issue by Jesuslovesme1234** [glixzzy/blooket-hack#861]
It dosnt work. can you fix it please

**Comment by donaldli2020** [comment]
use it on the waiting for host page

**Comment by sahar233** [comment]
you have to use it in lobby of waiting for a game

**Comment by chansinyuen** [comment]
don't be messed. It isn't forever, it is only in the game

**Comment by Greenlio** [comment]
https://user-images.githubusercontent.com/62725108/147725242-705e2d3b-b330-4bbf-9d99-76dbe5af1161.mp4

ok

**Comment by glixzzy** [comment]
Blooket hack v3 has just been released! visit: https://github.com/glixzzy/blooket-hack for the scripts
