### ISSUE TITLE
Fishing Frenzy Weight Hack

### ISSUE THREAD

**Issue by sahar233** [glixzzy/blooket-hack#862]
Not working tried everything

**Comment by Greenlio** [comment]
if it works im gonna be angry

**Comment by Greenlio** [comment]
i am very angr
![9vWezw5oQ8](https://user-images.githubusercontent.com/62725108/147725154-817ac928-fa47-4889-82f3-63503e8e083b.gif)
y

**Comment by sahar233** [comment]
its not that its that it wont come on the hosts screen

**Comment by glixzzy** [comment]
Blooket hack v3 has just been released! visit: https://github.com/glixzzy/blooket-hack for the scripts
