### ISSUE TITLE
Add Tokens

### ISSUE THREAD

**Issue by Oorwlly** [glixzzy/blooket-hack#865]
The add tokens hack is simply not working for me. If i put in the 500 on the alert, after that the alert saying '500 tokens and 300 xp added to your account' doesn't pop up. I tried github and schoolcheats, using inspect and bookmarklets, and it doesn't work so i cannot just get 500 tokens or bypass the limit until this is fixed

**Comment by sushixhan** [comment]
same!

**Comment by IAMSPECIAL76** [comment]
SAME!!!

**Comment by IAMSPECIAL76** [comment]
PLEASE FIX

**Comment by Cerulean-MC** [comment]
same here!

**Comment by sahar233** [comment]
same!!! someone let me know when its back up

**Comment by chansinyuen** [comment]
Same....

**Comment by glixzzy** [comment]
Blooket hack v3 has just been released! visit: https://github.com/glixzzy/blooket-hack for the scripts
