### ISSUE TITLE
AddTokens Has a problem again!!

### ISSUE THREAD

**Issue by DreamMinecraftBlooket** [glixzzy/blooket-hack#866]
So ik that u may have already pulled a request two hours ago but ya'know there's another one so basically i put the code for AddTokens.js right, when i did that it does say how many tokens do you want but when i put 500 or anything else it does'nt say 300 exp and 500 tokens have been added to your account! Instead it says (in red) this: VM68:2 GET https://api.blooket.com/api/users/verify-token?token=JWT+eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWIyNDFjYzZlZmJiMzE2OWU0YTBkMWYiLCJuYW1lIjoiRkJJX0FHRU5UX1V3VSIsImVtYWlsIjoiaGlteWxpZmUxMjNuaWNlQGdtYWlsLmNvbSIsImdhbWVzUGxheWVkIjoxNSwiaGFzUGFzc3dvcmQiOmZhbHNlLCJwbGFuIjoiU3RhcnRlciIsInJvbGUiOiJTdHVkZW50Iiwic3RyaXBlIjoiY3VzX0trTFJ2d3RhWUU1emk5IiwiZGF0ZUNyZWF0ZWQiOiIyMDIxLTEyLTA5VDE3OjUwOjA0LjUzMloiLCJleHAiOjE2NDE1NzU4MDV9.NAWoHEfivAHKKJB6O9pGtSbNJfYTJHBwdArvOmjaQM4 401 (Unauthorized)
getName @ VM68:2
addCurrencies @ VM68:26
(anonymous) @ VM68:38
VM70:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at getName (<anonymous>:3:33)
    at async addCurrencies (<anonymous>:26:19)
getName @ VM68:3
await in getName (async)
(anonymous) @ VM68:38
VM68:2 Fetch failed loading: GET "https://api.blooket.com/api/users/verify-token?token=JWT+eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWIyNDFjYzZlZmJiMzE2OWU0YTBkMWYiLCJuYW1lIjoiRkJJX0FHRU5UX1V3VSIsImVtYWlsIjoiaGlteWxpZmUxMjNuaWNlQGdtYWlsLmNvbSIsImdhbWVzUGxheWVkIjoxNSwiaGFzUGFzc3dvcmQiOmZhbHNlLCJwbGFuIjoiU3RhcnRlciIsInJvbGUiOiJTdHVkZW50Iiwic3RyaXBlIjoiY3VzX0trTFJ2d3RhWUU1emk5IiwiZGF0ZUNyZWF0ZWQiOiIyMDIxLTEyLTA5VDE3OjUwOjA0LjUzMloiLCJleHAiOjE2NDE1NzU4MDV9.NAWoHEfivAHKKJB6O9pGtSbNJfYTJHBwdArvOmjaQM4".
So Can you somehow fix this pls! THX

**Comment by Oorwlly** [comment]
Did you just give us your token?

**Comment by DreamMinecraftBlooket** [comment]
Huh what does that mean? And wdym? Sent from Mail for Windows From: OorwllySent: Friday, December 31, 2021 4:01 PMTo: glixzzy/blooket-hackCc: Dream; AuthorSubject: Re: [glixzzy/blooket-hack] AddTokens Has a problem again!! (Issue #866) Did you just give us your token?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by DreamMinecraftBlooket** [comment]
WDYM

**Comment by glixzzy** [comment]
Blooket hack v3 has just been released! visit: https://github.com/glixzzy/blooket-hack for the scripts
