### ISSUE TITLE
Suggestion: Better / More Complex Spam Open Boxes?

### ISSUE THREAD

**Issue by Cerulean-MC** [glixzzy/blooket-hack#867]
Glizzy, could you make a new hack that merges the "spam boxes" and "sell dupe" hacks together? It's fine if you separate it from the original hacks, but it would be helpful, as you don't need to keep switching hacks to spam and sell, spam and sell. The idea is it first just does the spam open boxes hack, shows what you got and what you sold, and maybe even calculate the profits, like others have said already?

Thank you!

**Comment by glixzzy** [comment]
sure, i'll see if i can
