### ISSUE TITLE
Hacks No longer Working.

### ISSUE THREAD

**Issue by givemeusername199** [glixzzy/blooket-hack#870]
Hacks are no longer working, do not try to use them until they are fixed by glixzzy.

**Comment by sahar233** [comment]
:( awh sad same for me

**Comment by chansinyuen** [comment]
why is blooket doing so good?

**Comment by Mosasaurushoffmani** [comment]
not working

**Comment by glixzzy** [comment]
Blooket hack v3 has just been released! visit: https://github.com/glixzzy/blooket-hack for the scripts
