### ISSUE TITLE
Add tokens problem

### ISSUE THREAD

**Issue by sahar233** [glixzzy/blooket-hack#875]
the pop up wont come up and its not working :p

**Comment by chansinyuen** [comment]
yes, it isn't working :(

**Comment by chansinyuen** [comment]
it changed to a red colour thing :(

**Comment by Tha0ms** [comment]
Ye syntax error :(

**Comment by Mosasaurushoffmani** [comment]
not working :(

**Comment by sahar233** [comment]
so sad- rip hacks 2022- 💀

**Comment by Rookiehecker** [comment]
its patched :(

**Comment by glixzzy** [comment]
Blooket hack v3 has been released right now! visit: https://github.com/glixzzy/blooket-hack for the scripts
