### ISSUE TITLE
Spam box hack problem

### ISSUE THREAD

**Issue by BigDawg23** [glixzzy/blooket-hack#878]

**Comment by glixzzy** [comment]
please provide more information

**Comment by mikehawk223s** [comment]
I spam opened the blizzard box hoping to get santa but when I got the results it said 16 unidentified. I don't know if you can fix it but it would be something to look in please.

**Comment by mikehawk223s** [comment]
I thought it might have been a certain blook that was causing this but when I looked at my blooks I was missing some that i opened and I didn't have 16 or 17 of any blooks (17 because I have one of each)

**Comment by glixzzy** [comment]
fixed
