### ISSUE TITLE
Python daily token hack

### ISSUE THREAD

**Issue by hhheeellloooo** [glixzzy/blooket-hack#883]
I am confused about how to set this up I downloaded the most recent python software but don't know what to do from there. Can you please help?

**Comment by jrs1rules** [comment]
you have to be using chorme

**Comment by hhheeellloooo** [comment]
I am in chrome

**Comment by phdwquhqdhi** [comment]
do ctrl shift j than paste in console than just type 500 than hit enter. than refresh

**Comment by hhheeellloooo** [comment]
No not the add tokens the python daily tokens hack here: https://github.com/glixzzy/blooket-hack/tree/main/global/py

**Comment by hhheeellloooo** [comment]
Never mind I got it to work using replit.
