### ISSUE TITLE
Every Answer Correct Bookmarklet.

### ISSUE THREAD

**Issue by RandyPlayzMC** [glixzzy/blooket-hack#888]
Has a problem. Fix needed.

**Comment by mikehawk223s** [comment]
whats the problem

**Comment by mikehawk223s** [comment]
I tried the hack and it worked you need to make sure it says hack activated until you keep spamming the answers if you wait and it still doesn't work just make sure glixzzy sees this and he should look at it but like i said it works for me

**Comment by mikehawk223s** [comment]
also big sets could take a long time to load and may not work every time you try so try at least 3 times

**Comment by RandyPlayzMC** [comment]
ok

**Comment by RandyPlayzMC** [comment]
Thank you it worked.
