### ISSUE TITLE
Make the fetch Java Code for tower defence in a READme.md

### ISSUE THREAD

**Issue by Sai-Pamidi-8274** [glixzzy/blooket-hack#899]
I feel like you should leave the fetch code in a read me file because some people cant access them in my school due to a blockage against the website.. Please fix this issue, I really want to use this hack. 

Instead of sending us to another website put the fetch() code in a seperate readme

for example, so you can understand, if I make a repository that said "go here to get script" the user would probably have no access to it. So I would create a README.md that lists all fetch codes for each game or atleast towerdefece. 

Thanks for resolving this issue.

/-/~Sai

Edited- you can reach out to me - 
spamidi99@gmail.com
or discord - Saii#2695
or snap - sai_pamidi1
Thanks

**Comment by glixzzy** [comment]
not made in java.
