### ISSUE TITLE
Can you please split the hack of tokens and the hack for the XP?

### ISSUE THREAD

**Issue by BATheGamer** [glixzzy/blooket-hack#90]
Pls split the token hack and the XP hack. If not it might cause some inconvenience.

**Comment by BlooketLover** [comment]
Close This

**Comment by Ihatr1** [comment]
Just use them both.

If you don't want one, just use the same code for one. They reset at the same time, so there's practically no reason to separate one. Just don't use the XP if it bothers you, it adds tokens too.
