### ISSUE TITLE
My blooket Account Got Suspended 

### ISSUE THREAD

**Issue by BlooketHacks123** [glixzzy/blooket-hack#914]
My blooket account got suspended by using spam open box. Because my account got suspended does that mean it might get banned or I wont ever be able to access it again. Plz help

**Comment by coolman3289** [comment]
Try to re-login. Does it help?

**Comment by sushixhan** [comment]
this sorta happened to me, all I did to fix the problem was to restart my computer

**Comment by glixzzy** [comment]
LOL

**Comment by BlooketHacks123** [comment]
I restarted my computer, DIDN'T WORK XD. THIS SUCKS BALLS

**Comment by coolman3289** [comment]
Well, glixzzy did give a warning in the readme

**Comment by gimmy74** [comment]
LMAO

**Comment by AFLUFYPROTOGEN** [comment]
rip account
