### ISSUE TITLE
Spam Open Boxes

### ISSUE THREAD

**Issue by RandyPlayzMC** [glixzzy/blooket-hack#926]
It doesn't work as a bookmarklet. Sorry for so many issue requests.

**Comment by njberman** [comment]
Yes am having this problem as well for bookmark thank you.

**Comment by coolman3289** [comment]
Same.

**Comment by RandyPlayzMC** [comment]
please fix this

**Comment by GooseterV** [comment]
Use the updated code from this repository, and not schoolcheats.
