### ISSUE TITLE
check it out i got banned

### ISSUE THREAD

**Issue by Telantix** [glixzzy/blooket-hack#929]
![Screenshot 2022-01-06 11 33 34 AM](https://user-images.githubusercontent.com/95559328/148425732-890cbb26-bd6b-4f72-b792-5a43e28c57b7.png)

**Comment by Telantix** [comment]
got suddenly logged out when i used multitool box spammer and now my email got blocked haha

**Comment by Telantix** [comment]
![Screenshot 2022-01-06 11 39 52 AM](https://user-images.githubusercontent.com/95559328/148426591-49b0ee48-8d0c-4f2c-9d98-52072e732a34.png)

**Comment by Telantix** [comment]
I doubt you can be banned on a guest account, I only got banned for some
reason when I used the box spammer, oddly enough.

**Comment by Telantix** [comment]
i sent an email to blooket appealing my suspension lemme see what they say.

**Comment by RandyPlayzMC** [comment]
bookmarklet spam boxes isnt working

**Comment by Telantix** [comment]
I got unbanned I emailed them and this what they responded with:


We have unbanned you this time but if you continue using Blooket with
cheats then you will be banned again. Thanks, Spencer

**Comment by Cerulean-MC** [comment]
who did you email to get unbanned? i emailed contact-us@blooket.com

**Comment by Telantix** [comment]
I also emailed them

**Comment by Cerulean-MC** [comment]
you didn't say WHO you emailed to get ur account unbanned -.-

**Comment by Cerulean-MC** [comment]
WHO?

**Comment by Cerulean-MC** [comment]
Like, what email???

**Comment by Telantix** [comment]
The email that you just said that's the email that i sent a ban appeal to.

**Comment by phdwquhqdhi** [comment]
I also got banned and emailed them, i had like almost every blook so i hope they are nice

**Comment by Telantix** [comment]
good luck I hope you get unbanned.

**Comment by porg13231** [comment]
i also got banned! 🤬

**Comment by Telantix** [comment]
email contact-us@blooket.com and ask if you can be unbanned.

**Comment by vincent6748** [comment]
Did you put the right username? and password?

**Comment by Telantix** [comment]
Yes and I also made an alt to test the spam box and sure enough when I it
automatically logged me out and I tried to log back in it said that your
account has been suspended for violating the terms of service.

**Comment by crying4u** [comment]
o0f i guess .,.

**Comment by GooseterV** [comment]
To get unbanned, contact contact-us@blooket.com . Nobody here can do anything about it.

**Comment by Telantix** [comment]
I know that, if you read the previous replies to this issue it has been
resolved.

**Comment by porg13231** [comment]
> i also got banned! 🤬

I got unbanned!!!!😄

**Comment by kingofninjaz** [comment]
i got band do u sent it on the acc u got band or aanother alt
