### ISSUE TITLE
Add back the bookmarklets

### ISSUE THREAD

**Issue by Atlas-Can-Code** [glixzzy/blooket-hack#930]
I’m kinda new so it would be really helpful to just put bookmarklets for the scripts in the readme files for copy & pasting. Usually the raw obfuscated code in the bookmarklets doesn’t work for mobile but bookmarklets do.

**Comment by Telantix** [comment]
just copy the raw code and put javascript: in front of it i did that it works fine for mobile.

**Comment by Atlas-Can-Code** [comment]
On safari?

**Comment by Telantix** [comment]
GitHub is the same on every browser .-.

**Comment by Atlas-Can-Code** [comment]
Yeah but they all throw errors; ALL of them.

**Comment by jrs1rules** [comment]
You have to be user chrome.

**Comment by jrs1rules** [comment]
useing

**Comment by Atlas-Can-Code** [comment]
Errors still occur

**Comment by GooseterV** [comment]
For mobile safari use refer to [this](https://github.com/GooseterV/Blooket/wiki/Methods#ios--apple-mobile-devices)
If he added files with bookmarklets, they would be useless because when you paste something with `javascript:blah` in it, it will only paste the `blah` part.
