### ISSUE TITLE
Glizzy I got banneddddddd

### ISSUE THREAD

**Issue by Cerulean-MC** [glixzzy/blooket-hack#932]
bruh i had 2 chroma

**Comment by hihihhihihihihihihihihihih** [comment]
sad life

**Comment by ilikecatss** [comment]
welp
not his fault
he already said that you shouldn't use it unless u wanna get banned

**Comment by ilikecatss** [comment]
contact-us@blooket.com 
to appeal ur ban

**Comment by Staraner** [comment]
> 

Yo I joined 10 days ago and I am level 86 and 37 different blooks unlocked but I have no chromas :(

**Comment by GooseterV** [comment]
Refer to other posts, do not complain here as we cannot do anything.
You used the hacks which is giving them valid reasons to ban.
Contact blooket support if you want to be unbanned.
