### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by phdwquhqdhi** [glixzzy/blooket-hack#933]
i was using spam open boxes, i got astronaut, mega bot, bby shark and than opened medieval and got banned, i logged out and said no acc for my email, i went to sign up and said there is an acc for my email.HELP

**Comment by hihihhihihihihihihihihihih** [comment]
contact-us@blooket.com

**Comment by jrs1rules** [comment]
Well he was hacking so he is not going to get his account hack.

**Comment by crying4u** [comment]
Try to delete ur other acc

**Comment by GooseterV** [comment]
- If you don't want to be banned don't use spam open boxes or sell dupes
- Contact blooket support to be unbanned, don't complain here
- Nobody here can help you, seeing as it's an issue with you and blooket
