### ISSUE TITLE
 if you dont want your blooket account banned DONT USE SPAM BOX

### ISSUE THREAD

**Issue by Telantix** [glixzzy/blooket-hack#934]
spam box for some reason is triggering like auto bans on blooket so if you dont want your blooket account to  get banned dont use spam boxes blooket can detect it.

**Comment by Telantix** [comment]
however if you do get banned email contact-us@blooket.com and appeal your ban thats how i got unbanned

**Comment by EdenEmerald** [comment]
That is scary to know. Did you get ur ACC unbanned?

**Comment by Telantix** [comment]
Yes I emailed them

**Comment by Mosasaurushoffmani** [comment]
noice

**Comment by Leejunji** [comment]
Yes thank you

**Comment by Leejunji** [comment]
Now I don’t have a account

**Comment by jrs1rules** [comment]
I don,t think it will work as you guys are hacking.

**Comment by EdenEmerald** [comment]
> Now I don’t have a account

was it from the spam hacking?

**Comment by Telantix** [comment]
yea probably

**Comment by Leejunji** [comment]
Log out log in again but you will start from level zero and everything
zero🙁

**Comment by GooseterV** [comment]
As stated in the title, you will only be banned for using hacks that spam the api. If you do get suspended you can contact blooket support to get your account back.

**Comment by iplayblooket** [comment]
oof
