### ISSUE TITLE
Why the santa workshop is not coming???

### ISSUE THREAD

**Issue by HahHeanKee** [glixzzy/blooket-hack#936]
I lose than a hacker

**Comment by RandyPlayzMC** [comment]
he not gonna add it cuz santa workshop getting removed soon

**Comment by GooseterV** [comment]
Santa's workshop is a LTM, meaning it won't be active all the time and hence hacks will be useless for it. He would have to make new ones and he may not have the time to do this, when the thing he's making them for isn't there anymore.
