### ISSUE TITLE
School problems

### ISSUE THREAD

**Issue by Araki01** [glixzzy/blooket-hack#937]
My school has blocked the "school hax" website, I was wondering if anyone could copy all the scripts and send them to me so I could still use them. Me and all my friends would be very thankful if we could still cheat the game.

**Comment by coolman3289** [comment]
How about this: https://schoolcheats.pages.dev/

**Comment by yapgamer** [comment]
On the dev version i cant click on buttons for Blooket one, EdPuzzle cant get token due to blocked extensions, most of other ones work but when i try to use it says network error

**Comment by coolman3289** [comment]
Same I thought it wa Shaun me.

**Comment by GooseterV** [comment]
IS there a problem with using the cheats from this repository on github?

**Comment by yapgamer** [comment]
no, its just that this repository doesn't have hacks for other sites
