### ISSUE TITLE
Racing hack broken

### ISSUE THREAD

**Issue by Atlas-Can-Code** [glixzzy/blooket-hack#940]
Instant win is broken using on safari as bookmarklet
I’m pretty sure I did everything correctly

**Comment by Atlas-Can-Code** [comment]
Revision, ive tried almost all of the hacks and they all throw errors; using all of them as a bookmarklet on iOS and using safari.

**Comment by Telantix** [comment]
type javascript: in front of the script before pasting into the url

**Comment by ilikecatss** [comment]
I tried and it also didnt work
someone pls fix

**Comment by jrs1rules** [comment]
You have to be using chrome not ios if you use ios it will not work.

**Comment by Atlas-Can-Code** [comment]
They all still do not work. Chrome doesn’t help, it’s the same thing.

**Comment by Staraner** [comment]
Racing hacks are useless

**Comment by GooseterV** [comment]
If you're using ios, i made [a guide](https://github.com/GooseterV/Blooket/wiki/Methods#ios--apple-mobile-devices) in my own blooket repository, if you're using anything else you can use the methods mentioned in this repository. 

For using the racing hacks, they should be marked as deprecated and no longer supported.
He will most likely not update racing hacks, so don't count on it.
