### ISSUE TITLE
Plz add anti-ban hack

### ISSUE THREAD

**Issue by hihihhihihihihihihihihihih** [glixzzy/blooket-hack#941]

**Comment by ilikecatss** [comment]
...
NOT POSSIBLE

**Comment by gimmy74** [comment]
This is debatable, if there is an api page for the ban and unban function this is very much possible but we don't know yet so.

**Comment by coolman3289** [comment]
No, it’s server-sided

**Comment by somekidwhoexists** [comment]
Are bans ip based because if so you could reset your ip

**Comment by GooseterV** [comment]
Only blooket admins are able to unban people, hence getting unbanned will only happen by contacting blooket support. The only hacks that will get you banned are the ones that spam the api.
