### ISSUE TITLE
ALL HACKS ARE NOT WORKING

### ISSUE THREAD

**Issue by vincent6748** [glixzzy/blooket-hack#942]

**Comment by Dankcraft** [comment]
they do work

**Comment by ilikecatss** [comment]
they do

**Comment by Staraner** [comment]
Did you mean: All hacks are working?

**Comment by FreezeLucif3r** [comment]
@Staraner Stop trying to impersonate grammarly.

**Comment by GooseterV** [comment]
All of the hacks are currently working and up-to-date. If you still experience errors, elaborate and send information on what the error is instead of "ALL HACKS AER NOT WORKING".
