### ISSUE TITLE
Spam open boxes

### ISSUE THREAD

**Issue by sahar233** [glixzzy/blooket-hack#945]
The hack does not work it doesn't have a pop up or anything.

**Comment by ilikecatss** [comment]
dont use it for now
Someone said you will get banned for using spam open boxes

**Comment by sahar233** [comment]
ooo kk tysm for letting me know

**Comment by Staraner** [comment]
> The hack does not work it doesn't have a pop up or anything.

Its works lol :+1:

**Comment by GooseterV** [comment]
1. I wouldn't recommend using it unless you want to get your account banned
2. It is working fine.
