### ISSUE TITLE
How to get banned

### ISSUE THREAD

**Issue by jrs1rules** [glixzzy/blooket-hack#946]
can I be told how to do it.

**Comment by Piplup7575** [comment]
use these scripts excessively in a public game :D

**Comment by jrs1rules** [comment]
ok

**Comment by jrs1rules** [comment]
look like i got to wait for a new public game.

**Comment by Nobody-720** [comment]
**Why The Hell DO You Want To Get Banned ;=;**

**Comment by FreezeLucif3r** [comment]
Bruh what are these issues

**Comment by HawkFalcon787** [comment]
Use Spam Boxes to GET banned

**Comment by jrs1rules** [comment]
I was using spam boxes it dose not work. I want to see what happens if I get banned.

**Comment by HawkFalcon787** [comment]
> I was using spam boxes it dose not work. I want to see what happens if I get banned.

Yes it does not work. Since he disabled so you DON'T get banned. Maybe ask them? But I know. You won't be able to login or do anything. But they will unban you and you will not lose any stats

**Comment by Telantix** [comment]
use an old version of spam boxes

**Comment by coolman3289** [comment]
This si who it looks: 
![](https://user-images.githubusercontent.com/73669084/148287313-30793b91-b0d1-430b-879b-398a23b9b197.png)

**Comment by crying4u** [comment]
sucks :/ i guess

**Comment by GooseterV** [comment]
If you really wanted to get banned, you could use spam open boxes and sell all dupes very rapidly.
