### ISSUE TITLE
School cheats site not working

### ISSUE THREAD

**Issue by yapgamer** [glixzzy/blooket-hack#950]
on the blooket one I cant pick the games type or global buttons, other ones have network error, cant find token for edpuzzle due to blocked extensions, Note im on the dev one cuz normal one blocked.

**Comment by coolman3289** [comment]
He means https://schoolcheats.pages.dev/blooket/

**Comment by coolman3289** [comment]
@glixzzy

**Comment by glixzzy** [comment]
use this now https://github.com/glixzzy/blooket-hack
