### ISSUE TITLE
Why can you only use clear enemies once?

### ISSUE THREAD

**Issue by RandyPlayzMC** [glixzzy/blooket-hack#951]
I`m using the bookmarklet method. So I don´t know how it works for console method.

**Comment by HawkFalcon787** [comment]
You sure this is the new version, v3. Go to the code and copy the new one.

**Comment by RandyPlayzMC** [comment]
Yes I'm using th new v3. But also know that I'm using the Bookmarklet method.

**Comment by HawkFalcon787** [comment]
Well then, I have no idea. Here in gbasil.dev/blooket, the multitool has an option that can use clear enemies multiple times.

**Comment by GooseterV** [comment]
To use the same script multiple times on a page, you need to refresh the page (will not work in some active games). If you have access to variable names, you can run `javascript: delete {varname}` for each variable and run again.
