### ISSUE TITLE
might need to look at the code for spam boxes again.

### ISSUE THREAD

**Issue by EdenEmerald** [glixzzy/blooket-hack#952]
I dont know if the spam boxes hack does work, or if you guys are still working on it, but for some reason, I cant seem to get the pop up menu from it. 

When you have the time, Thank you

EdenEmerald

**Comment by HawkFalcon787** [comment]
It is intentional, you will get banned if you use it.

**Comment by MrGamer-FS** [comment]
Is there a way to just make it not ban you?

**Comment by HawkFalcon787** [comment]
Nope, not yet

**Comment by MrGamer-FS** [comment]
if there's a page the admins use can you get into it to look for the user's name and unban them? it that possible?

**Comment by edward-not** [comment]
> if there's a page the admins use can you get into it to look for the user's name and unban them? it that possible?

No, the login page will submit a query using PHP to some database of theirs, probably an SQL one, to check if the user is banned. Of course, we cannot edit this, as it is not our database.

**Comment by edward-not** [comment]
The query is sent via HTTPS to `https://api.blooket.com/api/users/login`.

That will then proceed to respond with an error code if the login is invalid. For example, this is the HTTPS response for a wrong email and password:


`{"errType":"password","msg":"Email/User and password don't match.","success":false}`

**Comment by HOST000** [comment]
that sucks

**Comment by netsaosa** [comment]
> Contributor

correction: blooket does not use sql lol

**Comment by edward-not** [comment]
> 

lol i said probably an SQL one not certainly
