### ISSUE TITLE
do not use anymore hacks

### ISSUE THREAD

**Issue by JOELLRX13246** [glixzzy/blooket-hack#953]
why,why,why!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Cretawwin3** [comment]
update terms of service

**Comment by XkXkpro** [comment]
yea

**Comment by XkXkpro** [comment]
glixzzy is a piece of shit forever shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit glixzzy is shit!

**Comment by MrGamer-FS** [comment]
shut it just because you got banned doesn't mean glizzy is bad he clearly states do not use hacks if you don't wanna get banned

**Comment by FallGuysFan1234** [comment]
Yea MrGamer is right, its not his fault if you get banned >:(

**Comment by ilikecatss** [comment]
> glixzzy is a piece of shit forever shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit shit glixzzy is shit!

ur probably just a little kid who rages when you get banned
JUST CONTACT THE  BLOOKET TEAM AND APPEAL FOR YOUR BAN
ITS THAT EASY

**Comment by ilikecatss** [comment]
there is no point in leaving an unnecessary issue
this "issue" just serves the purpose of insulting glizzy

**Comment by jrs1rules** [comment]
true

**Comment by vincent6748** [comment]
Shut up idiots

**Comment by edward-not** [comment]
JESUS LORD STOP GETTING MAD BECAUSE U GOT BANNED IT LITERALLY SAYS IN THE README.MD THAT GLIXZZY IS NOT RESPONSIBLE FOR ANY ACCOUNT BANNING

**Comment by nottoosaltysurelol** [comment]
glixzzy's not responsible for it, don't use the hacks if so you don't get banned

**Comment by GooseterV** [comment]
1. Getting banned is something you should expect when using hacks/cheats in a game, if you don't want to get banned you shouldn't use them.
2. Gliz isn't responsible for anything **YOU** do with his cheats.
3. If you really want to be unbanned, read blooket's ToS/ToU again and contact blooket support at the above email.

**Comment by spiralerror** [comment]
im just waiting for him to update and fix some of them and if i get banned ill just make another account not that hard
