### ISSUE TITLE
Bookmarklet method to get coins doesn't work in Cafe

### ISSUE THREAD

**Issue by RandyPlayzMC** [glixzzy/blooket-hack#957]
Please fix glixzzy. Pls

**Comment by ilikecatss** [comment]
does work
tried 4+ times
all worked

**Comment by myronrice** [comment]
how i do book mark

**Comment by NotGlixzzy** [comment]
It's currently not working for me either, but if it works for other people just re-add it and try at another time, or on a different account.

**Comment by GooseterV** [comment]
- If you're using cafe get coins for solo cafe, it will only work on a hosted game
- Bookmarklets should all work, you may need to update them with the newest release.
