### ISSUE TITLE
IF We Use Hack Did We Will Get Banned ? [ Also Have Yu Added Not To Sell Dupes Legendary Blook In Sell Dupes Blook ] 

### ISSUE THREAD

**Issue by Nobody-720** [glixzzy/blooket-hack#960]
****

**Comment by ilikecatss** [comment]
don't use spam open box
you will get banned

**Comment by NotGlizzy** [comment]
@Nobody-720 Your issue is unclear to me. Furthermore, the game Crypto Hack is not compatible with Gold Quest Chest ESP.

**Comment by Staraner** [comment]
I used hack for 22 days after Updated Terms of Service and Privacy Policy and I still didn't get banned and also spam open box works and glixzzy is a piece of jesus thanks XD

**Comment by crying4u** [comment]
Piece of Jesus? ;-;

**Comment by GooseterV** [comment]
1. You will only get banned if you spam the api  with scripts such as spam open boxes.
2. Sell all dupes will do all blooks and not just legendaries
