### ISSUE TITLE
my 2-3 friends got banned

### ISSUE THREAD

**Issue by nottoosaltysurelol** [glixzzy/blooket-hack#965]
so when we did a blooket, 2 or 3 of my friends got banned and they didn't use spam boxes hack for some reason. I was wondering if any other hacks were used to get banned, my friend may be wondering about that. I'm still trying to know which one it is (one of my friends cheated of getting the answers all right but it wasn't working for me though, he got caught anyway)

**Comment by coolman3289** [comment]
Lol that does nothing

**Comment by coolman3289** [comment]
They ban you from logs in blooket, it’s not you parents banning you.

**Comment by coolman3289** [comment]
If you friends used the hacks when multiple staff where online, maybe. But no hack othe r than spam open boxes autoban.

**Comment by coolman3289** [comment]
Did they get banned right after they used them, or after some time?

**Comment by gimmy74** [comment]
> They ban you from logs in blooket, it’s not you parents banning you.

Almost everything is stored with local storage and cookies including your blooket token

**Comment by nottoosaltysurelol** [comment]
ahem. they are school emails and usernames

**Comment by nottoosaltysurelol** [comment]
> Did they get banned right after they used them, or after some time?

I'm not sure, my friend mason got banned by using hacks but I dunno which one is it, and my other friend said he just got kicked out.

**Comment by coolman3289** [comment]
If they got banned right after, that means Blooket detected it,if after some time, probably you got reported

**Comment by glixzzy** [comment]
All of you who commented and what yall was most likely false. As far as I know, using spam open boxes and sell dupe blooks cheat is a autoban I don't know if using in game hacks would get you banned.

**Comment by coolman3289** [comment]
I did sell dupe and it does not ban me

**Comment by coolman3289** [comment]
I use it all the time still

**Comment by coolman3289** [comment]
I used it a minute ago
