### ISSUE TITLE
"Get all Blooks" doesn't work

### ISSUE THREAD

**Issue by SirMadMa** [glixzzy/blooket-hack#966]
The "Get all Blooks" doesn't work. even if i'm in the Blook selecting page.

**Comment by vincent6748** [comment]
Yes It works, you just have to be in a game that is hosted and then do the hack

**Comment by SirMadMa** [comment]
I'm a idiot, thanks vincent!

**Comment by snpainter** [comment]
thanks

**Comment by lishangqiu** [comment]
Pretty sure the "unlocked" ones are client-side? When you refresh its gone?

**Comment by MAXXINCODING** [comment]
it just stopped working today for me

**Comment by DanielTan123456** [comment]
can't copy
Why?
It display eror

**Comment by GooseterV** [comment]
@DanielTan123456 , this is not an error anyone else can fix, it's simply a one time thing that will occur sometimes whenever you copy using copy button. If it continues not to work you can use the schoolcheats copy version.
