### ISSUE TITLE
Spam Open Boxes

### ISSUE THREAD

**Issue by SirMadMa** [glixzzy/blooket-hack#967]
It just says "Unauthorized" whenever i try the Spam Open Boxes hack.

**Comment by crying4u** [comment]
that sucks .,.

**Comment by NotGlizzy** [comment]
I am not going to confirm this, because I feel this is pointless. This has an extremely high chance of getting your account banned. Just set up an auto clicker or open them legit.

**Comment by Telantix** [comment]
its cause spam open boxes can get you banned now you wouldnt want that would you?

**Comment by glixzzy** [comment]
probably a glitch, but it works fine.

**Comment by crying4u** [comment]
Have a Nice day.
