### ISSUE TITLE
Update Scripts

### ISSUE THREAD

**Issue by yodaluca23** [glixzzy/blooket-hack#970]
Please update the scripts to the ones from schoolcheats.net, because it's blocked at school.
Every time I use pages.schoolcheats.dev it doesn't work because of "Network Error".

**Comment by glixzzy** [comment]
use this now https://github.com/glixzzy/blooket-hack

**Comment by yodaluca23** [comment]
???? that's literally the same thing

**Comment by glixzzy** [comment]
> @glixzzy ???? that's literally the same thing

no???? everything is updated here: https://github.com/glixzzy/blooket-hack .
