### ISSUE TITLE
The Clear in tower defense does not work

### ISSUE THREAD

**Issue by nahuNOW** [glixzzy/blooket-hack#973]

**Comment by gimmy74** [comment]
no one can help you if you don't tell us whats wrong and what part of the cheat isnt working

**Comment by nahuNOW** [comment]
When i try to run the hack nothing happens and the enemies ate still yhere

**Comment by NotGlizzy** [comment]
Still works, try adding it again.
![image](https://user-images.githubusercontent.com/97697915/149643662-ce083790-b704-43d3-86c4-b20471baf1e5.png)

**Comment by edward-not** [comment]
Obviously, the program does not permanently stop enemies from spawning, just removes the present ones. If this is what you meant by 'not working', please close the issue
