### ISSUE TITLE
Problem with code.

### ISSUE THREAD

**Issue by spookycat117** [glixzzy/blooket-hack#975]
I am new to this website and coding a whole. I watched the video on how to do one of the hacks. Everything was going fine until the video included a much different interface then what was on the website itself.

![image](https://user-images.githubusercontent.com/97820410/149648699-2f3b2a35-65cd-4838-878e-655bf50db8a8.png)

![image](https://user-images.githubusercontent.com/97820410/149648729-4e2d27f3-3164-4be4-8750-ec96210f6593.png)
 
If someone could help me solve this issue that would be great.

**Comment by glixzzy** [comment]
yeah a lot of stuff has changed in the past months, just copy the whole code in the file and paste it in the console. You could also search on youtube on the hacks. Theres a lot of videos.
