### ISSUE TITLE
Get all blooks help

### ISSUE THREAD

**Issue by Mikoltheprogod** [glixzzy/blooket-hack#978]
Make the get all blooks thing make you permanently have the blooks so that i can impress my friends because when i reload the screen it gets rid of it all, so pls

**Comment by somekidwhoexists** [comment]
@Piplup7575 he means the other one

**Comment by edward-not** [comment]
> Make the get all blooks thing make you permanently have the blooks so that i can impress my friends because when i reload the screen it gets rid of it all, so pls

Not sure whether ur honestly braindead or what. A million people have said this and they all get the same response: THE BLOOKS ATTACHED TO AN ACCOUNT ARE MANAGED SERVER SIDE IN SOME KINDA SQL DATABASE AND WE CANT EDIT THAT
