### ISSUE TITLE
One-Time Use.

### ISSUE THREAD

**Issue by benzywenzy** [glixzzy/blooket-hack#979]
I believe there is a problem probably in the coding of every single script because since most of the people using the blooket hacks, they're using it plenty of times. Which meaning since I have already tried experimenting with the hacks on my own time, I've come to realize that the hacks are able to be ONLY used for one time. If you're able to fix this problem. Please fix it later or on your free time. And plus, I'm using the bookmarklet method so it would be probably more common to experience this type of issue.

**Comment by glixzzy** [comment]
i'll look into it, thank you.

**Comment by Goldenium11** [comment]
This happens to me for some of the hacks. For some of them, I can use them multiple times for a page. Other ones I can only use once for a page.

**Comment by FallGuysFan1234** [comment]
Yea this happens to me too

**Comment by GooseterV** [comment]
For now, when running it, you can do this:
```js
async () => (codehere)
```
to set each of the variables in a function instead of globals

**Comment by netsaosa** [comment]
still valid, as im aware. leaving this open...
