### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by Mikoltheprogod** [glixzzy/blooket-hack#993]
Why can you only get 500 tokens daily, can you not make it more for the entertainment purposes of the infrastructure of the bisector adding up to the isosceles triangle of the people.

**Comment by jrs1rules** [comment]
Huh>

**Comment by BlooketHackerx** [comment]
I wish you could get 10000000000

**Comment by Piplup7575** [comment]
Uh...
That is not possible?
The amount of tokens you can get in a day is controlled by the server, so there is no way to change that.

**Comment by GooseterV** [comment]
As piplup7575 said,
> the amount of tokens you get in a day is controlled by the server, so there is no way to change that
The daily limit is set server sided, if you change the request sent to have more than 500 tokens, it will still only give you 500.
If he were to make it possible to input a number above 500 tokens, people would be complaining about only receiving 500 tokens when they asked for, persay 1e9 (1B)
